var annotated_dup =
[
    [ "Grindstone", null, [
      [ "Assets", null, [
        [ "AssetPackSerializer", null, [
          [ "AssetPackageSerializer", "classGrindstone_1_1Assets_1_1AssetPackSerializer_1_1AssetPackageSerializer.html", null ]
        ] ],
        [ "ArchiveAssetLoader", "classGrindstone_1_1Assets_1_1ArchiveAssetLoader.html", null ],
        [ "ArchiveContentFile", "structGrindstone_1_1Assets_1_1ArchiveContentFile.html", "structGrindstone_1_1Assets_1_1ArchiveContentFile" ],
        [ "ArchiveDirectory", "structGrindstone_1_1Assets_1_1ArchiveDirectory.html", "structGrindstone_1_1Assets_1_1ArchiveDirectory" ],
        [ "ArchiveDirectoryDeserializer", "classGrindstone_1_1Assets_1_1ArchiveDirectoryDeserializer.html", null ],
        [ "ArchiveDirectoryFile", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile.html", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile" ],
        [ "AssetLoadBinaryResult", "structGrindstone_1_1Assets_1_1AssetLoadBinaryResult.html", null ],
        [ "AssetLoader", "classGrindstone_1_1Assets_1_1AssetLoader.html", null ],
        [ "AssetLoadTextResult", "structGrindstone_1_1Assets_1_1AssetLoadTextResult.html", null ],
        [ "AssetManager", "classGrindstone_1_1Assets_1_1AssetManager.html", null ],
        [ "AssetRegistry", "classGrindstone_1_1Assets_1_1AssetRegistry.html", "classGrindstone_1_1Assets_1_1AssetRegistry" ],
        [ "FileAssetLoader", "classGrindstone_1_1Assets_1_1FileAssetLoader.html", null ]
      ] ],
      [ "Audio", null, [
        [ "AudioClipAsset", "structGrindstone_1_1Audio_1_1AudioClipAsset.html", null ],
        [ "AudioClipImporter", "classGrindstone_1_1Audio_1_1AudioClipImporter.html", null ],
        [ "Core", "classGrindstone_1_1Audio_1_1Core.html", null ],
        [ "Source", "classGrindstone_1_1Audio_1_1Source.html", "classGrindstone_1_1Audio_1_1Source" ]
      ] ],
      [ "BuildSettings", null, [
        [ "PluginBuildSettings", "classGrindstone_1_1BuildSettings_1_1PluginBuildSettings.html", null ],
        [ "SceneBuildSettings", "classGrindstone_1_1BuildSettings_1_1SceneBuildSettings.html", null ]
      ] ],
      [ "Containers", null, [
        [ "ArrayIterator", "structGrindstone_1_1Containers_1_1ArrayIterator.html", null ],
        [ "Bitset", "classGrindstone_1_1Containers_1_1Bitset.html", null ],
        [ "BitsetEnum", "classGrindstone_1_1Containers_1_1BitsetEnum.html", "classGrindstone_1_1Containers_1_1BitsetEnum" ],
        [ "BitsetFlags", "classGrindstone_1_1Containers_1_1BitsetFlags.html", "classGrindstone_1_1Containers_1_1BitsetFlags" ],
        [ "ConstArrayIterator", "structGrindstone_1_1Containers_1_1ConstArrayIterator.html", null ],
        [ "ConstReverseArrayIterator", "structGrindstone_1_1Containers_1_1ConstReverseArrayIterator.html", null ],
        [ "DynamicArray", "classGrindstone_1_1Containers_1_1DynamicArray.html", null ],
        [ "ReverseArrayIterator", "structGrindstone_1_1Containers_1_1ReverseArrayIterator.html", null ],
        [ "ReverseRange", "classGrindstone_1_1Containers_1_1ReverseRange.html", null ],
        [ "ReverseRangeTemp", "classGrindstone_1_1Containers_1_1ReverseRangeTemp.html", null ],
        [ "Span", "classGrindstone_1_1Containers_1_1Span.html", null ]
      ] ],
      [ "ECS", null, [
        [ "ComponentFunctions", "classGrindstone_1_1ECS_1_1ComponentFunctions.html", null ],
        [ "ComponentRegistrar", "classGrindstone_1_1ECS_1_1ComponentRegistrar.html", null ],
        [ "Entity", "classGrindstone_1_1ECS_1_1Entity.html", null ],
        [ "has_clone", "structGrindstone_1_1ECS_1_1has__clone.html", null ],
        [ "has_clone< T, std::void_t< decltype(std::declval< const T & >().Clone(std::declval< Grindstone::WorldContextSet & >(), std::declval< entt::entity >()))> >", "structGrindstone_1_1ECS_1_1has__clone_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_dd43ab67fe6f91e44f4828392a2436bc.html", null ],
        [ "ISystem", "classGrindstone_1_1ECS_1_1ISystem.html", null ],
        [ "SystemRegistrar", "classGrindstone_1_1ECS_1_1SystemRegistrar.html", null ]
      ] ],
      [ "Editor", null, [
        [ "ImguiEditor", null, [
          [ "Settings", null, [
            [ "BasePage", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1BasePage.html", null ],
            [ "Build", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build.html", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build" ],
            [ "CodeTools", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1CodeTools.html", null ],
            [ "CompilerProperties", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1CompilerProperties.html", null ],
            [ "PageData", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PageData.html", null ],
            [ "Platforms", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Platforms.html", null ],
            [ "PlatformWindows", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PlatformWindows.html", null ],
            [ "Plugins", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Plugins.html", null ],
            [ "ProjectSettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1ProjectSettingsWindow.html", null ],
            [ "SettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1SettingsWindow.html", null ],
            [ "UserSettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1UserSettingsWindow.html", null ]
          ] ],
          [ "AssetBrowserPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetBrowserPanel.html", null ],
          [ "AssetPicker", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetPicker.html", null ],
          [ "BuildPopup", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1BuildPopup.html", null ],
          [ "ComponentInspector", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ComponentInspector.html", null ],
          [ "ConsolePanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ConsolePanel.html", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ConsolePanel" ],
          [ "ControlBar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ControlBar.html", null ],
          [ "ImguiEditor", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiEditor.html", null ],
          [ "ImguiInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiInput.html", null ],
          [ "ImguiInterface", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiInterface.html", null ],
          [ "ImguiRenderer", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiRenderer.html", null ],
          [ "ImguiRendererVulkan", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiRendererVulkan.html", null ],
          [ "InspectorPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1InspectorPanel.html", null ],
          [ "MaterialInspector", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialInspector.html", null ],
          [ "MaterialParameter", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialParameter.html", null ],
          [ "Menubar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Menubar.html", null ],
          [ "NewComponentInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1NewComponentInput.html", null ],
          [ "Sampler", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Sampler.html", null ],
          [ "SceneHeirarchyPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SceneHeirarchyPanel.html", null ],
          [ "StatsPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatsPanel.html", null ],
          [ "StatusBar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatusBar.html", null ],
          [ "SuggestedInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SuggestedInput.html", null ],
          [ "SystemPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SystemPanel.html", null ],
          [ "TaskPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1TaskPanel.html", null ],
          [ "TracingPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1TracingPanel.html", null ],
          [ "ViewportPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ViewportPanel.html", null ]
        ] ],
        [ "Importers", null, [
          [ "StandardMaterialCreateInfo", "structGrindstone_1_1Editor_1_1Importers_1_1StandardMaterialCreateInfo.html", null ]
        ] ],
        [ "ScriptBuilder", null, [
          [ "CSharpBuildManager", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpBuildManager.html", null ],
          [ "CSharpProjectBuilder", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpProjectBuilder.html", null ],
          [ "CSharpProjectMetaData", "structGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpProjectMetaData.html", null ],
          [ "SolutionBuilder", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1SolutionBuilder.html", null ]
        ] ],
        [ "AddComponentCommand", "classGrindstone_1_1Editor_1_1AddComponentCommand.html", null ],
        [ "AddEntityCommand", "classGrindstone_1_1Editor_1_1AddEntityCommand.html", null ],
        [ "AssetRegistry", "classGrindstone_1_1Editor_1_1AssetRegistry.html", "classGrindstone_1_1Editor_1_1AssetRegistry" ],
        [ "AssetTemplateRegistry", "classGrindstone_1_1Editor_1_1AssetTemplateRegistry.html", "classGrindstone_1_1Editor_1_1AssetTemplateRegistry" ],
        [ "BaseCommand", "classGrindstone_1_1Editor_1_1BaseCommand.html", null ],
        [ "BuildProcessStats", "structGrindstone_1_1Editor_1_1BuildProcessStats.html", null ],
        [ "CommandList", "classGrindstone_1_1Editor_1_1CommandList.html", null ],
        [ "DeleteComponentCommand", "classGrindstone_1_1Editor_1_1DeleteComponentCommand.html", null ],
        [ "DeleteEntityCommand", "classGrindstone_1_1Editor_1_1DeleteEntityCommand.html", null ],
        [ "EditorCamera", "classGrindstone_1_1Editor_1_1EditorCamera.html", null ],
        [ "FileManager", "classGrindstone_1_1Editor_1_1FileManager.html", "classGrindstone_1_1Editor_1_1FileManager" ],
        [ "GitManager", "classGrindstone_1_1Editor_1_1GitManager.html", null ],
        [ "GizmoRenderer", "classGrindstone_1_1Editor_1_1GizmoRenderer.html", "classGrindstone_1_1Editor_1_1GizmoRenderer" ],
        [ "GridRenderer", "classGrindstone_1_1Editor_1_1GridRenderer.html", null ],
        [ "IEditor", "classGrindstone_1_1Editor_1_1IEditor.html", null ],
        [ "ImporterData", "structGrindstone_1_1Editor_1_1ImporterData.html", null ],
        [ "ImporterSettings", "structGrindstone_1_1Editor_1_1ImporterSettings.html", "structGrindstone_1_1Editor_1_1ImporterSettings" ],
        [ "JointCommand", "classGrindstone_1_1Editor_1_1JointCommand.html", null ],
        [ "Manager", "classGrindstone_1_1Editor_1_1Manager.html", null ],
        [ "MetaFile", "classGrindstone_1_1Editor_1_1MetaFile.html", "classGrindstone_1_1Editor_1_1MetaFile" ],
        [ "Selection", "classGrindstone_1_1Editor_1_1Selection.html", null ],
        [ "SetDataCommand", "classGrindstone_1_1Editor_1_1SetDataCommand.html", null ],
        [ "Task", "structGrindstone_1_1Editor_1_1Task.html", null ],
        [ "TaskSystem", "classGrindstone_1_1Editor_1_1TaskSystem.html", null ]
      ] ],
      [ "Events", null, [
        [ "BaseEvent", "structGrindstone_1_1Events_1_1BaseEvent.html", null ],
        [ "CharacterTypedEvent", "structGrindstone_1_1Events_1_1CharacterTypedEvent.html", null ],
        [ "Dispatcher", "classGrindstone_1_1Events_1_1Dispatcher.html", null ],
        [ "KeyPressEvent", "structGrindstone_1_1Events_1_1KeyPressEvent.html", null ],
        [ "MouseMovedEvent", "structGrindstone_1_1Events_1_1MouseMovedEvent.html", null ],
        [ "MousePressEvent", "structGrindstone_1_1Events_1_1MousePressEvent.html", null ],
        [ "MouseScrolledEvent", "structGrindstone_1_1Events_1_1MouseScrolledEvent.html", null ],
        [ "PrintMessageEvent", "structGrindstone_1_1Events_1_1PrintMessageEvent.html", null ],
        [ "WindowForceQuitEvent", "structGrindstone_1_1Events_1_1WindowForceQuitEvent.html", null ],
        [ "WindowKillFocusEvent", "structGrindstone_1_1Events_1_1WindowKillFocusEvent.html", null ],
        [ "WindowMovedEvent", "structGrindstone_1_1Events_1_1WindowMovedEvent.html", null ],
        [ "WindowResizeEvent", "structGrindstone_1_1Events_1_1WindowResizeEvent.html", null ],
        [ "WindowStartFocusEvent", "structGrindstone_1_1Events_1_1WindowStartFocusEvent.html", null ],
        [ "WindowTryQuitEvent", "structGrindstone_1_1Events_1_1WindowTryQuitEvent.html", null ]
      ] ],
      [ "Formats", null, [
        [ "Animation", null, [
          [ "V1", null, [
            [ "Channel", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1Channel.html", null ],
            [ "ChannelData", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1ChannelData.html", null ],
            [ "Header", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1Header.html", null ],
            [ "PositionKeyframe", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1PositionKeyframe.html", null ],
            [ "RotationKeyframe", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1RotationKeyframe.html", null ],
            [ "ScaleKeyframe", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1ScaleKeyframe.html", null ]
          ] ]
        ] ],
        [ "DDS", null, [
          [ "DDS_PIXELFORMAT", "structGrindstone_1_1Formats_1_1DDS_1_1DDS__PIXELFORMAT.html", null ],
          [ "DDSHeader", "structGrindstone_1_1Formats_1_1DDS_1_1DDSHeader.html", null ],
          [ "DDSHeaderExtended", "structGrindstone_1_1Formats_1_1DDS_1_1DDSHeaderExtended.html", null ]
        ] ],
        [ "Model", null, [
          [ "V1", null, [
            [ "BoundingData", "structGrindstone_1_1Formats_1_1Model_1_1V1_1_1BoundingData.html", null ],
            [ "Header", "structGrindstone_1_1Formats_1_1Model_1_1V1_1_1Header.html", null ]
          ] ]
        ] ],
        [ "Pipelines", null, [
          [ "V1", null, [
            [ "BufferReflection", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1BufferReflection.html", null ],
            [ "BufferReflectionMember", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1BufferReflectionMember.html", null ],
            [ "ComputePipelineConfigurationHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ComputePipelineConfigurationHeader.html", null ],
            [ "ComputePipelineSetHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ComputePipelineSetHeader.html", null ],
            [ "GraphicsPipelineConfigurationHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1GraphicsPipelineConfigurationHeader.html", null ],
            [ "GraphicsPipelineSetHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1GraphicsPipelineSetHeader.html", null ],
            [ "MaterialParameter", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1MaterialParameter.html", null ],
            [ "MaterialResource", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1MaterialResource.html", null ],
            [ "PassDescriptorBinding", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorBinding.html", null ],
            [ "PassDescriptorSet", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorSet.html", null ],
            [ "PassPipelineAttachmentHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineAttachmentHeader.html", null ],
            [ "PassPipelineHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineHeader.html", null ],
            [ "PassPipelineShaderStageHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineShaderStageHeader.html", null ],
            [ "PipelineSetFileHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PipelineSetFileHeader.html", null ],
            [ "ShaderReflectDescriptorBinding", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorBinding.html", null ],
            [ "ShaderReflectDescriptorSet", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorSet.html", null ],
            [ "ShaderReflectInputVariables", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectInputVariables.html", null ]
          ] ]
        ] ]
      ] ],
      [ "GraphicsAPI", null, [
        [ "OpenGL", null, [
          [ "Buffer", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Buffer.html", null ],
          [ "ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1ComputePipeline.html", null ],
          [ "Core", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Core.html", null ],
          [ "DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1DescriptorSet.html", null ],
          [ "DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1DescriptorSetLayout.html", null ],
          [ "Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Framebuffer.html", null ],
          [ "GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1GraphicsPipeline.html", null ],
          [ "Image", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Image.html", null ],
          [ "Sampler", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Sampler.html", null ],
          [ "VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1VertexArrayObject.html", null ],
          [ "WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1WindowGraphicsBinding.html", null ]
        ] ],
        [ "Vulkan", null, [
          [ "Buffer", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Buffer.html", null ],
          [ "CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1CommandBuffer.html", null ],
          [ "ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1ComputePipeline.html", null ],
          [ "Core", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Core.html", null ],
          [ "DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1DescriptorSet.html", null ],
          [ "DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1DescriptorSetLayout.html", null ],
          [ "Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Framebuffer.html", null ],
          [ "GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1GraphicsPipeline.html", null ],
          [ "Image", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Image.html", null ],
          [ "ImageSet", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1ImageSet.html", null ],
          [ "ImageSetNative", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1ImageSetNative.html", null ],
          [ "QueueFamilyIndices", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1QueueFamilyIndices.html", null ],
          [ "RenderPass", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1RenderPass.html", null ],
          [ "Sampler", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Sampler.html", null ],
          [ "SwapChainSupportDetails", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1SwapChainSupportDetails.html", null ],
          [ "VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1VertexArrayObject.html", null ],
          [ "WindowBindingDataNative", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1WindowBindingDataNative.html", null ],
          [ "WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1WindowGraphicsBinding.html", null ]
        ] ],
        [ "BlendData", "structGrindstone_1_1GraphicsAPI_1_1BlendData.html", null ],
        [ "Buffer", "classGrindstone_1_1GraphicsAPI_1_1Buffer.html", "classGrindstone_1_1GraphicsAPI_1_1Buffer" ],
        [ "ClearColor", "unionGrindstone_1_1GraphicsAPI_1_1ClearColor.html", null ],
        [ "ClearDepthStencil", "structGrindstone_1_1GraphicsAPI_1_1ClearDepthStencil.html", null ],
        [ "CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1CommandBuffer.html", "classGrindstone_1_1GraphicsAPI_1_1CommandBuffer" ],
        [ "ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1ComputePipeline.html", "classGrindstone_1_1GraphicsAPI_1_1ComputePipeline" ],
        [ "Core", "classGrindstone_1_1GraphicsAPI_1_1Core.html", "classGrindstone_1_1GraphicsAPI_1_1Core" ],
        [ "DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSet.html", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSet" ],
        [ "DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout.html", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout" ],
        [ "DirectX12CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12CommandBuffer.html", null ],
        [ "DirectX12DepthStencilTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX12DepthStencilTarget.html", null ],
        [ "DirectX12Descriptor", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Descriptor.html", null ],
        [ "DirectX12DescriptorLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX12DescriptorLayout.html", null ],
        [ "DirectX12Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Framebuffer.html", null ],
        [ "DirectX12GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1DirectX12GraphicsPipeline.html", null ],
        [ "DirectX12GraphicsWrapper", "classGrindstone_1_1GraphicsAPI_1_1DirectX12GraphicsWrapper.html", null ],
        [ "DirectX12IndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12IndexBuffer.html", null ],
        [ "DirectX12RenderPass", "classGrindstone_1_1GraphicsAPI_1_1DirectX12RenderPass.html", null ],
        [ "DirectX12RenderTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX12RenderTarget.html", null ],
        [ "DirectX12Texture", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Texture.html", null ],
        [ "DirectX12TextureBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX12TextureBinding.html", null ],
        [ "DirectX12TextureBindingLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX12TextureBindingLayout.html", null ],
        [ "DirectX12UniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12UniformBuffer.html", null ],
        [ "DirectX12UniformBufferBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX12UniformBufferBinding.html", null ],
        [ "DirectX12VertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12VertexBuffer.html", null ],
        [ "Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1Framebuffer.html", "classGrindstone_1_1GraphicsAPI_1_1Framebuffer" ],
        [ "GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline.html", "classGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline" ],
        [ "Image", "classGrindstone_1_1GraphicsAPI_1_1Image.html", "classGrindstone_1_1GraphicsAPI_1_1Image" ],
        [ "ImageBarrier", "structGrindstone_1_1GraphicsAPI_1_1ImageBarrier.html", null ],
        [ "OpenGLFormats", "structGrindstone_1_1GraphicsAPI_1_1OpenGLFormats.html", null ],
        [ "RenderPass", "classGrindstone_1_1GraphicsAPI_1_1RenderPass.html", "classGrindstone_1_1GraphicsAPI_1_1RenderPass" ],
        [ "Sampler", "classGrindstone_1_1GraphicsAPI_1_1Sampler.html", "classGrindstone_1_1GraphicsAPI_1_1Sampler" ],
        [ "SamplerOptions", "structGrindstone_1_1GraphicsAPI_1_1SamplerOptions.html", null ],
        [ "VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1VertexArrayObject.html", "classGrindstone_1_1GraphicsAPI_1_1VertexArrayObject" ],
        [ "VertexAttributeDescription", "structGrindstone_1_1GraphicsAPI_1_1VertexAttributeDescription.html", null ],
        [ "VertexBindingDescription", "structGrindstone_1_1GraphicsAPI_1_1VertexBindingDescription.html", null ],
        [ "VertexInputLayout", "structGrindstone_1_1GraphicsAPI_1_1VertexInputLayout.html", null ],
        [ "VertexInputLayoutBuilder", "structGrindstone_1_1GraphicsAPI_1_1VertexInputLayoutBuilder.html", "structGrindstone_1_1GraphicsAPI_1_1VertexInputLayoutBuilder" ],
        [ "WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1WindowGraphicsBinding.html", null ]
      ] ],
      [ "Importers", null, [
        [ "ImporterManager", "classGrindstone_1_1Importers_1_1ImporterManager.html", null ]
      ] ],
      [ "Input", null, [
        [ "Interface", "classGrindstone_1_1Input_1_1Interface.html", null ],
        [ "Manager", "classGrindstone_1_1Input_1_1Manager.html", null ]
      ] ],
      [ "Logger", null, [
        [ "LoggerState", "structGrindstone_1_1Logger_1_1LoggerState.html", null ]
      ] ],
      [ "Math", null, [
        [ "EulerAngles", "structGrindstone_1_1Math_1_1EulerAngles.html", null ],
        [ "Float2", "structGrindstone_1_1Math_1_1Float2.html", null ],
        [ "Float3", "structGrindstone_1_1Math_1_1Float3.html", null ],
        [ "Float4", "structGrindstone_1_1Math_1_1Float4.html", null ],
        [ "Quaternion", "classGrindstone_1_1Math_1_1Quaternion.html", null ]
      ] ],
      [ "Memory", null, [
        [ "AllocatorCore", null, [
          [ "AllocatorState", "structGrindstone_1_1Memory_1_1AllocatorCore_1_1AllocatorState.html", null ]
        ] ],
        [ "Allocators", null, [
          [ "BasePoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1BasePoolAllocator.html", "classGrindstone_1_1Memory_1_1Allocators_1_1BasePoolAllocator" ],
          [ "DynamicAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator.html", "classGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator" ],
          [ "GenericPoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1GenericPoolAllocator.html", null ],
          [ "LinearAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1LinearAllocator.html", null ],
          [ "PoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1PoolAllocator.html", null ],
          [ "StackAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1StackAllocator.html", null ]
        ] ]
      ] ],
      [ "Physics", null, [
        [ "BoxColliderComponent", "structGrindstone_1_1Physics_1_1BoxColliderComponent.html", null ],
        [ "CapsuleColliderComponent", "structGrindstone_1_1Physics_1_1CapsuleColliderComponent.html", null ],
        [ "ColliderComponent", "structGrindstone_1_1Physics_1_1ColliderComponent.html", null ],
        [ "PlaneColliderComponent", "structGrindstone_1_1Physics_1_1PlaneColliderComponent.html", null ],
        [ "RigidBodyComponent", "structGrindstone_1_1Physics_1_1RigidBodyComponent.html", null ],
        [ "SphereColliderComponent", "structGrindstone_1_1Physics_1_1SphereColliderComponent.html", null ],
        [ "WorldContext", "classGrindstone_1_1Physics_1_1WorldContext.html", null ]
      ] ],
      [ "PipelineAssetMetaData", null, [
        [ "Buffer", "structGrindstone_1_1PipelineAssetMetaData_1_1Buffer.html", null ],
        [ "Parameter", "structGrindstone_1_1PipelineAssetMetaData_1_1Parameter.html", null ],
        [ "ParameterValue", "unionGrindstone_1_1PipelineAssetMetaData_1_1ParameterValue.html", null ],
        [ "ResourceSlot", "structGrindstone_1_1PipelineAssetMetaData_1_1ResourceSlot.html", null ]
      ] ],
      [ "Plugins", null, [
        [ "BaseEditorInterface", "classGrindstone_1_1Plugins_1_1BaseEditorInterface.html", null ],
        [ "EditorPluginInterface", "classGrindstone_1_1Plugins_1_1EditorPluginInterface.html", null ],
        [ "Interface", "classGrindstone_1_1Plugins_1_1Interface.html", null ],
        [ "Manager", "classGrindstone_1_1Plugins_1_1Manager.html", null ]
      ] ],
      [ "Profiler", null, [
        [ "InstrumentationSession", "structGrindstone_1_1Profiler_1_1InstrumentationSession.html", null ],
        [ "Manager", "classGrindstone_1_1Profiler_1_1Manager.html", null ],
        [ "Result", "structGrindstone_1_1Profiler_1_1Result.html", null ],
        [ "Timer", "classGrindstone_1_1Profiler_1_1Timer.html", null ]
      ] ],
      [ "Reflection", null, [
        [ "DefaultResolver", "structGrindstone_1_1Reflection_1_1DefaultResolver.html", "structGrindstone_1_1Reflection_1_1DefaultResolver" ],
        [ "TypeDescriptor", "structGrindstone_1_1Reflection_1_1TypeDescriptor.html", null ],
        [ "TypeDescriptor_AssetReference", "structGrindstone_1_1Reflection_1_1TypeDescriptor__AssetReference.html", null ],
        [ "TypeDescriptor_Bool", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Bool.html", null ],
        [ "TypeDescriptor_Double", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double.html", null ],
        [ "TypeDescriptor_Double2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double2.html", null ],
        [ "TypeDescriptor_Double3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double3.html", null ],
        [ "TypeDescriptor_Double4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double4.html", null ],
        [ "TypeDescriptor_Entity", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Entity.html", null ],
        [ "TypeDescriptor_Float", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float.html", null ],
        [ "TypeDescriptor_Float2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float2.html", null ],
        [ "TypeDescriptor_Float3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float3.html", null ],
        [ "TypeDescriptor_Float4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float4.html", null ],
        [ "TypeDescriptor_Int", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int.html", null ],
        [ "TypeDescriptor_Int2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int2.html", null ],
        [ "TypeDescriptor_Int3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int3.html", null ],
        [ "TypeDescriptor_Int4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int4.html", null ],
        [ "TypeDescriptor_Quat", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Quat.html", null ],
        [ "TypeDescriptor_StdString", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdString.html", null ],
        [ "TypeDescriptor_StdVector", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdVector.html", null ],
        [ "TypeDescriptor_Struct", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct.html", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct" ],
        [ "TypeDescriptor_Uint", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint.html", null ],
        [ "TypeDescriptor_Uint2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint2.html", null ],
        [ "TypeDescriptor_Uint3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint3.html", null ],
        [ "TypeDescriptor_Uint4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint4.html", null ],
        [ "TypeResolver", "structGrindstone_1_1Reflection_1_1TypeResolver.html", null ],
        [ "TypeResolver< Grindstone::AssetReference< T > >", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01Grindstone_1_1AssetReference_3_01T_01_4_01_4.html", null ],
        [ "TypeResolver< std::vector< T > >", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01std_1_1vector_3_01T_01_4_01_4.html", null ]
      ] ],
      [ "Rendering", null, [
        [ "GeometryRenderStats", "structGrindstone_1_1Rendering_1_1GeometryRenderStats.html", null ],
        [ "RenderPathBase", "classGrindstone_1_1Rendering_1_1RenderPathBase.html", null ],
        [ "RenderViewData", "structGrindstone_1_1Rendering_1_1RenderViewData.html", null ]
      ] ],
      [ "SceneManagement", null, [
        [ "Scene", "classGrindstone_1_1SceneManagement_1_1Scene.html", null ],
        [ "SceneLoaderJson", "classGrindstone_1_1SceneManagement_1_1SceneLoaderJson.html", null ],
        [ "SceneManager", "classGrindstone_1_1SceneManagement_1_1SceneManager.html", null ],
        [ "SceneWriterJson", "classGrindstone_1_1SceneManagement_1_1SceneWriterJson.html", null ]
      ] ],
      [ "Scripting", null, [
        [ "CSharp", null, [
          [ "CSharpManager", "classGrindstone_1_1Scripting_1_1CSharp_1_1CSharpManager.html", "classGrindstone_1_1Scripting_1_1CSharp_1_1CSharpManager" ],
          [ "ScriptClass", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass.html", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass" ],
          [ "ScriptComponent", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptComponent.html", null ],
          [ "ScriptField", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptField.html", null ]
        ] ]
      ] ],
      [ "Asset", "structGrindstone_1_1Asset.html", null ],
      [ "AssetImporter", "classGrindstone_1_1AssetImporter.html", null ],
      [ "AssetReference", "structGrindstone_1_1AssetReference.html", null ],
      [ "AssetRendererManager", "classGrindstone_1_1AssetRendererManager.html", null ],
      [ "AudioListenerComponent", "structGrindstone_1_1AudioListenerComponent.html", null ],
      [ "AudioSourceComponent", "structGrindstone_1_1AudioSourceComponent.html", null ],
      [ "BaseAssetRenderer", "classGrindstone_1_1BaseAssetRenderer.html", null ],
      [ "BaseRenderer", "classGrindstone_1_1BaseRenderer.html", "classGrindstone_1_1BaseRenderer" ],
      [ "BaseRendererFactory", "classGrindstone_1_1BaseRendererFactory.html", null ],
      [ "Buffer", "classGrindstone_1_1Buffer.html", null ],
      [ "Camera", "classGrindstone_1_1Camera.html", null ],
      [ "CameraComponent", "classGrindstone_1_1CameraComponent.html", null ],
      [ "ComponentRegistrar", "classGrindstone_1_1ComponentRegistrar.html", null ],
      [ "ComputePipelineAsset", "structGrindstone_1_1ComputePipelineAsset.html", null ],
      [ "ComputePipelineImporter", "classGrindstone_1_1ComputePipelineImporter.html", null ],
      [ "ConsoleMessage", "structGrindstone_1_1ConsoleMessage.html", null ],
      [ "ConstHashedString", "classGrindstone_1_1ConstHashedString.html", null ],
      [ "CsharpGlobals", "structGrindstone_1_1CsharpGlobals.html", null ],
      [ "DeferredRenderer", "classGrindstone_1_1DeferredRenderer.html", null ],
      [ "DeferredRendererFactory", "classGrindstone_1_1DeferredRendererFactory.html", null ],
      [ "DirectionalLightComponent", "structGrindstone_1_1DirectionalLightComponent.html", "structGrindstone_1_1DirectionalLightComponent" ],
      [ "Display", "structGrindstone_1_1Display.html", null ],
      [ "DisplayManager", "classGrindstone_1_1DisplayManager.html", null ],
      [ "EngineCore", "classGrindstone_1_1EngineCore.html", "classGrindstone_1_1EngineCore" ],
      [ "Entity", "structGrindstone_1_1Entity.html", null ],
      [ "EnvironmentMapComponent", "structGrindstone_1_1EnvironmentMapComponent.html", null ],
      [ "GameplayTag", "classGrindstone_1_1GameplayTag.html", null ],
      [ "GenericAssetReference", "structGrindstone_1_1GenericAssetReference.html", null ],
      [ "GlfwWindow", "classGrindstone_1_1GlfwWindow.html", null ],
      [ "GraphicsPipelineAsset", "structGrindstone_1_1GraphicsPipelineAsset.html", "structGrindstone_1_1GraphicsPipelineAsset" ],
      [ "GraphicsPipelineImporter", "classGrindstone_1_1GraphicsPipelineImporter.html", null ],
      [ "HashedString", "classGrindstone_1_1HashedString.html", null ],
      [ "HotReloadContext", "classGrindstone_1_1HotReloadContext.html", null ],
      [ "Logger", "classGrindstone_1_1Logger.html", null ],
      [ "MaterialAsset", "structGrindstone_1_1MaterialAsset.html", null ],
      [ "MaterialImporter", "classGrindstone_1_1MaterialImporter.html", null ],
      [ "Mesh3dAsset", "structGrindstone_1_1Mesh3dAsset.html", "structGrindstone_1_1Mesh3dAsset" ],
      [ "Mesh3dImporter", "classGrindstone_1_1Mesh3dImporter.html", null ],
      [ "Mesh3dRenderer", "classGrindstone_1_1Mesh3dRenderer.html", null ],
      [ "MeshComponent", "structGrindstone_1_1MeshComponent.html", null ],
      [ "MeshRendererComponent", "structGrindstone_1_1MeshRendererComponent.html", null ],
      [ "ParentComponent", "structGrindstone_1_1ParentComponent.html", null ],
      [ "PointLightComponent", "classGrindstone_1_1PointLightComponent.html", "classGrindstone_1_1PointLightComponent" ],
      [ "Rect", "structGrindstone_1_1Rect.html", null ],
      [ "RenderPassRegistry", "classGrindstone_1_1RenderPassRegistry.html", null ],
      [ "ResizableBuffer", "classGrindstone_1_1ResizableBuffer.html", null ],
      [ "ResourcePipeline", "classGrindstone_1_1ResourcePipeline.html", null ],
      [ "Scene", "structGrindstone_1_1Scene.html", null ],
      [ "SharedPtr", "classGrindstone_1_1SharedPtr.html", "classGrindstone_1_1SharedPtr" ],
      [ "SmartComponent", "classGrindstone_1_1SmartComponent.html", null ],
      [ "SpecificAssetImporter", "classGrindstone_1_1SpecificAssetImporter.html", null ],
      [ "SpotLightComponent", "structGrindstone_1_1SpotLightComponent.html", "structGrindstone_1_1SpotLightComponent" ],
      [ "SystemRegistrar", "classGrindstone_1_1SystemRegistrar.html", null ],
      [ "TagComponent", "classGrindstone_1_1TagComponent.html", null ],
      [ "TextureAsset", "structGrindstone_1_1TextureAsset.html", null ],
      [ "TextureImporter", "classGrindstone_1_1TextureImporter.html", null ],
      [ "TransformComponent", "classGrindstone_1_1TransformComponent.html", null ],
      [ "UniquePtr", "classGrindstone_1_1UniquePtr.html", null ],
      [ "Uuid", "classGrindstone_1_1Uuid.html", null ],
      [ "Win32Window", "classGrindstone_1_1Win32Window.html", null ],
      [ "Window", "classGrindstone_1_1Window.html", "classGrindstone_1_1Window" ],
      [ "WindowManager", "classGrindstone_1_1WindowManager.html", null ],
      [ "WorldContext", "classGrindstone_1_1WorldContext.html", null ],
      [ "WorldContextManager", "classGrindstone_1_1WorldContextManager.html", null ],
      [ "WorldContextSet", "classGrindstone_1_1WorldContextSet.html", null ],
      [ "X11Window", "classGrindstone_1_1X11Window.html", null ]
    ] ],
    [ "std", null, [
      [ "std", null, [
        [ "hash< Grindstone::GraphicsAPI::GraphicsPipeline::AttachmentData >", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1AttachmentData_01_4.html", null ],
        [ "hash< Grindstone::GraphicsAPI::GraphicsPipeline::PipelineData >", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1PipelineData_01_4.html", null ],
        [ "hash< Grindstone::GraphicsAPI::GraphicsPipeline::ShaderStageData >", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1ShaderStageData_01_4.html", null ],
        [ "hash< Grindstone::GraphicsAPI::VertexAttributeDescription >", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1VertexAttributeDescription_01_4.html", null ],
        [ "hash< Grindstone::GraphicsAPI::VertexBindingDescription >", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1VertexBindingDescription_01_4.html", null ],
        [ "hash< Grindstone::GraphicsAPI::VertexInputLayout >", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1VertexInputLayout_01_4.html", null ]
      ] ],
      [ "hash< Grindstone::HashedString >", "structstd_1_1hash_3_01Grindstone_1_1HashedString_01_4.html", null ],
      [ "hash< Grindstone::Uuid >", "structstd_1_1hash_3_01Grindstone_1_1Uuid_01_4.html", null ]
    ] ],
    [ "AABB", "structAABB.html", null ],
    [ "BloomUboStruct", "structBloomUboStruct.html", null ],
    [ "ChildEntity", "structChildEntity.html", null ],
    [ "CompilationArtifactsCompute", "structCompilationArtifactsCompute.html", null ],
    [ "CompilationArtifactsGraphics", "structCompilationArtifactsGraphics.html", "structCompilationArtifactsGraphics" ],
    [ "CompilationOptions", "structCompilationOptions.html", null ],
    [ "CullingFrustum", "structCullingFrustum.html", null ],
    [ "DescriptorSetOutput", "structDescriptorSetOutput.html", null ],
    [ "EngineUboStruct", "structEngineUboStruct.html", null ],
    [ "EnumFlagsTraits", "structEnumFlagsTraits.html", null ],
    [ "EnumFlagsTraits< Grindstone::GraphicsAPI::BufferUsage >", "structEnumFlagsTraits_3_01Grindstone_1_1GraphicsAPI_1_1BufferUsage_01_4.html", null ],
    [ "EnumFlagsTraits< Grindstone::GraphicsAPI::ImageUsageFlags >", "structEnumFlagsTraits_3_01Grindstone_1_1GraphicsAPI_1_1ImageUsageFlags_01_4.html", null ],
    [ "EnumTraits", "structEnumTraits.html", null ],
    [ "ExportableQuaternion", "structExportableQuaternion.html", null ],
    [ "ExportableVector", "structExportableVector.html", null ],
    [ "Float2", "structFloat2.html", null ],
    [ "GridUniformBuffer", "structGridUniformBuffer.html", null ],
    [ "InspectorState", "structInspectorState.html", null ],
    [ "MemoryDumpData", "structMemoryDumpData.html", null ],
    [ "MemoryDumpRow", "structMemoryDumpRow.html", null ],
    [ "Mesh3dUbo", "structMesh3dUbo.html", null ],
    [ "ModelImporter", "classModelImporter.html", null ],
    [ "ModelImporterRendererState", "structModelImporterRendererState.html", null ],
    [ "OBB", "structOBB.html", null ],
    [ "OpenGLFormatMapping", "structOpenGLFormatMapping.html", null ],
    [ "ParseContext", "structParseContext.html", null ],
    [ "ParseTree", "structParseTree.html", "structParseTree" ],
    [ "PipelineOutput", "structPipelineOutput.html", null ],
    [ "PipelineSetConditioner", "classPipelineSetConditioner.html", null ],
    [ "ReflectedBlock", "structReflectedBlock.html", null ],
    [ "ReflectedBlockVariable", "structReflectedBlockVariable.html", null ],
    [ "ReflectedBufferBinding", "structReflectedBufferBinding.html", null ],
    [ "RenderSortData", "structRenderSortData.html", null ],
    [ "RenderTask", "structRenderTask.html", null ],
    [ "RenderTaskGroup", "structRenderTaskGroup.html", null ],
    [ "ResolveContext", "structResolveContext.html", null ],
    [ "ResolvedStateTree", "structResolvedStateTree.html", "structResolvedStateTree" ],
    [ "ScanContext", "structScanContext.html", null ],
    [ "ShaderReflectDescriptorBinding", "structShaderReflectDescriptorBinding.html", null ],
    [ "ShaderReflectDescriptorSet", "structShaderReflectDescriptorSet.html", null ],
    [ "SourceSubmesh", "structSourceSubmesh.html", null ],
    [ "SsaoUboStruct", "structSsaoUboStruct.html", null ],
    [ "StageCompilationArtifacts", "structStageCompilationArtifacts.html", null ],
    [ "TextureImporter", "classTextureImporter.html", null ],
    [ "TokenData", "classTokenData.html", "classTokenData" ],
    [ "Writer", "structWriter.html", null ]
];