var dir_476cf4cbcbf57055a89a5374b1d77a45 =
[
    [ "Components", "dir_42ce4c11226d09992b39c7d4a5a03fa1.html", "dir_42ce4c11226d09992b39c7d4a5a03fa1" ],
    [ "ProjectSettings", "dir_c9296eb99f4f52ef8b82f14361252d7b.html", "dir_c9296eb99f4f52ef8b82f14361252d7b" ],
    [ "Settings", "dir_11ee18b958673228d295f95b5d11e80b.html", "dir_11ee18b958673228d295f95b5d11e80b" ],
    [ "UserSettings", "dir_2d6e25a884e98f1112b523970f115e63.html", "dir_2d6e25a884e98f1112b523970f115e63" ],
    [ "AssetBrowserPanel.hpp", "AssetBrowserPanel_8hpp_source.html", null ],
    [ "AssetPicker.hpp", "AssetPicker_8hpp_source.html", null ],
    [ "BrowseFile.hpp", "BrowseFile_8hpp_source.html", null ],
    [ "BuildPopup.hpp", "BuildPopup_8hpp_source.html", null ],
    [ "ComponentInspector.hpp", "ComponentInspector_8hpp_source.html", null ],
    [ "ConsolePanel.hpp", "ConsolePanel_8hpp_source.html", null ],
    [ "ControlBar.hpp", "ControlBar_8hpp_source.html", null ],
    [ "CvarBrowser.hpp", "CvarBrowser_8hpp_source.html", null ],
    [ "imgui_markdown.h", "imgui__markdown_8h_source.html", null ],
    [ "imgui_widget_flamegraph.h", "imgui__widget__flamegraph_8h_source.html", null ],
    [ "ImguiEditor.hpp", "ImguiEditor_8hpp_source.html", null ],
    [ "ImguiInput.hpp", "ImguiInput_8hpp_source.html", null ],
    [ "ImguiInterface.hpp", "ImguiInterface_8hpp_source.html", null ],
    [ "ImguiRenderer.hpp", "ImguiRenderer_8hpp_source.html", null ],
    [ "ImguiRendererOpenGL.hpp", "ImguiRendererOpenGL_8hpp_source.html", null ],
    [ "ImguiRendererVulkan.hpp", "ImguiRendererVulkan_8hpp_source.html", null ],
    [ "InspectorPanel.hpp", "InspectorPanel_8hpp_source.html", null ],
    [ "MaterialInspector.hpp", "MaterialInspector_8hpp_source.html", null ],
    [ "Menubar.hpp", "Menubar_8hpp_source.html", null ],
    [ "NewComponentInput.hpp", "NewComponentInput_8hpp_source.html", null ],
    [ "PluginsWindow.hpp", "PluginsWindow_8hpp_source.html", null ],
    [ "SceneHeirarchyPanel.hpp", "SceneHeirarchyPanel_8hpp_source.html", null ],
    [ "StatsPanel.hpp", "StatsPanel_8hpp_source.html", null ],
    [ "StatusBar.hpp", "StatusBar_8hpp_source.html", null ],
    [ "SuggestedInput.hpp", "SuggestedInput_8hpp_source.html", null ],
    [ "SystemPanel.hpp", "SystemPanel_8hpp_source.html", null ],
    [ "TaskPanel.hpp", "TaskPanel_8hpp_source.html", null ],
    [ "TracingPanel.hpp", "TracingPanel_8hpp_source.html", null ],
    [ "ViewportPanel.hpp", "ViewportPanel_8hpp_source.html", null ]
];