var hierarchy =
[
    [ "Grindstone::Memory::Allocators::DynamicAllocator::AllocationHeader", "structGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator_1_1AllocationHeader.html", null ],
    [ "Grindstone::Memory::AllocatorCore::AllocatorState", "structGrindstone_1_1Memory_1_1AllocatorCore_1_1AllocatorState.html", null ],
    [ "Grindstone::Assets::ArchiveContentFile", "structGrindstone_1_1Assets_1_1ArchiveContentFile.html", null ],
    [ "Grindstone::Assets::ArchiveDirectory", "structGrindstone_1_1Assets_1_1ArchiveDirectory.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryDeserializer", "classGrindstone_1_1Assets_1_1ArchiveDirectoryDeserializer.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile.html", null ],
    [ "Grindstone::Assets::ArchiveDirectory::ArchiveInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectory_1_1ArchiveInfo.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::ArchiveInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1ArchiveInfo.html", null ],
    [ "Grindstone::Scripting::CSharp::CSharpManager::AssemblyData", "structGrindstone_1_1Scripting_1_1CSharp_1_1CSharpManager_1_1AssemblyData.html", null ],
    [ "Grindstone::Asset", "structGrindstone_1_1Asset.html", [
      [ "Grindstone::Audio::AudioClipAsset", "structGrindstone_1_1Audio_1_1AudioClipAsset.html", null ],
      [ "Grindstone::MaterialAsset", "structGrindstone_1_1MaterialAsset.html", null ],
      [ "Grindstone::Mesh3dAsset", "structGrindstone_1_1Mesh3dAsset.html", null ],
      [ "Grindstone::ShaderAsset", "structGrindstone_1_1ShaderAsset.html", null ],
      [ "Grindstone::TextureAsset", "structGrindstone_1_1TextureAsset.html", null ]
    ] ],
    [ "Grindstone::Editor::ImguiEditor::AssetBrowserPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetBrowserPanel.html", null ],
    [ "Grindstone::AssetImporter", "classGrindstone_1_1AssetImporter.html", [
      [ "Grindstone::SpecificAssetImporter< AudioClipAsset, AssetType::AudioClip >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::Audio::AudioClipImporter", "classGrindstone_1_1Audio_1_1AudioClipImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< MaterialAsset, AssetType::Material >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::MaterialImporter", "classGrindstone_1_1MaterialImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< Mesh3dAsset, AssetType::Mesh3d >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::Mesh3dImporter", "classGrindstone_1_1Mesh3dImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< ShaderAsset, AssetType::Shader >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::ShaderImporter", "classGrindstone_1_1ShaderImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< TextureAsset, AssetType::Texture >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::TextureImporter", "classGrindstone_1_1TextureImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< AssetStructType, internalAssetType >", "classGrindstone_1_1SpecificAssetImporter.html", null ]
    ] ],
    [ "Grindstone::Assets::ArchiveDirectory::AssetInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectory_1_1AssetInfo.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::AssetInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1AssetInfo.html", null ],
    [ "Grindstone::Assets::AssetLoader", "classGrindstone_1_1Assets_1_1AssetLoader.html", [
      [ "Grindstone::Assets::ArchiveAssetLoader", "classGrindstone_1_1Assets_1_1ArchiveAssetLoader.html", null ],
      [ "Grindstone::Assets::FileAssetLoader", "classGrindstone_1_1Assets_1_1FileAssetLoader.html", null ]
    ] ],
    [ "Grindstone::Assets::AssetLoadResult", "structGrindstone_1_1Assets_1_1AssetLoadResult.html", null ],
    [ "Grindstone::Assets::AssetManager", "classGrindstone_1_1Assets_1_1AssetManager.html", null ],
    [ "Grindstone::Assets::AssetPackSerializer::AssetPackageSerializer", "classGrindstone_1_1Assets_1_1AssetPackSerializer_1_1AssetPackageSerializer.html", null ],
    [ "Grindstone::Editor::ImguiEditor::AssetPicker", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetPicker.html", null ],
    [ "Grindstone::Assets::AssetRegistry", "classGrindstone_1_1Assets_1_1AssetRegistry.html", null ],
    [ "Grindstone::Editor::AssetRegistry", "classGrindstone_1_1Editor_1_1AssetRegistry.html", null ],
    [ "Grindstone::AssetRendererManager", "classGrindstone_1_1AssetRendererManager.html", null ],
    [ "Grindstone::Editor::AssetTemplateRegistry::AssetTemplate", "structGrindstone_1_1Editor_1_1AssetTemplateRegistry_1_1AssetTemplate.html", null ],
    [ "Grindstone::Editor::AssetTemplateRegistry", "classGrindstone_1_1Editor_1_1AssetTemplateRegistry.html", null ],
    [ "Grindstone::Assets::ArchiveDirectory::AssetTypeIndex", "structGrindstone_1_1Assets_1_1ArchiveDirectory_1_1AssetTypeIndex.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::AssetTypeSectionInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1AssetTypeSectionInfo.html", null ],
    [ "Grindstone::GraphicsAPI::RenderPass::AttachmentInfo", "structGrindstone_1_1GraphicsAPI_1_1RenderPass_1_1AttachmentInfo.html", null ],
    [ "Grindstone::AudioListenerComponent", "structGrindstone_1_1AudioListenerComponent.html", null ],
    [ "Grindstone::AudioSourceComponent", "structGrindstone_1_1AudioSourceComponent.html", null ],
    [ "Grindstone::BaseAssetRenderer", "classGrindstone_1_1BaseAssetRenderer.html", [
      [ "Grindstone::Mesh3dRenderer", "classGrindstone_1_1Mesh3dRenderer.html", null ]
    ] ],
    [ "Grindstone::Editor::BaseCommand", "classGrindstone_1_1Editor_1_1BaseCommand.html", [
      [ "Grindstone::Editor::AddComponentCommand", "classGrindstone_1_1Editor_1_1AddComponentCommand.html", null ],
      [ "Grindstone::Editor::AddEntityCommand", "classGrindstone_1_1Editor_1_1AddEntityCommand.html", null ],
      [ "Grindstone::Editor::DeleteComponentCommand", "classGrindstone_1_1Editor_1_1DeleteComponentCommand.html", null ],
      [ "Grindstone::Editor::DeleteEntityCommand", "classGrindstone_1_1Editor_1_1DeleteEntityCommand.html", null ],
      [ "Grindstone::Editor::JointCommand", "classGrindstone_1_1Editor_1_1JointCommand.html", null ],
      [ "Grindstone::Editor::SetDataCommand", "classGrindstone_1_1Editor_1_1SetDataCommand.html", null ]
    ] ],
    [ "Grindstone::Plugins::BaseEditorInterface", "classGrindstone_1_1Plugins_1_1BaseEditorInterface.html", [
      [ "Grindstone::Plugins::EditorPluginInterface", "classGrindstone_1_1Plugins_1_1EditorPluginInterface.html", null ]
    ] ],
    [ "Grindstone::Events::BaseEvent", "structGrindstone_1_1Events_1_1BaseEvent.html", [
      [ "Grindstone::Events::CharacterTypedEvent", "structGrindstone_1_1Events_1_1CharacterTypedEvent.html", null ],
      [ "Grindstone::Events::KeyPressEvent", "structGrindstone_1_1Events_1_1KeyPressEvent.html", null ],
      [ "Grindstone::Events::MouseMovedEvent", "structGrindstone_1_1Events_1_1MouseMovedEvent.html", null ],
      [ "Grindstone::Events::MousePressEvent", "structGrindstone_1_1Events_1_1MousePressEvent.html", null ],
      [ "Grindstone::Events::MouseScrolledEvent", "structGrindstone_1_1Events_1_1MouseScrolledEvent.html", null ],
      [ "Grindstone::Events::PrintMessageEvent", "structGrindstone_1_1Events_1_1PrintMessageEvent.html", null ],
      [ "Grindstone::Events::WindowForceQuitEvent", "structGrindstone_1_1Events_1_1WindowForceQuitEvent.html", null ],
      [ "Grindstone::Events::WindowKillFocusEvent", "structGrindstone_1_1Events_1_1WindowKillFocusEvent.html", null ],
      [ "Grindstone::Events::WindowMovedEvent", "structGrindstone_1_1Events_1_1WindowMovedEvent.html", null ],
      [ "Grindstone::Events::WindowResizeEvent", "structGrindstone_1_1Events_1_1WindowResizeEvent.html", null ],
      [ "Grindstone::Events::WindowStartFocusEvent", "structGrindstone_1_1Events_1_1WindowStartFocusEvent.html", null ],
      [ "Grindstone::Events::WindowTryQuitEvent", "structGrindstone_1_1Events_1_1WindowTryQuitEvent.html", null ]
    ] ],
    [ "Grindstone::Editor::ImguiEditor::Settings::BasePage", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1BasePage.html", [
      [ "Grindstone::Editor::ImguiEditor::Settings::Build", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::CodeTools", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1CodeTools.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::PlatformWindows", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PlatformWindows.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::Platforms", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Platforms.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::Plugins", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Plugins.html", null ]
    ] ],
    [ "Grindstone::Memory::Allocators::BasePoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1BasePoolAllocator.html", [
      [ "Grindstone::Memory::Allocators::GenericPoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1GenericPoolAllocator.html", null ],
      [ "Grindstone::Memory::Allocators::PoolAllocator< T >", "classGrindstone_1_1Memory_1_1Allocators_1_1PoolAllocator.html", null ]
    ] ],
    [ "Grindstone::BaseRenderer", "classGrindstone_1_1BaseRenderer.html", [
      [ "Grindstone::DeferredRenderer", "classGrindstone_1_1DeferredRenderer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::DescriptorSet::Binding", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSet_1_1Binding.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSetLayout::Binding", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_1_1Binding.html", null ],
    [ "Grindstone::GraphicsAPI::BlendData", "structGrindstone_1_1GraphicsAPI_1_1BlendData.html", null ],
    [ "BloomUboStruct", "structBloomUboStruct.html", null ],
    [ "Grindstone::Buffer", "classGrindstone_1_1Buffer.html", [
      [ "Grindstone::ResizableBuffer", "classGrindstone_1_1ResizableBuffer.html", null ]
    ] ],
    [ "Grindstone::BufferView", "classGrindstone_1_1BufferView.html", null ],
    [ "Grindstone::Editor::ImguiEditor::BuildPopup", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1BuildPopup.html", null ],
    [ "Grindstone::Editor::BuildProcessStats", "structGrindstone_1_1Editor_1_1BuildProcessStats.html", null ],
    [ "Grindstone::Camera", "classGrindstone_1_1Camera.html", null ],
    [ "Grindstone::CameraComponent", "classGrindstone_1_1CameraComponent.html", null ],
    [ "Grindstone::Reflection::TypeDescriptor_Struct::Category", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct_1_1Category.html", null ],
    [ "Grindstone::Formats::Animation::V1::Channel", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1Channel.html", null ],
    [ "Grindstone::Formats::Animation::V1::ChannelData", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1ChannelData.html", null ],
    [ "ChildEntity", "structChildEntity.html", null ],
    [ "Grindstone::GraphicsAPI::ClearColor", "unionGrindstone_1_1GraphicsAPI_1_1ClearColor.html", null ],
    [ "Grindstone::GraphicsAPI::ClearDepthStencil", "structGrindstone_1_1GraphicsAPI_1_1ClearDepthStencil.html", null ],
    [ "Grindstone::Physics::ColliderComponent", "structGrindstone_1_1Physics_1_1ColliderComponent.html", [
      [ "Grindstone::Physics::BoxColliderComponent", "structGrindstone_1_1Physics_1_1BoxColliderComponent.html", null ],
      [ "Grindstone::Physics::CapsuleColliderComponent", "structGrindstone_1_1Physics_1_1CapsuleColliderComponent.html", null ],
      [ "Grindstone::Physics::PlaneColliderComponent", "structGrindstone_1_1Physics_1_1PlaneColliderComponent.html", null ],
      [ "Grindstone::Physics::SphereColliderComponent", "structGrindstone_1_1Physics_1_1SphereColliderComponent.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1CommandBuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX11CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX11CommandBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12CommandBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanCommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1VulkanCommandBuffer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::CommandBuffer::CommandBufferSecondaryInfo", "structGrindstone_1_1GraphicsAPI_1_1CommandBuffer_1_1CommandBufferSecondaryInfo.html", null ],
    [ "Grindstone::Editor::CommandList", "classGrindstone_1_1Editor_1_1CommandList.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::CompilerProperties", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1CompilerProperties.html", null ],
    [ "Grindstone::ECS::ComponentFunctions", "classGrindstone_1_1ECS_1_1ComponentFunctions.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ComponentInspector", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ComponentInspector.html", null ],
    [ "Grindstone.ComponentRegistrar", "classGrindstone_1_1ComponentRegistrar.html", null ],
    [ "Grindstone::ECS::ComponentRegistrar", "classGrindstone_1_1ECS_1_1ComponentRegistrar.html", null ],
    [ "Grindstone::GraphicsAPI::ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1ComputePipeline.html", [
      [ "Grindstone::GraphicsAPI::GLComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1GLComputePipeline.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1VulkanComputePipeline.html", null ]
    ] ],
    [ "Grindstone::ConsoleMessage", "structGrindstone_1_1ConsoleMessage.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ConsolePanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ConsolePanel.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ControlBar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ControlBar.html", null ],
    [ "Grindstone::Audio::Core", "classGrindstone_1_1Audio_1_1Core.html", null ],
    [ "Grindstone::GraphicsAPI::Core", "classGrindstone_1_1GraphicsAPI_1_1Core.html", [
      [ "Grindstone::GraphicsAPI::GLCore", "classGrindstone_1_1GraphicsAPI_1_1GLCore.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanCore", "classGrindstone_1_1GraphicsAPI_1_1VulkanCore.html", null ]
    ] ],
    [ "Grindstone::Physics::Core", "classGrindstone_1_1Physics_1_1Core.html", null ],
    [ "Grindstone::Audio::Source::CreateInfo", "structGrindstone_1_1Audio_1_1Source_1_1CreateInfo.html", null ],
    [ "Grindstone::EngineCore::CreateInfo", "structGrindstone_1_1EngineCore_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::CommandBuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1CommandBuffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::ComputePipeline::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1ComputePipeline_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Core::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Core_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::DepthTarget::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1DepthTarget_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSet::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSet_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSetLayout::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Framebuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Framebuffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::IndexBuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1IndexBuffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::RenderPass::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1RenderPass_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::RenderTarget::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1RenderTarget_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Texture::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Texture_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::UniformBuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1UniformBuffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::VertexArrayObject::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1VertexArrayObject_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::VertexBuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1VertexBuffer_1_1CreateInfo.html", null ],
    [ "Grindstone.Window::CreateInfo", "structGrindstone_1_1Window_1_1CreateInfo.html", null ],
    [ "Grindstone::Editor::ScriptBuilder::CSharpBuildManager", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpBuildManager.html", null ],
    [ "Grindstone::Scripting::CSharp::CSharpManager", "classGrindstone_1_1Scripting_1_1CSharp_1_1CSharpManager.html", null ],
    [ "Grindstone::Editor::ScriptBuilder::CSharpProjectBuilder", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpProjectBuilder.html", null ],
    [ "Grindstone::Editor::ScriptBuilder::CSharpProjectMetaData", "structGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpProjectMetaData.html", null ],
    [ "Grindstone::GraphicsAPI::Texture::CubemapCreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Texture_1_1CubemapCreateInfo.html", null ],
    [ "Grindstone::Formats::DDS::DDS_PIXELFORMAT", "structGrindstone_1_1Formats_1_1DDS_1_1DDS__PIXELFORMAT.html", null ],
    [ "Grindstone::Formats::DDS::DDSHeader", "structGrindstone_1_1Formats_1_1DDS_1_1DDSHeader.html", null ],
    [ "Grindstone::Formats::DDS::DDSHeaderExtended", "structGrindstone_1_1Formats_1_1DDS_1_1DDSHeaderExtended.html", null ],
    [ "Grindstone::GraphicsAPI::Framebuffer::DefaultFramebufferCreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Framebuffer_1_1DefaultFramebufferCreateInfo.html", null ],
    [ "Grindstone::Reflection::DefaultResolver", "structGrindstone_1_1Reflection_1_1DefaultResolver.html", null ],
    [ "Grindstone::GraphicsAPI::DepthTarget", "classGrindstone_1_1GraphicsAPI_1_1DepthTarget.html", [
      [ "Grindstone::GraphicsAPI::DirectX11DepthTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX11DepthTarget.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12DepthTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX12DepthTarget.html", null ],
      [ "Grindstone::GraphicsAPI::GLDepthTarget", "classGrindstone_1_1GraphicsAPI_1_1GLDepthTarget.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanDepthTarget", "classGrindstone_1_1GraphicsAPI_1_1VulkanDepthTarget.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSet.html", [
      [ "Grindstone::GraphicsAPI::GLDescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1GLDescriptorSet.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanDescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1VulkanDescriptorSet.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout.html", [
      [ "Grindstone::GraphicsAPI::GLDescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1GLDescriptorSetLayout.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanDescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1VulkanDescriptorSetLayout.html", null ]
    ] ],
    [ "Grindstone::DirectionalLightComponent", "structGrindstone_1_1DirectionalLightComponent.html", null ],
    [ "Grindstone::Editor::Directory", "structGrindstone_1_1Editor_1_1Directory.html", null ],
    [ "Grindstone::GraphicsAPI::DirectX11Descriptor", "classGrindstone_1_1GraphicsAPI_1_1DirectX11Descriptor.html", null ],
    [ "Grindstone::GraphicsAPI::DirectX11DescriptorLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX11DescriptorLayout.html", null ],
    [ "Grindstone::GraphicsAPI::DirectX12Descriptor", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Descriptor.html", null ],
    [ "Grindstone::GraphicsAPI::DirectX12DescriptorLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX12DescriptorLayout.html", null ],
    [ "Grindstone::Events::Dispatcher", "classGrindstone_1_1Events_1_1Dispatcher.html", null ],
    [ "Grindstone::Display", "structGrindstone_1_1Display.html", null ],
    [ "Grindstone::DisplayManager", "classGrindstone_1_1DisplayManager.html", null ],
    [ "Grindstone::Memory::Allocators::DynamicAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator.html", null ],
    [ "Grindstone::Editor::EditorCamera", "classGrindstone_1_1Editor_1_1EditorCamera.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ConsolePanel::EditorConsoleMessage", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1ConsolePanel_1_1EditorConsoleMessage.html", null ],
    [ "Grindstone::EngineCore", "classGrindstone_1_1EngineCore.html", null ],
    [ "EngineUboStruct", "structEngineUboStruct.html", null ],
    [ "Grindstone::ECS::Entity", "classGrindstone_1_1ECS_1_1Entity.html", null ],
    [ "Grindstone.Entity", "structGrindstone_1_1Entity.html", null ],
    [ "Grindstone::Assets::AssetRegistry::Entry", "structGrindstone_1_1Assets_1_1AssetRegistry_1_1Entry.html", null ],
    [ "Grindstone::Editor::AssetRegistry::Entry", "structGrindstone_1_1Editor_1_1AssetRegistry_1_1Entry.html", null ],
    [ "Grindstone::EnvironmentMapComponent", "structGrindstone_1_1EnvironmentMapComponent.html", null ],
    [ "Grindstone.Math.EulerAngles", "structGrindstone_1_1Math_1_1EulerAngles.html", null ],
    [ "ExportableQuaternion", "structExportableQuaternion.html", null ],
    [ "ExportableVector", "structExportableVector.html", null ],
    [ "Grindstone::Editor::File", "structGrindstone_1_1Editor_1_1File.html", null ],
    [ "Grindstone::Editor::FileManager", "classGrindstone_1_1Editor_1_1FileManager.html", null ],
    [ "Float2", "structFloat2.html", null ],
    [ "Grindstone.Math.Float2", "structGrindstone_1_1Math_1_1Float2.html", null ],
    [ "Grindstone.Math.Float3", "structGrindstone_1_1Math_1_1Float3.html", null ],
    [ "Grindstone.Math.Float4", "structGrindstone_1_1Math_1_1Float4.html", null ],
    [ "Grindstone::GraphicsAPI::Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1Framebuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX11Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX11Framebuffer.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Framebuffer.html", null ],
      [ "Grindstone::GraphicsAPI::GLFramebuffer", "classGrindstone_1_1GraphicsAPI_1_1GLFramebuffer.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanFramebuffer", "classGrindstone_1_1GraphicsAPI_1_1VulkanFramebuffer.html", null ]
    ] ],
    [ "Grindstone::Memory::Allocators::DynamicAllocator::FreeHeader", "structGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator_1_1FreeHeader.html", null ],
    [ "Grindstone::Memory::Allocators::BasePoolAllocator::FreeLink", "structGrindstone_1_1Memory_1_1Allocators_1_1BasePoolAllocator_1_1FreeLink.html", null ],
    [ "Grindstone::GameplayTag", "classGrindstone_1_1GameplayTag.html", null ],
    [ "Grindstone::GenericAssetReference", "structGrindstone_1_1GenericAssetReference.html", [
      [ "Grindstone::AssetReference< Grindstone::Audio::AudioClipAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::TextureAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::Mesh3dAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< T >", "structGrindstone_1_1AssetReference.html", null ]
    ] ],
    [ "Grindstone::Editor::GitManager", "classGrindstone_1_1Editor_1_1GitManager.html", null ],
    [ "Grindstone::Editor::GizmoRenderer", "classGrindstone_1_1Editor_1_1GizmoRenderer.html", null ],
    [ "Grindstone::Editor::GizmoRenderer::GizmoUniformBuffer", "structGrindstone_1_1Editor_1_1GizmoRenderer_1_1GizmoUniformBuffer.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline.html", [
      [ "Grindstone::GraphicsAPI::DirectX11GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1DirectX11GraphicsPipeline.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1DirectX12GraphicsPipeline.html", null ],
      [ "Grindstone::GraphicsAPI::GLGraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1GLGraphicsPipeline.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanGraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1VulkanGraphicsPipeline.html", null ]
    ] ],
    [ "GraphicsWrapper", null, [
      [ "Grindstone::GraphicsAPI::DirectX11GraphicsWrapper", "classGrindstone_1_1GraphicsAPI_1_1DirectX11GraphicsWrapper.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12GraphicsWrapper", "classGrindstone_1_1GraphicsAPI_1_1DirectX12GraphicsWrapper.html", null ]
    ] ],
    [ "Grindstone::Editor::GridRenderer", "classGrindstone_1_1Editor_1_1GridRenderer.html", null ],
    [ "GridUniformBuffer", "structGridUniformBuffer.html", null ],
    [ "Grindstone::HashedString", "classGrindstone_1_1HashedString.html", null ],
    [ "Grindstone::Assets::ArchiveContentFile::Header", "structGrindstone_1_1Assets_1_1ArchiveContentFile_1_1Header.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::Header", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1Header.html", null ],
    [ "Grindstone::Formats::Animation::V1::Header", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1Header.html", null ],
    [ "Grindstone::Formats::Model::V1::Header", "structGrindstone_1_1Formats_1_1Model_1_1V1_1_1Header.html", null ],
    [ "Grindstone::Editor::IEditor", "classGrindstone_1_1Editor_1_1IEditor.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiEditor", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiEditor.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiInput.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiInterface", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiInterface.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiRenderer", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiRenderer.html", [
      [ "Grindstone::Editor::ImguiEditor::ImguiRendererVulkan", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiRendererVulkan.html", null ]
    ] ],
    [ "Grindstone::Editor::Importers::Importer", "classGrindstone_1_1Editor_1_1Importers_1_1Importer.html", [
      [ "Grindstone::Editor::Importers::AudioImporter", "classGrindstone_1_1Editor_1_1Importers_1_1AudioImporter.html", null ],
      [ "Grindstone::Editor::Importers::MaterialImporter", "classGrindstone_1_1Editor_1_1Importers_1_1MaterialImporter.html", null ],
      [ "Grindstone::Editor::Importers::ModelImporter", "classGrindstone_1_1Editor_1_1Importers_1_1ModelImporter.html", null ],
      [ "Grindstone::Editor::Importers::ShaderImporter", "classGrindstone_1_1Editor_1_1Importers_1_1ShaderImporter.html", null ],
      [ "Grindstone::Editor::Importers::TextureImporter", "classGrindstone_1_1Editor_1_1Importers_1_1TextureImporter.html", null ]
    ] ],
    [ "Grindstone::Importers::ImporterManager", "classGrindstone_1_1Importers_1_1ImporterManager.html", null ],
    [ "Grindstone::GraphicsAPI::IndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1IndexBuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX11IndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX11IndexBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12IndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12IndexBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::GLIndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1GLIndexBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanIndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1VulkanIndexBuffer.html", null ]
    ] ],
    [ "Grindstone::Editor::ImguiEditor::InspectorPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1InspectorPanel.html", null ],
    [ "Grindstone::Profiler::InstrumentationSession", "structGrindstone_1_1Profiler_1_1InstrumentationSession.html", null ],
    [ "Grindstone::Input::Interface", "classGrindstone_1_1Input_1_1Interface.html", [
      [ "Grindstone::Input::Manager", "classGrindstone_1_1Input_1_1Manager.html", null ]
    ] ],
    [ "Grindstone::Plugins::Interface", "classGrindstone_1_1Plugins_1_1Interface.html", null ],
    [ "Grindstone::Reflection::DefaultResolver::IsReflected< T >", "structGrindstone_1_1Reflection_1_1DefaultResolver_1_1IsReflected.html", null ],
    [ "Grindstone::ECS::ISystem", "classGrindstone_1_1ECS_1_1ISystem.html", null ],
    [ "Grindstone::Memory::Allocators::LinearAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1LinearAllocator.html", null ],
    [ "Grindstone.Logger", "classGrindstone_1_1Logger.html", null ],
    [ "Grindstone::Logger::LoggerState", "structGrindstone_1_1Logger_1_1LoggerState.html", null ],
    [ "Grindstone::Editor::Manager", "classGrindstone_1_1Editor_1_1Manager.html", null ],
    [ "Grindstone::Plugins::Manager", "classGrindstone_1_1Plugins_1_1Manager.html", null ],
    [ "Grindstone::Profiler::Manager", "classGrindstone_1_1Profiler_1_1Manager.html", null ],
    [ "Grindstone::Editor::ImguiEditor::MaterialInspector", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialInspector.html", null ],
    [ "Grindstone::Editor::ImguiEditor::MaterialParameter", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialParameter.html", null ],
    [ "Grindstone::Editor::ImguiEditor::MaterialInspector::MaterialUniformBuffer::Member", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialInspector_1_1MaterialUniformBuffer_1_1Member.html", null ],
    [ "Grindstone::Editor::Importers::ShaderImporter::UniformBuffer::Member", "structGrindstone_1_1Editor_1_1Importers_1_1ShaderImporter_1_1UniformBuffer_1_1Member.html", null ],
    [ "Grindstone::Reflection::TypeDescriptor_Struct::Member", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct_1_1Member.html", null ],
    [ "Grindstone::ShaderReflectionData::StructData::MemberData", "structGrindstone_1_1ShaderReflectionData_1_1StructData_1_1MemberData.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Menubar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Menubar.html", null ],
    [ "Mesh3dUbo", "structMesh3dUbo.html", null ],
    [ "Grindstone::MeshComponent", "structGrindstone_1_1MeshComponent.html", null ],
    [ "Grindstone::MeshRendererComponent", "structGrindstone_1_1MeshRendererComponent.html", null ],
    [ "Grindstone::Editor::MetaFile", "classGrindstone_1_1Editor_1_1MetaFile.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptClass::Methods", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass_1_1Methods.html", null ],
    [ "Grindstone::Editor::ImguiEditor::NewComponentInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1NewComponentInput.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::PageData", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PageData.html", null ],
    [ "Grindstone::ParentComponent", "structGrindstone_1_1ParentComponent.html", null ],
    [ "Grindstone::BuildSettings::PluginBuildSettings", "classGrindstone_1_1BuildSettings_1_1PluginBuildSettings.html", null ],
    [ "Grindstone::PointLightComponent", "classGrindstone_1_1PointLightComponent.html", null ],
    [ "Grindstone::Formats::Animation::V1::PositionKeyframe", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1PositionKeyframe.html", null ],
    [ "Grindstone.Math.Quaternion", "classGrindstone_1_1Math_1_1Quaternion.html", null ],
    [ "Grindstone::GraphicsAPI::QueueFamilyIndices", "structGrindstone_1_1GraphicsAPI_1_1QueueFamilyIndices.html", null ],
    [ "Grindstone.Rect", "structGrindstone_1_1Rect.html", null ],
    [ "Grindstone::BaseRenderer::RenderMode", "structGrindstone_1_1BaseRenderer_1_1RenderMode.html", null ],
    [ "Grindstone::GraphicsAPI::RenderPass", "classGrindstone_1_1GraphicsAPI_1_1RenderPass.html", [
      [ "Grindstone::GraphicsAPI::DirectX11RenderPass", "classGrindstone_1_1GraphicsAPI_1_1DirectX11RenderPass.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12RenderPass", "classGrindstone_1_1GraphicsAPI_1_1DirectX12RenderPass.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanRenderPass", "classGrindstone_1_1GraphicsAPI_1_1VulkanRenderPass.html", null ]
    ] ],
    [ "Grindstone::Rendering::RenderPathBase", "classGrindstone_1_1Rendering_1_1RenderPathBase.html", null ],
    [ "Grindstone::RenderQueueContainer", "structGrindstone_1_1RenderQueueContainer.html", null ],
    [ "Grindstone::RenderSortData", "structGrindstone_1_1RenderSortData.html", null ],
    [ "Grindstone::GraphicsAPI::RenderTarget", "classGrindstone_1_1GraphicsAPI_1_1RenderTarget.html", [
      [ "Grindstone::GraphicsAPI::DirectX11RenderTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX11RenderTarget.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12RenderTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX12RenderTarget.html", null ],
      [ "Grindstone::GraphicsAPI::GLRenderTarget", "classGrindstone_1_1GraphicsAPI_1_1GLRenderTarget.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanRenderTarget", "classGrindstone_1_1GraphicsAPI_1_1VulkanRenderTarget.html", null ]
    ] ],
    [ "Grindstone::RenderTask", "structGrindstone_1_1RenderTask.html", null ],
    [ "Grindstone::ResourcePipeline", "classGrindstone_1_1ResourcePipeline.html", null ],
    [ "Grindstone::Profiler::Result", "structGrindstone_1_1Profiler_1_1Result.html", null ],
    [ "Grindstone::Physics::RigidBodyComponent", "structGrindstone_1_1Physics_1_1RigidBodyComponent.html", null ],
    [ "Grindstone::Formats::Animation::V1::RotationKeyframe", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1RotationKeyframe.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Sampler", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Sampler.html", null ],
    [ "Grindstone::Formats::Animation::V1::ScaleKeyframe", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1ScaleKeyframe.html", null ],
    [ "Grindstone.Scene", "structGrindstone_1_1Scene.html", null ],
    [ "Grindstone::SceneManagement::Scene", "classGrindstone_1_1SceneManagement_1_1Scene.html", null ],
    [ "Grindstone::BuildSettings::SceneBuildSettings", "classGrindstone_1_1BuildSettings_1_1SceneBuildSettings.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::Build::SceneData", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build_1_1SceneData.html", null ],
    [ "Grindstone::Editor::ImguiEditor::SceneHeirarchyPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SceneHeirarchyPanel.html", null ],
    [ "Grindstone::SceneManagement::SceneLoaderJson", "classGrindstone_1_1SceneManagement_1_1SceneLoaderJson.html", null ],
    [ "Grindstone::SceneManagement::SceneManager", "classGrindstone_1_1SceneManagement_1_1SceneManager.html", null ],
    [ "Grindstone::SceneManagement::SceneWriterJson", "classGrindstone_1_1SceneManagement_1_1SceneWriterJson.html", null ],
    [ "Grindstone::ScriptBase", "classGrindstone_1_1ScriptBase.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptClass", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptComponent", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptComponent.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptField", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptField.html", null ],
    [ "Grindstone::Editor::Selection", "classGrindstone_1_1Editor_1_1Selection.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::SettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1SettingsWindow.html", [
      [ "Grindstone::Editor::ImguiEditor::Settings::ProjectSettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1ProjectSettingsWindow.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::UserSettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1UserSettingsWindow.html", null ]
    ] ],
    [ "Grindstone::ShaderReflectionData", "structGrindstone_1_1ShaderReflectionData.html", null ],
    [ "Grindstone::ShaderReflectionLoader", "classGrindstone_1_1ShaderReflectionLoader.html", null ],
    [ "Grindstone::GraphicsAPI::ShaderStageCreateInfo", "structGrindstone_1_1GraphicsAPI_1_1ShaderStageCreateInfo.html", null ],
    [ "ShaderVertexLayouts", "structShaderVertexLayouts.html", null ],
    [ "Grindstone::Editor::GizmoRenderer::ShapeMetaData", "structGrindstone_1_1Editor_1_1GizmoRenderer_1_1ShapeMetaData.html", null ],
    [ "Grindstone::Memory::SmartPointers::SharedPtr< T >", "classGrindstone_1_1Memory_1_1SmartPointers_1_1SharedPtr.html", null ],
    [ "Grindstone::Memory::SmartPointers::SharedPtr< T >::SharedPtrRefCounter", "structGrindstone_1_1Memory_1_1SmartPointers_1_1SharedPtr_1_1SharedPtrRefCounter.html", null ],
    [ "Grindstone.SmartComponent", "classGrindstone_1_1SmartComponent.html", null ],
    [ "Grindstone::Editor::ScriptBuilder::SolutionBuilder", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1SolutionBuilder.html", null ],
    [ "Grindstone::Audio::Source", "classGrindstone_1_1Audio_1_1Source.html", null ],
    [ "SourceSubmesh", "structSourceSubmesh.html", null ],
    [ "Grindstone::SpotLightComponent", "structGrindstone_1_1SpotLightComponent.html", null ],
    [ "SsaoUboStruct", "structSsaoUboStruct.html", null ],
    [ "Grindstone::Memory::Allocators::StackAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1StackAllocator.html", null ],
    [ "Grindstone::Editor::Importers::StandardMaterialCreateInfo", "structGrindstone_1_1Editor_1_1Importers_1_1StandardMaterialCreateInfo.html", null ],
    [ "Grindstone::Editor::ImguiEditor::StatsPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatsPanel.html", null ],
    [ "Grindstone::Editor::ImguiEditor::StatusBar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatusBar.html", null ],
    [ "Grindstone::ShaderReflectionData::StructData", "structGrindstone_1_1ShaderReflectionData_1_1StructData.html", null ],
    [ "Grindstone::Editor::MetaFile::Subasset", "structGrindstone_1_1Editor_1_1MetaFile_1_1Subasset.html", null ],
    [ "Grindstone::Mesh3dAsset::Submesh", "structGrindstone_1_1Mesh3dAsset_1_1Submesh.html", null ],
    [ "Grindstone::Editor::ImguiEditor::SuggestedInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SuggestedInput.html", null ],
    [ "Grindstone::GraphicsAPI::SwapChainSupportDetails", "structGrindstone_1_1GraphicsAPI_1_1SwapChainSupportDetails.html", null ],
    [ "Grindstone::Editor::ImguiEditor::SystemPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SystemPanel.html", null ],
    [ "Grindstone::ECS::SystemRegistrar", "classGrindstone_1_1ECS_1_1SystemRegistrar.html", null ],
    [ "Grindstone.SystemRegistrar", "classGrindstone_1_1SystemRegistrar.html", null ],
    [ "Grindstone::TagComponent", "classGrindstone_1_1TagComponent.html", null ],
    [ "Grindstone::Editor::Task", "structGrindstone_1_1Editor_1_1Task.html", null ],
    [ "Grindstone::Editor::ImguiEditor::TaskPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1TaskPanel.html", null ],
    [ "Grindstone::Editor::TaskSystem", "classGrindstone_1_1Editor_1_1TaskSystem.html", null ],
    [ "Grindstone::Editor::Importers::ShaderImporter::Texture", "structGrindstone_1_1Editor_1_1Importers_1_1ShaderImporter_1_1Texture.html", null ],
    [ "Grindstone::GraphicsAPI::Texture", "classGrindstone_1_1GraphicsAPI_1_1Texture.html", [
      [ "Grindstone::GraphicsAPI::DirectX11Texture", "classGrindstone_1_1GraphicsAPI_1_1DirectX11Texture.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12Texture", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Texture.html", null ],
      [ "Grindstone::GraphicsAPI::GLTexture", "classGrindstone_1_1GraphicsAPI_1_1GLTexture.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanTexture", "classGrindstone_1_1GraphicsAPI_1_1VulkanTexture.html", null ]
    ] ],
    [ "TextureBinding", null, [
      [ "Grindstone::GraphicsAPI::DirectX11TextureBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX11TextureBinding.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12TextureBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX12TextureBinding.html", null ]
    ] ],
    [ "TextureBindingLayout", null, [
      [ "Grindstone::GraphicsAPI::DirectX11TextureBindingLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX11TextureBindingLayout.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12TextureBindingLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX12TextureBindingLayout.html", null ]
    ] ],
    [ "Grindstone::ShaderReflectionData::TextureData", "structGrindstone_1_1ShaderReflectionData_1_1TextureData.html", null ],
    [ "Grindstone::GraphicsAPI::TextureMipMapCreateInfo", "structGrindstone_1_1GraphicsAPI_1_1TextureMipMapCreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::TextureOptions", "structGrindstone_1_1GraphicsAPI_1_1TextureOptions.html", null ],
    [ "Grindstone::Profiler::Timer", "classGrindstone_1_1Profiler_1_1Timer.html", null ],
    [ "Grindstone::Editor::ImguiEditor::TracingPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1TracingPanel.html", null ],
    [ "Grindstone::TransformComponent", "classGrindstone_1_1TransformComponent.html", null ],
    [ "Grindstone::Reflection::TypeDescriptor", "structGrindstone_1_1Reflection_1_1TypeDescriptor.html", [
      [ "Grindstone::Reflection::TypeDescriptor_AssetReference", "structGrindstone_1_1Reflection_1_1TypeDescriptor__AssetReference.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Bool", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Bool.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Entity", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Entity.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Quat", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Quat.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_StdString", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdString.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_StdVector", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdVector.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Struct", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct.html", null ]
    ] ],
    [ "Grindstone::Reflection::TypeResolver< T >", "structGrindstone_1_1Reflection_1_1TypeResolver.html", null ],
    [ "Grindstone::Reflection::TypeResolver< Grindstone::AssetReference< T > >", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01Grindstone_1_1AssetReference_3_01T_01_4_01_4.html", null ],
    [ "Grindstone::Reflection::TypeResolver< std::vector< T > >", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "Grindstone::Editor::Importers::ShaderImporter::UniformBuffer", "structGrindstone_1_1Editor_1_1Importers_1_1ShaderImporter_1_1UniformBuffer.html", null ],
    [ "Grindstone::GraphicsAPI::UniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1UniformBuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX11UniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX11UniformBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12UniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12UniformBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::GLUniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1GLUniformBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanUniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1VulkanUniformBuffer.html", null ]
    ] ],
    [ "UniformBufferBinding", null, [
      [ "Grindstone::GraphicsAPI::DirectX11UniformBufferBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX11UniformBufferBinding.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12UniformBufferBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX12UniformBufferBinding.html", null ]
    ] ],
    [ "Grindstone::DirectionalLightComponent::UniformStruct", "structGrindstone_1_1DirectionalLightComponent_1_1UniformStruct.html", null ],
    [ "Grindstone::PointLightComponent::UniformStruct", "structGrindstone_1_1PointLightComponent_1_1UniformStruct.html", null ],
    [ "Grindstone::SpotLightComponent::UniformStruct", "structGrindstone_1_1SpotLightComponent_1_1UniformStruct.html", null ],
    [ "Grindstone::Memory::SmartPointers::UniquePtr< T >", "classGrindstone_1_1Memory_1_1SmartPointers_1_1UniquePtr.html", null ],
    [ "Grindstone::Uuid", "classGrindstone_1_1Uuid.html", null ],
    [ "Grindstone::Editor::Importers::ModelImporter::OutputData::VertexArray", "structGrindstone_1_1Editor_1_1Importers_1_1ModelImporter_1_1OutputData_1_1VertexArray.html", null ],
    [ "Grindstone::GraphicsAPI::VertexArrayBindingLayout", "structGrindstone_1_1GraphicsAPI_1_1VertexArrayBindingLayout.html", null ],
    [ "Grindstone::GraphicsAPI::VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1VertexArrayObject.html", [
      [ "Grindstone::GraphicsAPI::DirectX11VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1DirectX11VertexArrayObject.html", null ],
      [ "Grindstone::GraphicsAPI::GLVertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1GLVertexArrayObject.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanVertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1VulkanVertexArrayObject.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::VertexAttributeDescription", "structGrindstone_1_1GraphicsAPI_1_1VertexAttributeDescription.html", null ],
    [ "Grindstone::GraphicsAPI::VertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1VertexBuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX11VertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX11VertexBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::DirectX12VertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12VertexBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::GLVertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1GLVertexBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanVertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1VulkanVertexBuffer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::VertexBufferLayout", "structGrindstone_1_1GraphicsAPI_1_1VertexBufferLayout.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ViewportPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ViewportPanel.html", null ],
    [ "Grindstone::GraphicsAPI::VulkanImageSet", "structGrindstone_1_1GraphicsAPI_1_1VulkanImageSet.html", null ],
    [ "Grindstone::GraphicsAPI::VulkanImageSetNative", "structGrindstone_1_1GraphicsAPI_1_1VulkanImageSetNative.html", null ],
    [ "Grindstone::GraphicsAPI::VulkanWindowBindingDataNative", "structGrindstone_1_1GraphicsAPI_1_1VulkanWindowBindingDataNative.html", null ],
    [ "Grindstone.Window", "classGrindstone_1_1Window.html", [
      [ "Grindstone::GlfwWindow", "classGrindstone_1_1GlfwWindow.html", null ],
      [ "Grindstone::Win32Window", "classGrindstone_1_1Win32Window.html", null ],
      [ "Grindstone::X11Window", "classGrindstone_1_1X11Window.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1WindowGraphicsBinding.html", [
      [ "Grindstone::GraphicsAPI::GLWindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1GLWindowGraphicsBinding.html", null ],
      [ "Grindstone::GraphicsAPI::VulkanWindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1VulkanWindowGraphicsBinding.html", null ]
    ] ],
    [ "Grindstone::WindowManager", "classGrindstone_1_1WindowManager.html", null ]
];