var hierarchy =
[
    [ "Grindstone::Renderer::AABB", "structGrindstone_1_1Renderer_1_1AABB.html", null ],
    [ "Grindstone::Memory::Allocators::DynamicAllocator::AllocationHeader", "structGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator_1_1AllocationHeader.html", null ],
    [ "Grindstone::Memory::AllocatorCore::AllocatorState", "structGrindstone_1_1Memory_1_1AllocatorCore_1_1AllocatorState.html", null ],
    [ "Grindstone::AnimatorComponent", "structGrindstone_1_1AnimatorComponent.html", null ],
    [ "Grindstone::Assets::ArchiveContentFile", "structGrindstone_1_1Assets_1_1ArchiveContentFile.html", null ],
    [ "Grindstone::Assets::ArchiveDirectory", "structGrindstone_1_1Assets_1_1ArchiveDirectory.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryDeserializer", "classGrindstone_1_1Assets_1_1ArchiveDirectoryDeserializer.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile.html", null ],
    [ "Grindstone::Assets::ArchiveDirectory::ArchiveInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectory_1_1ArchiveInfo.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::ArchiveInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1ArchiveInfo.html", null ],
    [ "Grindstone::Containers::ArrayIterator&lt; T &gt;", "structGrindstone_1_1Containers_1_1ArrayIterator.html", null ],
    [ "Grindstone::Scripting::CSharp::CSharpManager::AssemblyData", "structGrindstone_1_1Scripting_1_1CSharp_1_1CSharpManager_1_1AssemblyData.html", null ],
    [ "AssemblyDefinition", "structAssemblyDefinition.html", null ],
    [ "AssemblyLoadContext", null, [
      [ "Grindstone.HotReloadContext", "classGrindstone_1_1HotReloadContext.html", null ]
    ] ],
    [ "AssemblyReference", "structAssemblyReference.html", null ],
    [ "Grindstone::Asset", "structGrindstone_1_1Asset.html", [
      [ "Grindstone::AnimationClipAsset", "structGrindstone_1_1AnimationClipAsset.html", null ],
      [ "Grindstone::Audio::AudioClipAsset", "structGrindstone_1_1Audio_1_1AudioClipAsset.html", null ],
      [ "Grindstone::ComputePipelineAsset", "structGrindstone_1_1ComputePipelineAsset.html", null ],
      [ "Grindstone::GraphicsPipelineAsset", "structGrindstone_1_1GraphicsPipelineAsset.html", null ],
      [ "Grindstone::MaterialAsset", "structGrindstone_1_1MaterialAsset.html", null ],
      [ "Grindstone::Mesh3dAsset", "structGrindstone_1_1Mesh3dAsset.html", null ],
      [ "Grindstone::RigAsset", "structGrindstone_1_1RigAsset.html", null ],
      [ "Grindstone::TextureAsset", "structGrindstone_1_1TextureAsset.html", null ]
    ] ],
    [ "Grindstone::Editor::ImguiEditor::AssetBrowserPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetBrowserPanel.html", null ],
    [ "Grindstone::Plugins::MetaData::AssetDirectory", "structGrindstone_1_1Plugins_1_1MetaData_1_1AssetDirectory.html", null ],
    [ "Grindstone::AssetImporter", "classGrindstone_1_1AssetImporter.html", [
      [ "Grindstone::SpecificAssetImporter< AnimationClipAsset, AssetType::AnimationClip >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::AnimationClipImporter", "classGrindstone_1_1AnimationClipImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< AudioClipAsset, AssetType::AudioClip >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::Audio::AudioClipImporter", "classGrindstone_1_1Audio_1_1AudioClipImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< ComputePipelineAsset, AssetType::ComputePipelineSet >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::ComputePipelineImporter", "classGrindstone_1_1ComputePipelineImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< GraphicsPipelineAsset, AssetType::GraphicsPipelineSet >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::GraphicsPipelineImporter", "classGrindstone_1_1GraphicsPipelineImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< MaterialAsset, AssetType::Material >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::MaterialImporter", "classGrindstone_1_1MaterialImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< Mesh3dAsset, AssetType::Mesh3d >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::Mesh3dImporter", "classGrindstone_1_1Mesh3dImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< RigAsset, AssetType::Rig >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::RigImporter", "classGrindstone_1_1RigImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< TextureAsset, AssetType::Texture >", "classGrindstone_1_1SpecificAssetImporter.html", [
        [ "Grindstone::TextureImporter", "classGrindstone_1_1TextureImporter.html", null ]
      ] ],
      [ "Grindstone::SpecificAssetImporter< AssetStructType, internalAssetType >", "classGrindstone_1_1SpecificAssetImporter.html", null ]
    ] ],
    [ "Grindstone::Assets::ArchiveDirectory::AssetInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectory_1_1AssetInfo.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::AssetInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1AssetInfo.html", null ],
    [ "Grindstone::Assets::AssetLoadBinaryResult", "structGrindstone_1_1Assets_1_1AssetLoadBinaryResult.html", null ],
    [ "Grindstone::Assets::AssetLoader", "classGrindstone_1_1Assets_1_1AssetLoader.html", [
      [ "Grindstone::Assets::ArchiveAssetLoader", "classGrindstone_1_1Assets_1_1ArchiveAssetLoader.html", null ],
      [ "Grindstone::Assets::FileAssetLoader", "classGrindstone_1_1Assets_1_1FileAssetLoader.html", null ]
    ] ],
    [ "Grindstone::Assets::AssetLoadTextResult", "structGrindstone_1_1Assets_1_1AssetLoadTextResult.html", null ],
    [ "Grindstone::Assets::AssetManager", "classGrindstone_1_1Assets_1_1AssetManager.html", null ],
    [ "Grindstone::Assets::AssetPackSerializer::AssetPackageSerializer", "classGrindstone_1_1Assets_1_1AssetPackSerializer_1_1AssetPackageSerializer.html", null ],
    [ "Grindstone::Editor::ImguiEditor::AssetPicker", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetPicker.html", null ],
    [ "Grindstone::Assets::AssetRegistry", "classGrindstone_1_1Assets_1_1AssetRegistry.html", null ],
    [ "Grindstone::Editor::AssetRegistry", "classGrindstone_1_1Editor_1_1AssetRegistry.html", null ],
    [ "Grindstone::AssetRendererManager", "classGrindstone_1_1AssetRendererManager.html", null ],
    [ "Grindstone::Editor::AssetTemplateRegistry::AssetTemplate", "structGrindstone_1_1Editor_1_1AssetTemplateRegistry_1_1AssetTemplate.html", null ],
    [ "Grindstone::Editor::AssetTemplateRegistry", "classGrindstone_1_1Editor_1_1AssetTemplateRegistry.html", null ],
    [ "Grindstone::Assets::ArchiveDirectory::AssetTypeIndex", "structGrindstone_1_1Assets_1_1ArchiveDirectory_1_1AssetTypeIndex.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::AssetTypeSectionInfo", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1AssetTypeSectionInfo.html", null ],
    [ "Grindstone::Editor::ThumbnailManager::AtlasCoords", "structGrindstone_1_1Editor_1_1ThumbnailManager_1_1AtlasCoords.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline::AttachmentData", "structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1AttachmentData.html", null ],
    [ "ParseTree::RenderState::AttachmentData", "structParseTree_1_1RenderState_1_1AttachmentData.html", null ],
    [ "Grindstone::GraphicsAPI::RenderPass::AttachmentInfo", "structGrindstone_1_1GraphicsAPI_1_1RenderPass_1_1AttachmentInfo.html", null ],
    [ "Grindstone::Renderer::AttachmentInfo", "structGrindstone_1_1Renderer_1_1AttachmentInfo.html", null ],
    [ "Grindstone::Renderer::PassImageDesc::AttachmentMeta", "structGrindstone_1_1Renderer_1_1PassImageDesc_1_1AttachmentMeta.html", null ],
    [ "Grindstone::AudioListenerComponent", "structGrindstone_1_1AudioListenerComponent.html", null ],
    [ "Grindstone::AudioSourceComponent", "structGrindstone_1_1AudioSourceComponent.html", null ],
    [ "Grindstone::BaseAssetRenderer", "classGrindstone_1_1BaseAssetRenderer.html", [
      [ "Grindstone::Mesh3dRenderer", "classGrindstone_1_1Mesh3dRenderer.html", null ],
      [ "Grindstone::SkeletalMeshRenderer", "classGrindstone_1_1SkeletalMeshRenderer.html", null ]
    ] ],
    [ "Grindstone::Editor::BaseCommand", "classGrindstone_1_1Editor_1_1BaseCommand.html", [
      [ "Grindstone::Editor::AddComponentCommand", "classGrindstone_1_1Editor_1_1AddComponentCommand.html", null ],
      [ "Grindstone::Editor::AddEntityCommand", "classGrindstone_1_1Editor_1_1AddEntityCommand.html", null ],
      [ "Grindstone::Editor::DeleteComponentCommand", "classGrindstone_1_1Editor_1_1DeleteComponentCommand.html", null ],
      [ "Grindstone::Editor::DeleteEntityCommand", "classGrindstone_1_1Editor_1_1DeleteEntityCommand.html", null ],
      [ "Grindstone::Editor::JointCommand", "classGrindstone_1_1Editor_1_1JointCommand.html", null ],
      [ "Grindstone::Editor::SetDataCommand", "classGrindstone_1_1Editor_1_1SetDataCommand.html", null ]
    ] ],
    [ "Grindstone::Events::BaseEvent", "structGrindstone_1_1Events_1_1BaseEvent.html", [
      [ "Grindstone::Events::CharacterTypedEvent", "structGrindstone_1_1Events_1_1CharacterTypedEvent.html", null ],
      [ "Grindstone::Events::KeyPressEvent", "structGrindstone_1_1Events_1_1KeyPressEvent.html", null ],
      [ "Grindstone::Events::MouseMovedEvent", "structGrindstone_1_1Events_1_1MouseMovedEvent.html", null ],
      [ "Grindstone::Events::MousePressEvent", "structGrindstone_1_1Events_1_1MousePressEvent.html", null ],
      [ "Grindstone::Events::MouseScrolledEvent", "structGrindstone_1_1Events_1_1MouseScrolledEvent.html", null ],
      [ "Grindstone::Events::PrintMessageEvent", "structGrindstone_1_1Events_1_1PrintMessageEvent.html", null ],
      [ "Grindstone::Events::WindowForceQuitEvent", "structGrindstone_1_1Events_1_1WindowForceQuitEvent.html", null ],
      [ "Grindstone::Events::WindowKillFocusEvent", "structGrindstone_1_1Events_1_1WindowKillFocusEvent.html", null ],
      [ "Grindstone::Events::WindowMovedEvent", "structGrindstone_1_1Events_1_1WindowMovedEvent.html", null ],
      [ "Grindstone::Events::WindowResizeEvent", "structGrindstone_1_1Events_1_1WindowResizeEvent.html", null ],
      [ "Grindstone::Events::WindowStartFocusEvent", "structGrindstone_1_1Events_1_1WindowStartFocusEvent.html", null ],
      [ "Grindstone::Events::WindowTryQuitEvent", "structGrindstone_1_1Events_1_1WindowTryQuitEvent.html", null ]
    ] ],
    [ "Grindstone::Editor::ImguiEditor::Settings::BasePage", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1BasePage.html", [
      [ "Grindstone::Editor::ImguiEditor::Settings::Build", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::CodeTools", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1CodeTools.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::PlatformWindows", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PlatformWindows.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::Platforms", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Platforms.html", null ],
      [ "Grindstone::Physics::JoltPhysicsSettingsPage", "classGrindstone_1_1Physics_1_1JoltPhysicsSettingsPage.html", null ],
      [ "JoltPhysicsSettingsPage", "classJoltPhysicsSettingsPage.html", null ]
    ] ],
    [ "Grindstone::Memory::Allocators::BasePoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1BasePoolAllocator.html", [
      [ "Grindstone::Memory::Allocators::GenericPoolAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1GenericPoolAllocator.html", null ],
      [ "Grindstone::Memory::Allocators::PoolAllocator< T >", "classGrindstone_1_1Memory_1_1Allocators_1_1PoolAllocator.html", null ]
    ] ],
    [ "Grindstone::BaseRenderer", "classGrindstone_1_1BaseRenderer.html", [
      [ "Grindstone::DeferredRenderer", "classGrindstone_1_1DeferredRenderer.html", null ]
    ] ],
    [ "Grindstone::BaseRendererFactory", "classGrindstone_1_1BaseRendererFactory.html", [
      [ "Grindstone::DeferredRendererFactory", "classGrindstone_1_1DeferredRendererFactory.html", null ]
    ] ],
    [ "Grindstone::Plugins::MetaData::Binary", "structGrindstone_1_1Plugins_1_1MetaData_1_1Binary.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSet::Binding", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSet_1_1Binding.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSetLayout::Binding", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_1_1Binding.html", null ],
    [ "Grindstone::Containers::Bitset&lt; bitCount, WordType &gt;", "classGrindstone_1_1Containers_1_1Bitset.html", null ],
    [ "Grindstone::Containers::Bitset&lt; static_cast&lt; std::underlying_type_t&lt; Enum &gt; &gt;(Enum::Count), std::underlying_type_t&lt; Enum &gt; &gt;", "classGrindstone_1_1Containers_1_1Bitset.html", [
      [ "Grindstone::Containers::BitsetEnum< Enum >", "classGrindstone_1_1Containers_1_1BitsetEnum.html", null ]
    ] ],
    [ "Grindstone::Containers::BitsetFlags&lt; Enum &gt;", "classGrindstone_1_1Containers_1_1BitsetFlags.html", null ],
    [ "Grindstone::GraphicsAPI::BlendData", "structGrindstone_1_1GraphicsAPI_1_1BlendData.html", null ],
    [ "BloomDataUboStruct", "structBloomDataUboStruct.html", null ],
    [ "Grindstone::Renderer::BloomPass", "classGrindstone_1_1Renderer_1_1BloomPass.html", null ],
    [ "BloomStageUboStruct", "structBloomStageUboStruct.html", null ],
    [ "Grindstone::Renderer::BlurPass", "classGrindstone_1_1Renderer_1_1BlurPass.html", null ],
    [ "JPH::BodyActivationListener", null, [
      [ "Grindstone::Physics::MyBodyActivationListener", "classGrindstone_1_1Physics_1_1MyBodyActivationListener.html", null ]
    ] ],
    [ "Grindstone::Formats::Rig::V1::Bone", "structGrindstone_1_1Formats_1_1Rig_1_1V1_1_1Bone.html", null ],
    [ "Grindstone::RigAsset::Bone", "structGrindstone_1_1RigAsset_1_1Bone.html", null ],
    [ "Grindstone::AnimationClipAsset::BoneChannel", "structGrindstone_1_1AnimationClipAsset_1_1BoneChannel.html", null ],
    [ "Grindstone::Formats::Animation::V1::BoneChannel", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1BoneChannel.html", null ],
    [ "Grindstone::Formats::Animation::V1::BoneChannelData", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1BoneChannelData.html", null ],
    [ "BoneInfo", "structBoneInfo.html", null ],
    [ "Grindstone::Formats::Model::V1::BoundingData", "structGrindstone_1_1Formats_1_1Model_1_1V1_1_1BoundingData.html", null ],
    [ "Grindstone::Math::Box3D", "structGrindstone_1_1Math_1_1Box3D.html", null ],
    [ "JPH::BroadPhaseLayerInterface", null, [
      [ "Grindstone::Physics::BPLayerInterfaceImpl", "classGrindstone_1_1Physics_1_1BPLayerInterfaceImpl.html", null ]
    ] ],
    [ "Grindstone::Buffer", "classGrindstone_1_1Buffer.html", [
      [ "Grindstone::ResizableBuffer", "classGrindstone_1_1ResizableBuffer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::Buffer", "classGrindstone_1_1GraphicsAPI_1_1Buffer.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::Buffer", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Buffer.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::Buffer", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Buffer.html", null ]
    ] ],
    [ "Grindstone::PipelineAssetMetaData::Buffer", "structGrindstone_1_1PipelineAssetMetaData_1_1Buffer.html", null ],
    [ "Grindstone::GraphicsAPI::BufferBarrier", "structGrindstone_1_1GraphicsAPI_1_1BufferBarrier.html", null ],
    [ "Grindstone::GraphicsAPI::BufferCopyRegion", "structGrindstone_1_1GraphicsAPI_1_1BufferCopyRegion.html", null ],
    [ "Grindstone::Renderer::BufferDescription", "structGrindstone_1_1Renderer_1_1BufferDescription.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::BufferReflection", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1BufferReflection.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::BufferReflectionMember", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1BufferReflectionMember.html", null ],
    [ "Grindstone::Renderer::BufferTransfer", "structGrindstone_1_1Renderer_1_1BufferTransfer.html", null ],
    [ "Grindstone::Renderer::BuilderBufferTransfer", "structGrindstone_1_1Renderer_1_1BuilderBufferTransfer.html", null ],
    [ "Grindstone::Renderer::BuilderImageTransfer", "structGrindstone_1_1Renderer_1_1BuilderImageTransfer.html", null ],
    [ "Grindstone::Editor::ImguiEditor::BuildPopup", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1BuildPopup.html", null ],
    [ "Grindstone::Editor::BuildProcessStats", "structGrindstone_1_1Editor_1_1BuildProcessStats.html", null ],
    [ "Grindstone::Camera", "classGrindstone_1_1Camera.html", null ],
    [ "Grindstone::CameraComponent", "structGrindstone_1_1CameraComponent.html", null ],
    [ "Grindstone::Reflection::TypeDescriptor_Struct::Category", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct_1_1Category.html", null ],
    [ "Grindstone::Physics::CharacterKinematicControllerComponent", "structGrindstone_1_1Physics_1_1CharacterKinematicControllerComponent.html", null ],
    [ "Grindstone::Physics::CharacterRigidbodyControllerComponent", "structGrindstone_1_1Physics_1_1CharacterRigidbodyControllerComponent.html", null ],
    [ "Grindstone.Physics.Jolt.CharacterRigidbodyControllerComponent", "classGrindstone_1_1Physics_1_1Jolt_1_1CharacterRigidbodyControllerComponent.html", null ],
    [ "ChildEntity", "structChildEntity.html", null ],
    [ "Grindstone::GraphicsAPI::ClearAttachment", "structGrindstone_1_1GraphicsAPI_1_1ClearAttachment.html", null ],
    [ "Grindstone::GraphicsAPI::ClearColor", "unionGrindstone_1_1GraphicsAPI_1_1ClearColor.html", null ],
    [ "Grindstone::GraphicsAPI::ClearDepthStencil", "structGrindstone_1_1GraphicsAPI_1_1ClearDepthStencil.html", null ],
    [ "Grindstone::GraphicsAPI::ClearRect", "structGrindstone_1_1GraphicsAPI_1_1ClearRect.html", null ],
    [ "Grindstone::GraphicsAPI::ClearUnion", "unionGrindstone_1_1GraphicsAPI_1_1ClearUnion.html", null ],
    [ "Grindstone::Physics::ColliderComponent", "structGrindstone_1_1Physics_1_1ColliderComponent.html", [
      [ "Grindstone::Physics::BoxColliderComponent", "structGrindstone_1_1Physics_1_1BoxColliderComponent.html", null ],
      [ "Grindstone::Physics::BoxColliderComponent", "structGrindstone_1_1Physics_1_1BoxColliderComponent.html", null ],
      [ "Grindstone::Physics::CapsuleColliderComponent", "structGrindstone_1_1Physics_1_1CapsuleColliderComponent.html", null ],
      [ "Grindstone::Physics::CapsuleColliderComponent", "structGrindstone_1_1Physics_1_1CapsuleColliderComponent.html", null ],
      [ "Grindstone::Physics::PlaneColliderComponent", "structGrindstone_1_1Physics_1_1PlaneColliderComponent.html", null ],
      [ "Grindstone::Physics::PlaneColliderComponent", "structGrindstone_1_1Physics_1_1PlaneColliderComponent.html", null ],
      [ "Grindstone::Physics::SphereColliderComponent", "structGrindstone_1_1Physics_1_1SphereColliderComponent.html", null ],
      [ "Grindstone::Physics::SphereColliderComponent", "structGrindstone_1_1Physics_1_1SphereColliderComponent.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1CommandBuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX12CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12CommandBuffer.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::CommandBuffer", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1CommandBuffer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::CommandBuffer::CommandBufferSecondaryInfo", "structGrindstone_1_1GraphicsAPI_1_1CommandBuffer_1_1CommandBufferSecondaryInfo.html", null ],
    [ "Grindstone::Editor::CommandList", "classGrindstone_1_1Editor_1_1CommandList.html", null ],
    [ "CompilationArtifactsCompute", "structCompilationArtifactsCompute.html", null ],
    [ "CompilationArtifactsGraphics", "structCompilationArtifactsGraphics.html", null ],
    [ "CompilationOptions", "structCompilationOptions.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::CompilerProperties", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1CompilerProperties.html", null ],
    [ "Grindstone::ECS::ComponentFunctions", "classGrindstone_1_1ECS_1_1ComponentFunctions.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ComponentInspector", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ComponentInspector.html", null ],
    [ "Grindstone.ComponentRegistrar", "classGrindstone_1_1ComponentRegistrar.html", null ],
    [ "Grindstone::ECS::ComponentRegistrar", "classGrindstone_1_1ECS_1_1ComponentRegistrar.html", null ],
    [ "Grindstone::GraphicsAPI::ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1ComputePipeline.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1ComputePipeline.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::ComputePipeline", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1ComputePipeline.html", null ]
    ] ],
    [ "Grindstone::Formats::Pipelines::V1::ComputePipelineConfigurationHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ComputePipelineConfigurationHeader.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::ComputePipelineSetHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ComputePipelineSetHeader.html", null ],
    [ "ParseTree::ComputeSet", "structParseTree_1_1ComputeSet.html", null ],
    [ "ResolvedStateTree::ComputeSet", "structResolvedStateTree_1_1ComputeSet.html", null ],
    [ "CompilationArtifactsGraphics::Configuration", "structCompilationArtifactsGraphics_1_1Configuration.html", null ],
    [ "ParseTree::Configuration", "structParseTree_1_1Configuration.html", null ],
    [ "ResolvedStateTree::Configuration", "structResolvedStateTree_1_1Configuration.html", null ],
    [ "Grindstone::ConsoleMessage", "structGrindstone_1_1ConsoleMessage.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ConsolePanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ConsolePanel.html", null ],
    [ "Grindstone::Containers::ConstArrayIterator&lt; T &gt;", "structGrindstone_1_1Containers_1_1ConstArrayIterator.html", null ],
    [ "Grindstone::ConstHashedString", "classGrindstone_1_1ConstHashedString.html", null ],
    [ "Grindstone::Containers::ConstReverseArrayIterator&lt; T &gt;", "structGrindstone_1_1Containers_1_1ConstReverseArrayIterator.html", null ],
    [ "JPH::ContactListener", null, [
      [ "Grindstone::Physics::MyContactListener", "classGrindstone_1_1Physics_1_1MyContactListener.html", null ]
    ] ],
    [ "Grindstone::Editor::ImguiEditor::ControlBar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ControlBar.html", null ],
    [ "Grindstone::Audio::Core", "classGrindstone_1_1Audio_1_1Core.html", null ],
    [ "Grindstone::GraphicsAPI::Core", "classGrindstone_1_1GraphicsAPI_1_1Core.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::Core", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Core.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::Core", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Core.html", null ]
    ] ],
    [ "Grindstone::Audio::Source::CreateInfo", "structGrindstone_1_1Audio_1_1Source_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Buffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Buffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::CommandBuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1CommandBuffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::ComputePipeline::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1ComputePipeline_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Core::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Core_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSet::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSet_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::DescriptorSetLayout::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Framebuffer::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Framebuffer_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Image::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Image_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::PipelineLayout::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1PipelineLayout_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::RenderPass::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1RenderPass_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::Sampler::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Sampler_1_1CreateInfo.html", null ],
    [ "Grindstone::GraphicsAPI::VertexArrayObject::CreateInfo", "structGrindstone_1_1GraphicsAPI_1_1VertexArrayObject_1_1CreateInfo.html", null ],
    [ "Grindstone::Window::CreateInfo", "structGrindstone_1_1Window_1_1CreateInfo.html", null ],
    [ "Grindstone::Editor::ScriptBuilder::CSharpBuildManager", "classGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpBuildManager.html", null ],
    [ "Grindstone::CsharpGlobals", "structGrindstone_1_1CsharpGlobals.html", null ],
    [ "Grindstone::Scripting::CSharp::CSharpManager", "classGrindstone_1_1Scripting_1_1CSharp_1_1CSharpManager.html", null ],
    [ "Grindstone::Editor::ScriptBuilder::CSharpProjectMetaData", "structGrindstone_1_1Editor_1_1ScriptBuilder_1_1CSharpProjectMetaData.html", null ],
    [ "Grindstone::Renderer::CullingFrustum", "structGrindstone_1_1Renderer_1_1CullingFrustum.html", null ],
    [ "Grindstone::Editor::ImguiEditor::CurrentPluginData", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1CurrentPluginData.html", null ],
    [ "Grindstone::CvarArray&lt; T &gt;", "structGrindstone_1_1CvarArray.html", null ],
    [ "Grindstone::Editor::ImguiEditor::CvarBrowser", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1CvarBrowser.html", null ],
    [ "Grindstone::CvarParameter", "classGrindstone_1_1CvarParameter.html", null ],
    [ "Grindstone::CvarStorage&lt; T &gt;", "structGrindstone_1_1CvarStorage.html", null ],
    [ "Grindstone::CvarSystem", "classGrindstone_1_1CvarSystem.html", [
      [ "Grindstone::CvarSystemImpl", "classGrindstone_1_1CvarSystemImpl.html", null ]
    ] ],
    [ "TokenData::Data", "unionTokenData_1_1Data.html", null ],
    [ "Grindstone::Formats::DDS::DDS_PIXELFORMAT", "structGrindstone_1_1Formats_1_1DDS_1_1DDS__PIXELFORMAT.html", null ],
    [ "Grindstone::Formats::DDS::DDSHeader", "structGrindstone_1_1Formats_1_1DDS_1_1DDSHeader.html", null ],
    [ "Grindstone::Formats::DDS::DDSHeaderExtended", "structGrindstone_1_1Formats_1_1DDS_1_1DDSHeaderExtended.html", null ],
    [ "Grindstone::Formats::DDS::DdsParseOutput", "structGrindstone_1_1Formats_1_1DDS_1_1DdsParseOutput.html", null ],
    [ "Grindstone::Renderer::DebugPass", "classGrindstone_1_1Renderer_1_1DebugPass.html", null ],
    [ "DebugUboData", "structDebugUboData.html", null ],
    [ "Grindstone::Ai::NavMeshDebugRenderer::DebugVertex", "structGrindstone_1_1Ai_1_1NavMeshDebugRenderer_1_1DebugVertex.html", null ],
    [ "Grindstone::GraphicsAPI::Framebuffer::DefaultFramebufferCreateInfo", "structGrindstone_1_1GraphicsAPI_1_1Framebuffer_1_1DefaultFramebufferCreateInfo.html", null ],
    [ "Grindstone::Reflection::DefaultResolver", "structGrindstone_1_1Reflection_1_1DefaultResolver.html", null ],
    [ "Grindstone::DeferredDeletionQueue", "classGrindstone_1_1DeferredDeletionQueue.html", null ],
    [ "Grindstone::DeletionQueue", "classGrindstone_1_1DeletionQueue.html", null ],
    [ "Grindstone::Plugins::MetaData::Dependency", "structGrindstone_1_1Plugins_1_1MetaData_1_1Dependency.html", null ],
    [ "Grindstone::Renderer::DepthOfFieldPass", "classGrindstone_1_1Renderer_1_1DepthOfFieldPass.html", null ],
    [ "DepthStencilTarget", null, [
      [ "Grindstone::GraphicsAPI::DirectX12DepthStencilTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX12DepthStencilTarget.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSet.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1DescriptorSet.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::DescriptorSet", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1DescriptorSet.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1DescriptorSetLayout.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1DescriptorSetLayout.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::DescriptorSetLayout", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1DescriptorSetLayout.html", null ]
    ] ],
    [ "DescriptorSetOutput", "structDescriptorSetOutput.html", null ],
    [ "Grindstone::DirectionalLightComponent", "structGrindstone_1_1DirectionalLightComponent.html", null ],
    [ "Grindstone::GraphicsAPI::DirectX12Descriptor", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Descriptor.html", null ],
    [ "Grindstone::GraphicsAPI::DirectX12DescriptorLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX12DescriptorLayout.html", null ],
    [ "Grindstone::Events::Dispatcher", "classGrindstone_1_1Events_1_1Dispatcher.html", null ],
    [ "Grindstone::Display", "structGrindstone_1_1Display.html", null ],
    [ "Grindstone::DisplayManager", "classGrindstone_1_1DisplayManager.html", null ],
    [ "Grindstone::Ai::NavMeshDebugRenderer::DrawCall", "structGrindstone_1_1Ai_1_1NavMeshDebugRenderer_1_1DrawCall.html", null ],
    [ "duDebugDraw", null, [
      [ "Grindstone::Ai::NavMeshDebugRenderer", "structGrindstone_1_1Ai_1_1NavMeshDebugRenderer.html", null ]
    ] ],
    [ "Grindstone::Memory::Allocators::DynamicAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator.html", null ],
    [ "Grindstone::Containers::DynamicArray&lt; T, AllocatorType &gt;", "classGrindstone_1_1Containers_1_1DynamicArray.html", null ],
    [ "Grindstone::EngineCore::EarlyCreateInfo", "structGrindstone_1_1EngineCore_1_1EarlyCreateInfo.html", null ],
    [ "Grindstone::Editor::EditorCamera", "classGrindstone_1_1Editor_1_1EditorCamera.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ConsolePanel::EditorConsoleMessage", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1ConsolePanel_1_1EditorConsoleMessage.html", null ],
    [ "ImGui::Emphasis", "structImGui_1_1Emphasis.html", null ],
    [ "Grindstone::EngineCore", "classGrindstone_1_1EngineCore.html", null ],
    [ "EngineUboStruct", "structEngineUboStruct.html", null ],
    [ "Grindstone::ECS::Entity", "classGrindstone_1_1ECS_1_1Entity.html", null ],
    [ "Grindstone.Entity", "structGrindstone_1_1Entity.html", null ],
    [ "Grindstone::Assets::AssetRegistry::Entry", "structGrindstone_1_1Assets_1_1AssetRegistry_1_1Entry.html", null ],
    [ "Grindstone::Editor::AssetRegistry::Entry", "structGrindstone_1_1Editor_1_1AssetRegistry_1_1Entry.html", null ],
    [ "EnumFlagsTraits&lt; Enum &gt;", "structEnumFlagsTraits.html", null ],
    [ "EnumFlagsTraits&lt; Grindstone::GraphicsAPI::BufferUsage &gt;", "structEnumFlagsTraits_3_01Grindstone_1_1GraphicsAPI_1_1BufferUsage_01_4.html", null ],
    [ "EnumFlagsTraits&lt; Grindstone::GraphicsAPI::ImageUsageFlags &gt;", "structEnumFlagsTraits_3_01Grindstone_1_1GraphicsAPI_1_1ImageUsageFlags_01_4.html", null ],
    [ "EnumTraits&lt; Enum &gt;", "structEnumTraits.html", null ],
    [ "Grindstone::EnvironmentMapComponent", "structGrindstone_1_1EnvironmentMapComponent.html", null ],
    [ "Grindstone.Math.EulerAngles", "structGrindstone_1_1Math_1_1EulerAngles.html", null ],
    [ "Grindstone::Math::ExportableQuaternion", "structGrindstone_1_1Math_1_1ExportableQuaternion.html", null ],
    [ "Grindstone::Math::ExportableVector", "structGrindstone_1_1Math_1_1ExportableVector.html", null ],
    [ "std::false_type", null, [
      [ "Grindstone::ECS::has_clone< T, std::void_t< decltype(std::declval< const T & >().Clone(std::declval< Grindstone::WorldContextSet & >(), std::declval< entt::entity >()))> >", "structGrindstone_1_1ECS_1_1has__clone_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_dd43ab67fe6f91e44f4828392a2436bc.html", null ],
      [ "Grindstone::ECS::has_clone< T, typename >", "structGrindstone_1_1ECS_1_1has__clone.html", null ]
    ] ],
    [ "FieldCountAndBufferSizeResponse", "structFieldCountAndBufferSizeResponse.html", null ],
    [ "Grindstone.HostBridge.FieldCountAndBufferSizeResponse", "structGrindstone_1_1HostBridge_1_1FieldCountAndBufferSizeResponse.html", null ],
    [ "Grindstone.HostBridge.FieldMetaData", "structGrindstone_1_1HostBridge_1_1FieldMetaData.html", null ],
    [ "Grindstone::Scripting::CSharp::FieldMetaData", "structGrindstone_1_1Scripting_1_1CSharp_1_1FieldMetaData.html", null ],
    [ "FieldMetaDataBlittable", "structFieldMetaDataBlittable.html", null ],
    [ "Grindstone::Editor::FileManager", "classGrindstone_1_1Editor_1_1FileManager.html", null ],
    [ "Float2", "structFloat2.html", null ],
    [ "Grindstone.Math.Float2", "structGrindstone_1_1Math_1_1Float2.html", null ],
    [ "Grindstone.Math.Float3", "structGrindstone_1_1Math_1_1Float3.html", null ],
    [ "Grindstone.Math.Float4", "structGrindstone_1_1Math_1_1Float4.html", null ],
    [ "Grindstone::Renderer::ForwardPass", "classGrindstone_1_1Renderer_1_1ForwardPass.html", null ],
    [ "Grindstone::GraphicsAPI::Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1Framebuffer.html", [
      [ "Grindstone::GraphicsAPI::DirectX12Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Framebuffer.html", null ],
      [ "Grindstone::GraphicsAPI::OpenGL::Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Framebuffer.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::Framebuffer", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Framebuffer.html", null ]
    ] ],
    [ "Grindstone::Memory::Allocators::DynamicAllocator::FreeHeader", "structGrindstone_1_1Memory_1_1Allocators_1_1DynamicAllocator_1_1FreeHeader.html", null ],
    [ "Grindstone::Memory::Allocators::BasePoolAllocator::FreeLink", "structGrindstone_1_1Memory_1_1Allocators_1_1BasePoolAllocator_1_1FreeLink.html", null ],
    [ "Grindstone::GameplayTag", "classGrindstone_1_1GameplayTag.html", null ],
    [ "Grindstone::Renderer::GbufferData", "structGrindstone_1_1Renderer_1_1GbufferData.html", null ],
    [ "Grindstone::Renderer::GbufferPass", "classGrindstone_1_1Renderer_1_1GbufferPass.html", null ],
    [ "Grindstone::GenericAssetReference", "structGrindstone_1_1GenericAssetReference.html", [
      [ "Grindstone::AssetReference< Grindstone::GraphicsPipelineAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::AnimationClipAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::RigAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::Audio::AudioClipAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::TextureAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::Mesh3dAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< Grindstone::ComputePipelineAsset >", "structGrindstone_1_1AssetReference.html", null ],
      [ "Grindstone::AssetReference< T >", "structGrindstone_1_1AssetReference.html", null ]
    ] ],
    [ "Grindstone::Rendering::GeometryRenderStats", "structGrindstone_1_1Rendering_1_1GeometryRenderStats.html", null ],
    [ "Grindstone::Editor::GitManager", "classGrindstone_1_1Editor_1_1GitManager.html", null ],
    [ "Grindstone::Editor::GizmoRenderer", "classGrindstone_1_1Editor_1_1GizmoRenderer.html", null ],
    [ "Grindstone::Editor::GizmoRenderer::GizmoUniformBuffer", "structGrindstone_1_1Editor_1_1GizmoRenderer_1_1GizmoUniformBuffer.html", null ],
    [ "GpuCrashTracker", "classGpuCrashTracker.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline.html", [
      [ "Grindstone::GraphicsAPI::DirectX12GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1DirectX12GraphicsPipeline.html", null ],
      [ "Grindstone::GraphicsAPI::OpenGL::GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1GraphicsPipeline.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::GraphicsPipeline", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1GraphicsPipeline.html", null ]
    ] ],
    [ "Grindstone::Formats::Pipelines::V1::GraphicsPipelineConfigurationHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1GraphicsPipelineConfigurationHeader.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::GraphicsPipelineSetHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1GraphicsPipelineSetHeader.html", null ],
    [ "GraphicsWrapper", null, [
      [ "Grindstone::GraphicsAPI::DirectX12GraphicsWrapper", "classGrindstone_1_1GraphicsAPI_1_1DirectX12GraphicsWrapper.html", null ]
    ] ],
    [ "Grindstone::Editor::GridRenderer", "classGrindstone_1_1Editor_1_1GridRenderer.html", null ],
    [ "GridUniformBuffer", "structGridUniformBuffer.html", null ],
    [ "std::hash&lt; Grindstone::GraphicsAPI::DescriptorSetLayout &gt;", "structstd_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_01_4.html", null ],
    [ "std::hash&lt; Grindstone::GraphicsAPI::DescriptorSetLayout::Binding &gt;", "structstd_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_1_1Binding_01_4.html", null ],
    [ "std::hash&lt; Grindstone::GraphicsAPI::DescriptorSetLayout::CreateInfo &gt;", "structstd_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1DescriptorSetLayout_1_1CreateInfo_01_4.html", null ],
    [ "std::std::hash&lt; Grindstone::GraphicsAPI::GraphicsPipeline::AttachmentData &gt;", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1AttachmentData_01_4.html", null ],
    [ "std::std::hash&lt; Grindstone::GraphicsAPI::GraphicsPipeline::PipelineData &gt;", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1PipelineData_01_4.html", null ],
    [ "std::std::hash&lt; Grindstone::GraphicsAPI::GraphicsPipeline::ShaderStageData &gt;", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1ShaderStageData_01_4.html", null ],
    [ "std::hash&lt; Grindstone::GraphicsAPI::PipelineLayout::CreateInfo &gt;", "structstd_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1PipelineLayout_1_1CreateInfo_01_4.html", null ],
    [ "std::hash&lt; Grindstone::GraphicsAPI::SamplerOptions &gt;", "structstd_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1SamplerOptions_01_4.html", null ],
    [ "std::std::hash&lt; Grindstone::GraphicsAPI::VertexAttributeDescription &gt;", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1VertexAttributeDescription_01_4.html", null ],
    [ "std::std::hash&lt; Grindstone::GraphicsAPI::VertexBindingDescription &gt;", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1VertexBindingDescription_01_4.html", null ],
    [ "std::std::hash&lt; Grindstone::GraphicsAPI::VertexInputLayout &gt;", "structstd_1_1std_1_1hash_3_01Grindstone_1_1GraphicsAPI_1_1VertexInputLayout_01_4.html", null ],
    [ "std::hash&lt; Grindstone::HashedString &gt;", "structstd_1_1hash_3_01Grindstone_1_1HashedString_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::BufferDescription &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1BufferDescription_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::ImageDescription &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1ImageDescription_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::MetaRect &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1MetaRect_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::MetaSize &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1MetaSize_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::MetaSize2D &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1MetaSize2D_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::RenderGraphBuilderResourceRef &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1RenderGraphBuilderResourceRef_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::TransientBufferDescription &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1TransientBufferDescription_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Renderer::TransientImageDescription &gt;", "structstd_1_1hash_3_01Grindstone_1_1Renderer_1_1TransientImageDescription_01_4.html", null ],
    [ "std::hash&lt; Grindstone::Uuid &gt;", "structstd_1_1hash_3_01Grindstone_1_1Uuid_01_4.html", null ],
    [ "Grindstone::HashedString", "classGrindstone_1_1HashedString.html", null ],
    [ "Grindstone::Hash::HashPair", "structGrindstone_1_1Hash_1_1HashPair.html", null ],
    [ "Grindstone::Assets::ArchiveContentFile::Header", "structGrindstone_1_1Assets_1_1ArchiveContentFile_1_1Header.html", null ],
    [ "Grindstone::Assets::ArchiveDirectoryFile::Header", "structGrindstone_1_1Assets_1_1ArchiveDirectoryFile_1_1Header.html", null ],
    [ "Grindstone::Formats::Animation::V1::Header", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1Header.html", null ],
    [ "Grindstone::Formats::Model::V1::Header", "structGrindstone_1_1Formats_1_1Model_1_1V1_1_1Header.html", null ],
    [ "Grindstone::Formats::Rig::V1::Header", "structGrindstone_1_1Formats_1_1Rig_1_1V1_1_1Header.html", null ],
    [ "Grindstone::Editor::ThumbnailManager::IconData", "structGrindstone_1_1Editor_1_1ThumbnailManager_1_1IconData.html", null ],
    [ "Grindstone::Editor::IEditor", "classGrindstone_1_1Editor_1_1IEditor.html", null ],
    [ "Grindstone::Plugins::IEditorInterface", "classGrindstone_1_1Plugins_1_1IEditorInterface.html", [
      [ "Grindstone::Plugins::EditorPluginInterface", "classGrindstone_1_1Plugins_1_1EditorPluginInterface.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::Image", "classGrindstone_1_1GraphicsAPI_1_1Image.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::Image", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Image.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::Image", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Image.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::ImageBarrier", "structGrindstone_1_1GraphicsAPI_1_1ImageBarrier.html", null ],
    [ "Grindstone::Renderer::ImageDescription", "structGrindstone_1_1Renderer_1_1ImageDescription.html", null ],
    [ "Grindstone::GraphicsAPI::Image::ImageRegion", "structGrindstone_1_1GraphicsAPI_1_1Image_1_1ImageRegion.html", null ],
    [ "Grindstone::GraphicsAPI::Vulkan::ImageSet", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1ImageSet.html", null ],
    [ "Grindstone::Renderer::BloomPass::ImageSet", "structGrindstone_1_1Renderer_1_1BloomPass_1_1ImageSet.html", null ],
    [ "Grindstone::GraphicsAPI::Vulkan::ImageSetNative", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1ImageSetNative.html", null ],
    [ "Grindstone::Renderer::ImageTransfer", "structGrindstone_1_1Renderer_1_1ImageTransfer.html", null ],
    [ "ImageUsageSyncInfo", "structImageUsageSyncInfo.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiEditor", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiEditor.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiInput.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiInterface", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiInterface.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ImguiRenderer", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiRenderer.html", [
      [ "Grindstone::Editor::ImguiEditor::ImguiRendererVulkan", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ImguiRendererVulkan.html", null ]
    ] ],
    [ "Grindstone::Editor::ImporterData", "structGrindstone_1_1Editor_1_1ImporterData.html", null ],
    [ "Grindstone::Importers::ImporterManager", "classGrindstone_1_1Importers_1_1ImporterManager.html", null ],
    [ "Grindstone::Editor::ImporterSettings", "structGrindstone_1_1Editor_1_1ImporterSettings.html", null ],
    [ "IndexBuffer", null, [
      [ "Grindstone::GraphicsAPI::DirectX12IndexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12IndexBuffer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::VertexInputLayoutBuilder::InlineAttribute", "structGrindstone_1_1GraphicsAPI_1_1VertexInputLayoutBuilder_1_1InlineAttribute.html", null ],
    [ "Grindstone::Editor::ImguiEditor::InspectorPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1InspectorPanel.html", null ],
    [ "InspectorState", "structInspectorState.html", null ],
    [ "Grindstone::Profiler::InstrumentationSession", "structGrindstone_1_1Profiler_1_1InstrumentationSession.html", null ],
    [ "Grindstone::Math::IntBox3D", "structGrindstone_1_1Math_1_1IntBox3D.html", null ],
    [ "Grindstone::Input::Interface", "classGrindstone_1_1Input_1_1Interface.html", [
      [ "Grindstone::Input::Manager", "classGrindstone_1_1Input_1_1Manager.html", null ]
    ] ],
    [ "Grindstone::Plugins::Interface", "classGrindstone_1_1Plugins_1_1Interface.html", null ],
    [ "Grindstone::Math::IntRect2D", "structGrindstone_1_1Math_1_1IntRect2D.html", null ],
    [ "Grindstone::Plugins::IPluginManager", "classGrindstone_1_1Plugins_1_1IPluginManager.html", [
      [ "Grindstone::Plugins::DefaultPluginManager", "classGrindstone_1_1Plugins_1_1DefaultPluginManager.html", null ],
      [ "Grindstone::Plugins::EditorPluginManager", "classGrindstone_1_1Plugins_1_1EditorPluginManager.html", null ]
    ] ],
    [ "Grindstone::Reflection::DefaultResolver::IsReflected&lt; T &gt;", "structGrindstone_1_1Reflection_1_1DefaultResolver_1_1IsReflected.html", null ],
    [ "Grindstone::ECS::ISystem", "classGrindstone_1_1ECS_1_1ISystem.html", null ],
    [ "Grindstone::Containers::BitsetEnum&lt; Enum &gt;::Iterator", "structGrindstone_1_1Containers_1_1BitsetEnum_1_1Iterator.html", null ],
    [ "Grindstone::Containers::BitsetFlags&lt; Enum &gt;::Iterator", "structGrindstone_1_1Containers_1_1BitsetFlags_1_1Iterator.html", null ],
    [ "Grindstone::AnimationClipAsset::Keyframe&lt; T &gt;", "structGrindstone_1_1AnimationClipAsset_1_1Keyframe.html", null ],
    [ "Grindstone::Formats::Animation::V1::Keyframe&lt; T &gt;", "structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1Keyframe.html", null ],
    [ "Grindstone::EngineCore::LateCreateInfo", "structGrindstone_1_1EngineCore_1_1LateCreateInfo.html", null ],
    [ "Grindstone::Physics::Layer", "structGrindstone_1_1Physics_1_1Layer.html", null ],
    [ "Grindstone::Physics::LayerMask", "structGrindstone_1_1Physics_1_1LayerMask.html", null ],
    [ "Grindstone::Renderer::LightingPass", "classGrindstone_1_1Renderer_1_1LightingPass.html", null ],
    [ "Grindstone::Renderer::LightingPassReturnData", "structGrindstone_1_1Renderer_1_1LightingPassReturnData.html", null ],
    [ "ImGui::Line", "structImGui_1_1Line.html", null ],
    [ "Grindstone::Memory::Allocators::LinearAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1LinearAllocator.html", null ],
    [ "ImGui::Link", "structImGui_1_1Link.html", null ],
    [ "Grindstone.Logger", "classGrindstone_1_1Logger.html", null ],
    [ "Grindstone::Logger::LoggerState", "structGrindstone_1_1Logger_1_1LoggerState.html", null ],
    [ "Grindstone::Editor::Manager", "classGrindstone_1_1Editor_1_1Manager.html", null ],
    [ "Grindstone::Profiler::Manager", "classGrindstone_1_1Profiler_1_1Manager.html", null ],
    [ "Grindstone::Plugins::ManifestData", "structGrindstone_1_1Plugins_1_1ManifestData.html", null ],
    [ "ImGui::MarkdownConfig", "structImGui_1_1MarkdownConfig.html", null ],
    [ "ImGui::MarkdownFormatInfo", "structImGui_1_1MarkdownFormatInfo.html", null ],
    [ "ImGui::MarkdownHeadingFormat", "structImGui_1_1MarkdownHeadingFormat.html", null ],
    [ "ImGui::MarkdownImageData", "structImGui_1_1MarkdownImageData.html", null ],
    [ "ImGui::MarkdownLinkCallbackData", "structImGui_1_1MarkdownLinkCallbackData.html", null ],
    [ "ImGui::MarkdownTooltipCallbackData", "structImGui_1_1MarkdownTooltipCallbackData.html", null ],
    [ "Grindstone::Editor::ImguiEditor::MaterialInspector", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialInspector.html", null ],
    [ "Grindstone::Editor::ImguiEditor::MaterialParameter", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialParameter.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::MaterialParameter", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1MaterialParameter.html", null ],
    [ "ParseTree::MaterialParameter", "structParseTree_1_1MaterialParameter.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::MaterialResource", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1MaterialResource.html", null ],
    [ "Grindstone::Editor::ImguiEditor::MaterialInspector::MaterialUniformBuffer::Member", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1MaterialInspector_1_1MaterialUniformBuffer_1_1Member.html", null ],
    [ "Grindstone::Reflection::TypeDescriptor_Struct::Member", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct_1_1Member.html", null ],
    [ "MemoryDumpData", "structMemoryDumpData.html", null ],
    [ "MemoryDumpRow", "structMemoryDumpRow.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Menubar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Menubar.html", null ],
    [ "Grindstone::MeshComponent", "structGrindstone_1_1MeshComponent.html", null ],
    [ "Grindstone::MeshRendererComponent", "structGrindstone_1_1MeshRendererComponent.html", null ],
    [ "Grindstone::GraphicsPipelineAsset::MetaData", "structGrindstone_1_1GraphicsPipelineAsset_1_1MetaData.html", null ],
    [ "Grindstone::Plugins::MetaData", "structGrindstone_1_1Plugins_1_1MetaData.html", null ],
    [ "Grindstone::Editor::MetaFile", "classGrindstone_1_1Editor_1_1MetaFile.html", null ],
    [ "Grindstone::Renderer::MetaRect", "structGrindstone_1_1Renderer_1_1MetaRect.html", null ],
    [ "Grindstone::Renderer::MetaSize", "structGrindstone_1_1Renderer_1_1MetaSize.html", null ],
    [ "Grindstone::Renderer::MetaSize2D", "structGrindstone_1_1Renderer_1_1MetaSize2D.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptClass::Methods", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass_1_1Methods.html", null ],
    [ "ModelImporter", "classModelImporter.html", null ],
    [ "ModelImporterRendererState", "structModelImporterRendererState.html", null ],
    [ "Grindstone::Editor::FileManager::MountPoint", "structGrindstone_1_1Editor_1_1FileManager_1_1MountPoint.html", null ],
    [ "MousePickMatrixBuffer", "structMousePickMatrixBuffer.html", null ],
    [ "MousePickResponseBuffer", "structMousePickResponseBuffer.html", null ],
    [ "Grindstone::MulticastObservable&lt; Args &gt;", "classGrindstone_1_1MulticastObservable.html", null ],
    [ "Grindstone::Ai::NavAgentComponent", "structGrindstone_1_1Ai_1_1NavAgentComponent.html", null ],
    [ "Grindstone::Ai::NavAgentType", "structGrindstone_1_1Ai_1_1NavAgentType.html", null ],
    [ "Grindstone.Ai.NavmeshAgentComponent", "classGrindstone_1_1Ai_1_1NavmeshAgentComponent.html", null ],
    [ "Grindstone::Ai::NavMeshComponent", "structGrindstone_1_1Ai_1_1NavMeshComponent.html", null ],
    [ "Grindstone::Ai::NavMeshLocomotionData", "structGrindstone_1_1Ai_1_1NavMeshLocomotionData.html", null ],
    [ "NavMeshSetHeader", "structNavMeshSetHeader.html", null ],
    [ "NavMeshTileHeader", "structNavMeshTileHeader.html", null ],
    [ "Grindstone::Editor::ImguiEditor::NewComponentInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1NewComponentInput.html", null ],
    [ "Grindstone::Renderer::OBB", "structGrindstone_1_1Renderer_1_1OBB.html", null ],
    [ "JPH::ObjectLayerPairFilter", null, [
      [ "Grindstone::Physics::ObjectLayerPairFilterImpl", "classGrindstone_1_1Physics_1_1ObjectLayerPairFilterImpl.html", null ]
    ] ],
    [ "JPH::ObjectVsBroadPhaseLayerFilter", null, [
      [ "Grindstone::Physics::ObjectVsBroadPhaseLayerFilterImpl", "classGrindstone_1_1Physics_1_1ObjectVsBroadPhaseLayerFilterImpl.html", null ]
    ] ],
    [ "OffMeshConnectionDataArrays", "structOffMeshConnectionDataArrays.html", null ],
    [ "Grindstone::Ai::OffNavMeshConnectionComponent", "structGrindstone_1_1Ai_1_1OffNavMeshConnectionComponent.html", null ],
    [ "OpenGLFormatMapping", "structOpenGLFormatMapping.html", null ],
    [ "Grindstone::GraphicsAPI::OpenGLFormats", "structGrindstone_1_1GraphicsAPI_1_1OpenGLFormats.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::PageData", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PageData.html", null ],
    [ "Grindstone::PipelineAssetMetaData::Parameter", "structGrindstone_1_1PipelineAssetMetaData_1_1Parameter.html", null ],
    [ "Grindstone::PipelineAssetMetaData::ParameterValue", "unionGrindstone_1_1PipelineAssetMetaData_1_1ParameterValue.html", null ],
    [ "Grindstone::ParentComponent", "structGrindstone_1_1ParentComponent.html", null ],
    [ "ParseTree::ParentData", "structParseTree_1_1ParentData.html", null ],
    [ "ParseContext", "structParseContext.html", null ],
    [ "ParseTree", "structParseTree.html", null ],
    [ "CompilationArtifactsGraphics::Pass", "structCompilationArtifactsGraphics_1_1Pass.html", null ],
    [ "Grindstone::GraphicsPipelineAsset::Pass", "structGrindstone_1_1GraphicsPipelineAsset_1_1Pass.html", null ],
    [ "ParseTree::Pass", "structParseTree_1_1Pass.html", null ],
    [ "ResolvedStateTree::Pass", "structResolvedStateTree_1_1Pass.html", null ],
    [ "Grindstone::Renderer::PassBufferDesc", "structGrindstone_1_1Renderer_1_1PassBufferDesc.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::PassDescriptorBinding", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorBinding.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::PassDescriptorSet", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorSet.html", null ],
    [ "Grindstone::Renderer::PassImageDesc", "structGrindstone_1_1Renderer_1_1PassImageDesc.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::PassPipelineAttachmentHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineAttachmentHeader.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::PassPipelineHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineHeader.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::PassPipelineShaderStageHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineShaderStageHeader.html", null ],
    [ "Grindstone::Physics::PhysicsSettings", "structGrindstone_1_1Physics_1_1PhysicsSettings.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline::PipelineData", "structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1PipelineData.html", null ],
    [ "Grindstone::GraphicsAPI::PipelineLayout", "classGrindstone_1_1GraphicsAPI_1_1PipelineLayout.html", [
      [ "Grindstone::GraphicsAPI::Vulkan::PipelineLayout", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1PipelineLayout.html", null ]
    ] ],
    [ "PipelineOutput", "structPipelineOutput.html", null ],
    [ "ParseTree::PipelineSet", "structParseTree_1_1PipelineSet.html", null ],
    [ "ResolvedStateTree::PipelineSet", "structResolvedStateTree_1_1PipelineSet.html", null ],
    [ "PipelineSetConditioner", "classPipelineSetConditioner.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::PipelineSetFileHeader", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PipelineSetFileHeader.html", null ],
    [ "Grindstone::BuildSettings::PluginBuildSettings", "classGrindstone_1_1BuildSettings_1_1PluginBuildSettings.html", null ],
    [ "Grindstone::Editor::ImguiEditor::PluginListElement", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1PluginListElement.html", null ],
    [ "Grindstone::Editor::ImguiEditor::PluginsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1PluginsWindow.html", null ],
    [ "Grindstone::PointLightComponent", "structGrindstone_1_1PointLightComponent.html", null ],
    [ "Grindstone::Renderer::TransientResourceManager::PooledBuffer", "structGrindstone_1_1Renderer_1_1TransientResourceManager_1_1PooledBuffer.html", null ],
    [ "Grindstone::Renderer::TransientResourceManager::PooledImage", "structGrindstone_1_1Renderer_1_1TransientResourceManager_1_1PooledImage.html", null ],
    [ "Grindstone::Renderer::PostProcessSettings", "structGrindstone_1_1Renderer_1_1PostProcessSettings.html", null ],
    [ "Grindstone.Math.Quaternion", "structGrindstone_1_1Math_1_1Quaternion.html", null ],
    [ "Grindstone::GraphicsAPI::Vulkan::QueueFamilyIndices", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1QueueFamilyIndices.html", null ],
    [ "rcContext", null, [
      [ "Grindstone::Ai::GrindstoneRecastContext", "classGrindstone_1_1Ai_1_1GrindstoneRecastContext.html", null ]
    ] ],
    [ "Grindstone.Rect", "structGrindstone_1_1Rect.html", null ],
    [ "Grindstone::Math::Rect2D", "structGrindstone_1_1Math_1_1Rect2D.html", null ],
    [ "ReflectedBlock", "structReflectedBlock.html", null ],
    [ "ReflectedBlockVariable", "structReflectedBlockVariable.html", null ],
    [ "ReflectedBufferBinding", "structReflectedBufferBinding.html", null ],
    [ "Grindstone::Renderer::RenderableBufferPair", "structGrindstone_1_1Renderer_1_1RenderableBufferPair.html", null ],
    [ "Grindstone::GraphicsAPI::RenderAttachment", "structGrindstone_1_1GraphicsAPI_1_1RenderAttachment.html", null ],
    [ "Grindstone::Renderer::RenderGraph", "classGrindstone_1_1Renderer_1_1RenderGraph.html", null ],
    [ "Grindstone::Renderer::RenderGraphBuilder", "classGrindstone_1_1Renderer_1_1RenderGraphBuilder.html", null ],
    [ "Grindstone::Renderer::RenderGraphBuilderPass", "classGrindstone_1_1Renderer_1_1RenderGraphBuilderPass.html", [
      [ "Grindstone::Renderer::PipelineRenderGraphBuilderPass", "classGrindstone_1_1Renderer_1_1PipelineRenderGraphBuilderPass.html", [
        [ "Grindstone::Renderer::ComputeRenderGraphBuilderPassBase", "classGrindstone_1_1Renderer_1_1ComputeRenderGraphBuilderPassBase.html", [
          [ "Grindstone::Renderer::ComputeRenderGraphBuilderPass< ReturnType >", "classGrindstone_1_1Renderer_1_1ComputeRenderGraphBuilderPass.html", null ]
        ] ],
        [ "Grindstone::Renderer::GraphicsRenderGraphBuilderPassBase", "classGrindstone_1_1Renderer_1_1GraphicsRenderGraphBuilderPassBase.html", [
          [ "Grindstone::Renderer::GraphicsRenderGraphBuilderPass< ReturnType >", "classGrindstone_1_1Renderer_1_1GraphicsRenderGraphBuilderPass.html", null ]
        ] ]
      ] ],
      [ "Grindstone::Renderer::PresentRenderGraphBuilderPass", "classGrindstone_1_1Renderer_1_1PresentRenderGraphBuilderPass.html", null ],
      [ "Grindstone::Renderer::TransferRenderGraphBuilderPass", "classGrindstone_1_1Renderer_1_1TransferRenderGraphBuilderPass.html", null ]
    ] ],
    [ "Grindstone::Renderer::RenderGraphBuilderResourceRef", "structGrindstone_1_1Renderer_1_1RenderGraphBuilderResourceRef.html", null ],
    [ "Grindstone::Renderer::RenderGraphContext", "structGrindstone_1_1Renderer_1_1RenderGraphContext.html", null ],
    [ "Grindstone::Renderer::RenderGraphFrameResources", "structGrindstone_1_1Renderer_1_1RenderGraphFrameResources.html", null ],
    [ "Grindstone::Renderer::RenderGraphPass", "classGrindstone_1_1Renderer_1_1RenderGraphPass.html", [
      [ "Grindstone::Renderer::PipelineRenderGraphPass", "classGrindstone_1_1Renderer_1_1PipelineRenderGraphPass.html", [
        [ "Grindstone::Renderer::ComputeRenderGraphPassBase", "classGrindstone_1_1Renderer_1_1ComputeRenderGraphPassBase.html", [
          [ "Grindstone::Renderer::ComputeRenderGraphPass< ReturnType >", "classGrindstone_1_1Renderer_1_1ComputeRenderGraphPass.html", null ]
        ] ],
        [ "Grindstone::Renderer::GraphicsRenderGraphPassBase", "classGrindstone_1_1Renderer_1_1GraphicsRenderGraphPassBase.html", [
          [ "Grindstone::Renderer::GraphicsRenderGraphPass< ReturnType >", "classGrindstone_1_1Renderer_1_1GraphicsRenderGraphPass.html", null ]
        ] ]
      ] ],
      [ "Grindstone::Renderer::PresentRenderGraphPass", "classGrindstone_1_1Renderer_1_1PresentRenderGraphPass.html", null ],
      [ "Grindstone::Renderer::TransferRenderGraphPass", "classGrindstone_1_1Renderer_1_1TransferRenderGraphPass.html", null ]
    ] ],
    [ "Grindstone::Renderer::RenderGraphResourceRef", "structGrindstone_1_1Renderer_1_1RenderGraphResourceRef.html", null ],
    [ "Grindstone::BaseRenderer::RenderMode", "structGrindstone_1_1BaseRenderer_1_1RenderMode.html", null ],
    [ "Grindstone::GraphicsAPI::RenderPass", "classGrindstone_1_1GraphicsAPI_1_1RenderPass.html", [
      [ "Grindstone::GraphicsAPI::DirectX12RenderPass", "classGrindstone_1_1GraphicsAPI_1_1DirectX12RenderPass.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::RenderPass", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1RenderPass.html", null ]
    ] ],
    [ "Grindstone::RenderPassRegistry", "classGrindstone_1_1RenderPassRegistry.html", null ],
    [ "Grindstone::Rendering::RenderPathBase", "classGrindstone_1_1Rendering_1_1RenderPathBase.html", null ],
    [ "ParseTree::RenderState", "structParseTree_1_1RenderState.html", null ],
    [ "RenderTarget", null, [
      [ "Grindstone::GraphicsAPI::DirectX12RenderTarget", "classGrindstone_1_1GraphicsAPI_1_1DirectX12RenderTarget.html", null ]
    ] ],
    [ "RenderTask", "structRenderTask.html", null ],
    [ "Grindstone::Rendering::RenderViewData", "structGrindstone_1_1Rendering_1_1RenderViewData.html", null ],
    [ "ResolveContext", "structResolveContext.html", null ],
    [ "ResolvedStateTree", "structResolvedStateTree.html", null ],
    [ "Grindstone::ResourcePipeline", "classGrindstone_1_1ResourcePipeline.html", null ],
    [ "Grindstone::PipelineAssetMetaData::ResourceSlot", "structGrindstone_1_1PipelineAssetMetaData_1_1ResourceSlot.html", null ],
    [ "Grindstone::Profiler::Result", "structGrindstone_1_1Profiler_1_1Result.html", null ],
    [ "Grindstone::Containers::ReverseArrayIterator&lt; T &gt;", "structGrindstone_1_1Containers_1_1ReverseArrayIterator.html", null ],
    [ "Grindstone::Containers::ReverseRange&lt; T &gt;", "classGrindstone_1_1Containers_1_1ReverseRange.html", null ],
    [ "Grindstone::Containers::ReverseRangeTemp&lt; T &gt;", "classGrindstone_1_1Containers_1_1ReverseRangeTemp.html", null ],
    [ "Grindstone::Physics::RigidBodyComponent", "structGrindstone_1_1Physics_1_1RigidBodyComponent.html", null ],
    [ "Grindstone.Physics.Jolt.RigidbodyComponent", "classGrindstone_1_1Physics_1_1Jolt_1_1RigidbodyComponent.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Sampler", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Sampler.html", null ],
    [ "Grindstone::GraphicsAPI::Sampler", "classGrindstone_1_1GraphicsAPI_1_1Sampler.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::Sampler", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Sampler.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::Sampler", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Sampler.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::SamplerOptions", "structGrindstone_1_1GraphicsAPI_1_1SamplerOptions.html", null ],
    [ "ScanContext", "structScanContext.html", null ],
    [ "Grindstone.Scene", "structGrindstone_1_1Scene.html", null ],
    [ "Grindstone::SceneManagement::Scene", "classGrindstone_1_1SceneManagement_1_1Scene.html", null ],
    [ "Grindstone::BuildSettings::SceneBuildSettings", "classGrindstone_1_1BuildSettings_1_1SceneBuildSettings.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::Build::SceneData", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build_1_1SceneData.html", null ],
    [ "Grindstone::Editor::ImguiEditor::SceneHeirarchyPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SceneHeirarchyPanel.html", null ],
    [ "Grindstone::SceneManagement::SceneLoaderJson", "classGrindstone_1_1SceneManagement_1_1SceneLoaderJson.html", null ],
    [ "Grindstone::SceneManagement::SceneManager", "classGrindstone_1_1SceneManagement_1_1SceneManager.html", null ],
    [ "Grindstone::SceneManagement::SceneWriterJson", "classGrindstone_1_1SceneManagement_1_1SceneWriterJson.html", null ],
    [ "Grindstone::Renderer::ScreenSpaceAmbientOcclusionPass", "classGrindstone_1_1Renderer_1_1ScreenSpaceAmbientOcclusionPass.html", null ],
    [ "Grindstone::Renderer::ScreenSpaceReflectionsPass", "classGrindstone_1_1Renderer_1_1ScreenSpaceReflectionsPass.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptClass", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptComponent", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptComponent.html", null ],
    [ "Grindstone::Scripting::CSharp::ScriptField", "structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptField.html", null ],
    [ "Grindstone::Editor::Selection", "classGrindstone_1_1Editor_1_1Selection.html", null ],
    [ "Grindstone::Editor::ImguiEditor::Settings::SettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1SettingsWindow.html", [
      [ "Grindstone::Editor::ImguiEditor::Settings::ProjectSettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1ProjectSettingsWindow.html", null ],
      [ "Grindstone::Editor::ImguiEditor::Settings::UserSettingsWindow", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1UserSettingsWindow.html", null ]
    ] ],
    [ "ParseTree::ShaderBlock", "structParseTree_1_1ShaderBlock.html", null ],
    [ "ShaderDatabase", "classShaderDatabase.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::ShaderReflectDescriptorBinding", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorBinding.html", null ],
    [ "ShaderReflectDescriptorBinding", "structShaderReflectDescriptorBinding.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::ShaderReflectDescriptorSet", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorSet.html", null ],
    [ "ShaderReflectDescriptorSet", "structShaderReflectDescriptorSet.html", null ],
    [ "Grindstone::Formats::Pipelines::V1::ShaderReflectInputVariables", "structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectInputVariables.html", null ],
    [ "Grindstone::GraphicsAPI::GraphicsPipeline::ShaderStageData", "structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1ShaderStageData.html", null ],
    [ "Grindstone::DirectionalLightComponent::ShadowData", "structGrindstone_1_1DirectionalLightComponent_1_1ShadowData.html", null ],
    [ "Grindstone::PointLightComponent::ShadowData", "structGrindstone_1_1PointLightComponent_1_1ShadowData.html", null ],
    [ "Grindstone::Renderer::ShadowPass", "classGrindstone_1_1Renderer_1_1ShadowPass.html", null ],
    [ "Grindstone::Renderer::ShadowPassReturnData", "structGrindstone_1_1Renderer_1_1ShadowPassReturnData.html", null ],
    [ "Grindstone::Editor::GizmoRenderer::ShapeMetaData", "structGrindstone_1_1Editor_1_1GizmoRenderer_1_1ShapeMetaData.html", null ],
    [ "Grindstone::SharedPtr&lt; T &gt;", "classGrindstone_1_1SharedPtr.html", null ],
    [ "Grindstone::SharedPtr&lt; T &gt;::SharedPtrRefCounter", "structGrindstone_1_1SharedPtr_1_1SharedPtrRefCounter.html", null ],
    [ "Grindstone::SinglecastObservable&lt; Args &gt;", "classGrindstone_1_1SinglecastObservable.html", null ],
    [ "Grindstone::SkeletalMeshComponent", "structGrindstone_1_1SkeletalMeshComponent.html", null ],
    [ "Grindstone::Renderer::SkinningPass", "classGrindstone_1_1Renderer_1_1SkinningPass.html", null ],
    [ "Grindstone::Renderer::SmaaPass", "classGrindstone_1_1Renderer_1_1SmaaPass.html", null ],
    [ "Grindstone.SmartComponent", "classGrindstone_1_1SmartComponent.html", null ],
    [ "Grindstone::Audio::Source", "classGrindstone_1_1Audio_1_1Source.html", null ],
    [ "SourceSubmesh", "structSourceSubmesh.html", null ],
    [ "Grindstone::Containers::Span&lt; T &gt;", "classGrindstone_1_1Containers_1_1Span.html", null ],
    [ "Grindstone::SpotLightComponent", "structGrindstone_1_1SpotLightComponent.html", null ],
    [ "SsaoUboStruct", "structSsaoUboStruct.html", null ],
    [ "Grindstone::Memory::Allocators::StackAllocator", "classGrindstone_1_1Memory_1_1Allocators_1_1StackAllocator.html", null ],
    [ "StageCompilationArtifacts", "structStageCompilationArtifacts.html", null ],
    [ "Grindstone::Editor::Importers::StandardMaterialCreateInfo", "structGrindstone_1_1Editor_1_1Importers_1_1StandardMaterialCreateInfo.html", null ],
    [ "Grindstone::Editor::ImguiEditor::StatsPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatsPanel.html", null ],
    [ "Grindstone::Editor::ImguiEditor::StatusBar", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatusBar.html", null ],
    [ "Grindstone::Editor::ImguiEditor::AssetBrowserPanel::AssetBrowserItem::Subasset", "structGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetBrowserPanel_1_1AssetBrowserItem_1_1Subasset.html", null ],
    [ "Grindstone::Editor::MetaFile::Subasset", "structGrindstone_1_1Editor_1_1MetaFile_1_1Subasset.html", null ],
    [ "Grindstone::Mesh3dAsset::Submesh", "structGrindstone_1_1Mesh3dAsset_1_1Submesh.html", null ],
    [ "Grindstone::Editor::ImguiEditor::SuggestedInput", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SuggestedInput.html", null ],
    [ "Grindstone::GraphicsAPI::Vulkan::SwapChainSupportDetails", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1SwapChainSupportDetails.html", null ],
    [ "Grindstone::Editor::ImguiEditor::SystemPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1SystemPanel.html", null ],
    [ "Grindstone::ECS::SystemRegistrar", "classGrindstone_1_1ECS_1_1SystemRegistrar.html", null ],
    [ "Grindstone.SystemRegistrar", "classGrindstone_1_1SystemRegistrar.html", null ],
    [ "Grindstone::TagComponent", "structGrindstone_1_1TagComponent.html", null ],
    [ "Grindstone::Editor::Task", "structGrindstone_1_1Editor_1_1Task.html", null ],
    [ "Grindstone::Editor::ImguiEditor::TaskPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1TaskPanel.html", null ],
    [ "Grindstone::Editor::TaskSystem", "classGrindstone_1_1Editor_1_1TaskSystem.html", null ],
    [ "ImGui::TextBlock", "structImGui_1_1TextBlock.html", null ],
    [ "ImGui::TextRegion", "structImGui_1_1TextRegion.html", null ],
    [ "Texture", null, [
      [ "Grindstone::GraphicsAPI::DirectX12Texture", "classGrindstone_1_1GraphicsAPI_1_1DirectX12Texture.html", null ]
    ] ],
    [ "TextureBinding", null, [
      [ "Grindstone::GraphicsAPI::DirectX12TextureBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX12TextureBinding.html", null ]
    ] ],
    [ "TextureBindingLayout", null, [
      [ "Grindstone::GraphicsAPI::DirectX12TextureBindingLayout", "classGrindstone_1_1GraphicsAPI_1_1DirectX12TextureBindingLayout.html", null ]
    ] ],
    [ "TextureImporter", "classTextureImporter.html", null ],
    [ "Grindstone::Editor::ThumbnailManager", "classGrindstone_1_1Editor_1_1ThumbnailManager.html", null ],
    [ "Grindstone::Profiler::Timer", "classGrindstone_1_1Profiler_1_1Timer.html", null ],
    [ "TokenData", "classTokenData.html", null ],
    [ "Grindstone::Renderer::TonemapPass", "classGrindstone_1_1Renderer_1_1TonemapPass.html", null ],
    [ "Grindstone::Renderer::TonemapPassReturnData", "structGrindstone_1_1Renderer_1_1TonemapPassReturnData.html", null ],
    [ "Grindstone::Editor::ImguiEditor::TracingPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1TracingPanel.html", null ],
    [ "Grindstone::TransformComponent", "structGrindstone_1_1TransformComponent.html", null ],
    [ "Grindstone::Renderer::TransientBufferData", "structGrindstone_1_1Renderer_1_1TransientBufferData.html", null ],
    [ "Grindstone::Renderer::TransientBufferDescription", "structGrindstone_1_1Renderer_1_1TransientBufferDescription.html", null ],
    [ "Grindstone::Renderer::TransientBufferKey", "structGrindstone_1_1Renderer_1_1TransientBufferKey.html", null ],
    [ "Grindstone::Renderer::TransientImageData", "structGrindstone_1_1Renderer_1_1TransientImageData.html", null ],
    [ "Grindstone::Renderer::TransientImageDescription", "structGrindstone_1_1Renderer_1_1TransientImageDescription.html", null ],
    [ "Grindstone::Renderer::TransientImageKey", "structGrindstone_1_1Renderer_1_1TransientImageKey.html", null ],
    [ "Grindstone::Renderer::TransientResourceManager", "classGrindstone_1_1Renderer_1_1TransientResourceManager.html", null ],
    [ "Grindstone::Renderer::TransientResourceUnion", "unionGrindstone_1_1Renderer_1_1TransientResourceUnion.html", null ],
    [ "std::true_type", null, [
      [ "Grindstone::ECS::has_clone< T, std::void_t< decltype(std::declval< const T & >().Clone(std::declval< Grindstone::WorldContextSet & >(), std::declval< entt::entity >()))> >", "structGrindstone_1_1ECS_1_1has__clone_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_dd43ab67fe6f91e44f4828392a2436bc.html", null ]
    ] ],
    [ "Grindstone::Reflection::TypeDescriptor", "structGrindstone_1_1Reflection_1_1TypeDescriptor.html", [
      [ "Grindstone::Reflection::TypeDescriptor_AssetReference", "structGrindstone_1_1Reflection_1_1TypeDescriptor__AssetReference.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Bool", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Bool.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Double4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Entity", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Entity.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_FixedArray", "structGrindstone_1_1Reflection_1_1TypeDescriptor__FixedArray.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Float4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int16", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int16.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int32", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int32.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int64", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int64.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Int8", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int8.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_PhysicsLayer", "structGrindstone_1_1Reflection_1_1TypeDescriptor__PhysicsLayer.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_PhysicsLayerMask", "structGrindstone_1_1Reflection_1_1TypeDescriptor__PhysicsLayerMask.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Quat", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Quat.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_StdString", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdString.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_StdVector", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdVector.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Struct", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint16", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint16.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint2.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint3.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint32", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint32.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint4.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint64", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint64.html", null ],
      [ "Grindstone::Reflection::TypeDescriptor_Uint8", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint8.html", null ]
    ] ],
    [ "Grindstone::Reflection::TypeResolver&lt; T &gt;", "structGrindstone_1_1Reflection_1_1TypeResolver.html", null ],
    [ "Grindstone::Reflection::TypeResolver&lt; Grindstone::AssetReference&lt; T &gt; &gt;", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01Grindstone_1_1AssetReference_3_01T_01_4_01_4.html", null ],
    [ "Grindstone::Reflection::TypeResolver&lt; std::vector&lt; T &gt; &gt;", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "Grindstone::Reflection::TypeResolver&lt; T[N]&gt;", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01T_0fN_0e_4.html", null ],
    [ "UniformBuffer", null, [
      [ "Grindstone::GraphicsAPI::DirectX12UniformBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12UniformBuffer.html", null ]
    ] ],
    [ "UniformBufferBinding", null, [
      [ "Grindstone::GraphicsAPI::DirectX12UniformBufferBinding", "classGrindstone_1_1GraphicsAPI_1_1DirectX12UniformBufferBinding.html", null ]
    ] ],
    [ "Grindstone::DirectionalLightComponent::UniformStruct", "structGrindstone_1_1DirectionalLightComponent_1_1UniformStruct.html", null ],
    [ "Grindstone::PointLightComponent::UniformStruct", "structGrindstone_1_1PointLightComponent_1_1UniformStruct.html", null ],
    [ "Grindstone::SpotLightComponent::UniformStruct", "structGrindstone_1_1SpotLightComponent_1_1UniformStruct.html", null ],
    [ "Grindstone::UniquePtr&lt; T &gt;", "classGrindstone_1_1UniquePtr.html", null ],
    [ "Grindstone::Uuid", "classGrindstone_1_1Uuid.html", null ],
    [ "Grindstone::Editor::ImporterSettings::Value", "structGrindstone_1_1Editor_1_1ImporterSettings_1_1Value.html", null ],
    [ "ModelImporter::OutputMesh::VertexArray", "structModelImporter_1_1OutputMesh_1_1VertexArray.html", null ],
    [ "Grindstone::GraphicsAPI::VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1VertexArrayObject.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1VertexArrayObject.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::VertexArrayObject", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1VertexArrayObject.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::VertexAttributeDescription", "structGrindstone_1_1GraphicsAPI_1_1VertexAttributeDescription.html", null ],
    [ "Grindstone::GraphicsAPI::VertexBindingDescription", "structGrindstone_1_1GraphicsAPI_1_1VertexBindingDescription.html", null ],
    [ "VertexBuffer", null, [
      [ "Grindstone::GraphicsAPI::DirectX12VertexBuffer", "classGrindstone_1_1GraphicsAPI_1_1DirectX12VertexBuffer.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::VertexInputLayout", "structGrindstone_1_1GraphicsAPI_1_1VertexInputLayout.html", null ],
    [ "Grindstone::GraphicsAPI::VertexInputLayoutBuilder", "structGrindstone_1_1GraphicsAPI_1_1VertexInputLayoutBuilder.html", null ],
    [ "Grindstone::Editor::ImguiEditor::ViewportPanel", "classGrindstone_1_1Editor_1_1ImguiEditor_1_1ViewportPanel.html", null ],
    [ "Grindstone::Window", "classGrindstone_1_1Window.html", [
      [ "Grindstone::GlfwWindow", "classGrindstone_1_1GlfwWindow.html", null ],
      [ "Grindstone::Win32Window", "classGrindstone_1_1Win32Window.html", null ],
      [ "Grindstone::X11Window", "classGrindstone_1_1X11Window.html", null ]
    ] ],
    [ "Grindstone::GraphicsAPI::Vulkan::WindowBindingDataNative", "structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1WindowBindingDataNative.html", null ],
    [ "Grindstone::GraphicsAPI::WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1WindowGraphicsBinding.html", [
      [ "Grindstone::GraphicsAPI::OpenGL::WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1WindowGraphicsBinding.html", null ],
      [ "Grindstone::GraphicsAPI::Vulkan::WindowGraphicsBinding", "classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1WindowGraphicsBinding.html", null ]
    ] ],
    [ "Grindstone::WindowManager", "classGrindstone_1_1WindowManager.html", null ],
    [ "Grindstone::WorldContext", "classGrindstone_1_1WorldContext.html", [
      [ "Grindstone::Ai::NavMeshWorldContext", "classGrindstone_1_1Ai_1_1NavMeshWorldContext.html", null ],
      [ "Grindstone::Physics::WorldContext", "classGrindstone_1_1Physics_1_1WorldContext.html", null ],
      [ "Grindstone::Physics::WorldContext", "classGrindstone_1_1Physics_1_1WorldContext.html", null ],
      [ "Grindstone::Rendering::RenderGraphWorldContext", "classGrindstone_1_1Rendering_1_1RenderGraphWorldContext.html", null ]
    ] ],
    [ "Grindstone::WorldContextManager", "classGrindstone_1_1WorldContextManager.html", null ],
    [ "Grindstone::WorldContextSet", "classGrindstone_1_1WorldContextSet.html", null ],
    [ "Writer", "structWriter.html", null ]
];