var namespaceGrindstone_1_1Reflection =
[
    [ "DefaultResolver", "structGrindstone_1_1Reflection_1_1DefaultResolver.html", "structGrindstone_1_1Reflection_1_1DefaultResolver" ],
    [ "TypeDescriptor", "structGrindstone_1_1Reflection_1_1TypeDescriptor.html", null ],
    [ "TypeDescriptor_AssetReference", "structGrindstone_1_1Reflection_1_1TypeDescriptor__AssetReference.html", null ],
    [ "TypeDescriptor_Bool", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Bool.html", null ],
    [ "TypeDescriptor_Double", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double.html", null ],
    [ "TypeDescriptor_Double2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double2.html", null ],
    [ "TypeDescriptor_Double3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double3.html", null ],
    [ "TypeDescriptor_Double4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Double4.html", null ],
    [ "TypeDescriptor_Entity", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Entity.html", null ],
    [ "TypeDescriptor_FixedArray", "structGrindstone_1_1Reflection_1_1TypeDescriptor__FixedArray.html", null ],
    [ "TypeDescriptor_Float", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float.html", null ],
    [ "TypeDescriptor_Float2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float2.html", null ],
    [ "TypeDescriptor_Float3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float3.html", null ],
    [ "TypeDescriptor_Float4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Float4.html", null ],
    [ "TypeDescriptor_Int16", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int16.html", null ],
    [ "TypeDescriptor_Int2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int2.html", null ],
    [ "TypeDescriptor_Int3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int3.html", null ],
    [ "TypeDescriptor_Int32", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int32.html", null ],
    [ "TypeDescriptor_Int4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int4.html", null ],
    [ "TypeDescriptor_Int64", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int64.html", null ],
    [ "TypeDescriptor_Int8", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Int8.html", null ],
    [ "TypeDescriptor_PhysicsLayer", "structGrindstone_1_1Reflection_1_1TypeDescriptor__PhysicsLayer.html", null ],
    [ "TypeDescriptor_PhysicsLayerMask", "structGrindstone_1_1Reflection_1_1TypeDescriptor__PhysicsLayerMask.html", null ],
    [ "TypeDescriptor_Quat", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Quat.html", null ],
    [ "TypeDescriptor_StdString", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdString.html", null ],
    [ "TypeDescriptor_StdVector", "structGrindstone_1_1Reflection_1_1TypeDescriptor__StdVector.html", null ],
    [ "TypeDescriptor_Struct", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct.html", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Struct" ],
    [ "TypeDescriptor_Uint16", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint16.html", null ],
    [ "TypeDescriptor_Uint2", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint2.html", null ],
    [ "TypeDescriptor_Uint3", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint3.html", null ],
    [ "TypeDescriptor_Uint32", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint32.html", null ],
    [ "TypeDescriptor_Uint4", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint4.html", null ],
    [ "TypeDescriptor_Uint64", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint64.html", null ],
    [ "TypeDescriptor_Uint8", "structGrindstone_1_1Reflection_1_1TypeDescriptor__Uint8.html", null ],
    [ "TypeResolver", "structGrindstone_1_1Reflection_1_1TypeResolver.html", null ],
    [ "TypeResolver&lt; Grindstone::AssetReference&lt; T &gt; &gt;", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01Grindstone_1_1AssetReference_3_01T_01_4_01_4.html", null ],
    [ "TypeResolver&lt; std::vector&lt; T &gt; &gt;", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "TypeResolver&lt; T[N]&gt;", "classGrindstone_1_1Reflection_1_1TypeResolver_3_01T_0fN_0e_4.html", null ]
];