var searchData=
[
  ['sampler_0',['Sampler',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1Sampler.html',1,'Grindstone::Editor::ImguiEditor::Sampler'],['../classGrindstone_1_1GraphicsAPI_1_1OpenGL_1_1Sampler.html',1,'Grindstone::GraphicsAPI::OpenGL::Sampler'],['../classGrindstone_1_1GraphicsAPI_1_1Sampler.html',1,'Grindstone::GraphicsAPI::Sampler'],['../classGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1Sampler.html',1,'Grindstone::GraphicsAPI::Vulkan::Sampler']]],
  ['sampleroptions_1',['SamplerOptions',['../structGrindstone_1_1GraphicsAPI_1_1SamplerOptions.html',1,'Grindstone::GraphicsAPI']]],
  ['samplers_2',['3. Material Resources (Textures and Samplers)',['../md_pages_2Rendering_2Materials.html#autotoc_md84',1,'']]],
  ['scalekeyframe_3',['ScaleKeyframe',['../structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1ScaleKeyframe.html',1,'Grindstone::Formats::Animation::V1']]],
  ['scancontext_4',['ScanContext',['../structScanContext.html',1,'']]],
  ['scene_5',['Scene',['../md_pages_2Rendering_2Materials.html#autotoc_md88',1,'Applying Materials in a Scene'],['../structGrindstone_1_1Scene.html',1,'Grindstone.Scene'],['../classGrindstone_1_1SceneManagement_1_1Scene.html',1,'Grindstone::SceneManagement::Scene']]],
  ['scenebuildsettings_6',['SceneBuildSettings',['../classGrindstone_1_1BuildSettings_1_1SceneBuildSettings.html',1,'Grindstone::BuildSettings']]],
  ['scenedata_7',['SceneData',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build_1_1SceneData.html',1,'Grindstone::Editor::ImguiEditor::Settings::Build']]],
  ['sceneheirarchypanel_8',['SceneHeirarchyPanel',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1SceneHeirarchyPanel.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['sceneloaderjson_9',['SceneLoaderJson',['../classGrindstone_1_1SceneManagement_1_1SceneLoaderJson.html',1,'Grindstone::SceneManagement']]],
  ['scenemanager_10',['SceneManager',['../classGrindstone_1_1SceneManagement_1_1SceneManager.html',1,'Grindstone::SceneManagement']]],
  ['scenewriterjson_11',['SceneWriterJson',['../classGrindstone_1_1SceneManagement_1_1SceneWriterJson.html',1,'Grindstone::SceneManagement']]],
  ['scriptclass_12',['ScriptClass',['../structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptClass.html',1,'Grindstone::Scripting::CSharp']]],
  ['scriptcomponent_13',['ScriptComponent',['../structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptComponent.html',1,'Grindstone::Scripting::CSharp']]],
  ['scriptfield_14',['ScriptField',['../structGrindstone_1_1Scripting_1_1CSharp_1_1ScriptField.html',1,'Grindstone::Scripting::CSharp']]],
  ['selection_15',['Selection',['../classGrindstone_1_1Editor_1_1Selection.html',1,'Grindstone::Editor']]],
  ['setdatacommand_16',['SetDataCommand',['../classGrindstone_1_1Editor_1_1SetDataCommand.html',1,'Grindstone::Editor']]],
  ['settingswindow_17',['SettingsWindow',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1SettingsWindow.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['shader_20entry_20points_18',['Shader Entry Points',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md129',1,'']]],
  ['shader_20pipeline_20system_20documentation_19',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['shader_20reference_20graphicspipelineset_20',['1. Shader Reference (GraphicsPipelineSet)',['../md_pages_2Rendering_2Materials.html#autotoc_md82',1,'']]],
  ['shaderblock_21',['ShaderBlock',['../structParseTree_1_1ShaderBlock.html',1,'ParseTree']]],
  ['shaderblock_20tt_22',['&lt;tt&gt;shaderBlock&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md144',1,'']]],
  ['shaderhlsl_20tt_23',['&lt;tt&gt;shaderHlsl&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md147',1,'']]],
  ['shaderreflectdescriptorbinding_24',['ShaderReflectDescriptorBinding',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorBinding.html',1,'Grindstone::Formats::Pipelines::V1::ShaderReflectDescriptorBinding'],['../structShaderReflectDescriptorBinding.html',1,'ShaderReflectDescriptorBinding']]],
  ['shaderreflectdescriptorset_25',['ShaderReflectDescriptorSet',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorSet.html',1,'Grindstone::Formats::Pipelines::V1::ShaderReflectDescriptorSet'],['../structShaderReflectDescriptorSet.html',1,'ShaderReflectDescriptorSet']]],
  ['shaderreflectinputvariables_26',['ShaderReflectInputVariables',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectInputVariables.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['shaders_27',['Shaders',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md143',1,'']]],
  ['shaderstagedata_28',['ShaderStageData',['../structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1ShaderStageData.html',1,'Grindstone::GraphicsAPI::GraphicsPipeline']]],
  ['shapemetadata_29',['ShapeMetaData',['../structGrindstone_1_1Editor_1_1GizmoRenderer_1_1ShapeMetaData.html',1,'Grindstone::Editor::GizmoRenderer']]],
  ['sharedptr_30',['SharedPtr',['../classGrindstone_1_1SharedPtr.html',1,'Grindstone']]],
  ['sharedptrrefcounter_31',['SharedPtrRefCounter',['../structGrindstone_1_1SharedPtr_1_1SharedPtrRefCounter.html',1,'Grindstone::SharedPtr']]],
  ['sky_20and_20transparent_20passes_32',['Unlit, Sky, and Transparent Passes',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md72',1,'']]],
  ['smartcomponent_33',['SmartComponent',['../classGrindstone_1_1SmartComponent.html',1,'Grindstone']]],
  ['solutionbuilder_34',['SolutionBuilder',['../classGrindstone_1_1Editor_1_1ScriptBuilder_1_1SolutionBuilder.html',1,'Grindstone::Editor::ScriptBuilder']]],
  ['source_35',['Source',['../classGrindstone_1_1Audio_1_1Source.html',1,'Grindstone::Audio']]],
  ['sourcesubmesh_36',['SourceSubmesh',['../structSourceSubmesh.html',1,'']]],
  ['span_37',['Span',['../classGrindstone_1_1Containers_1_1Span.html',1,'Grindstone::Containers']]],
  ['span_3c_20grindstone_3a_3abyte_20_3e_38',['Span&lt; Grindstone::Byte &gt;',['../classGrindstone_1_1Containers_1_1Span.html',1,'Grindstone::Containers']]],
  ['specificassetimporter_39',['SpecificAssetImporter',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20audioclipasset_2c_20assettype_3a_3aaudioclip_20_3e_40',['SpecificAssetImporter&lt; AudioClipAsset, AssetType::AudioClip &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20computepipelineasset_2c_20assettype_3a_3acomputepipelineset_20_3e_41',['SpecificAssetImporter&lt; ComputePipelineAsset, AssetType::ComputePipelineSet &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20graphicspipelineasset_2c_20assettype_3a_3agraphicspipelineset_20_3e_42',['SpecificAssetImporter&lt; GraphicsPipelineAsset, AssetType::GraphicsPipelineSet &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20materialasset_2c_20assettype_3a_3amaterial_20_3e_43',['SpecificAssetImporter&lt; MaterialAsset, AssetType::Material &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20mesh3dasset_2c_20assettype_3a_3amesh3d_20_3e_44',['SpecificAssetImporter&lt; Mesh3dAsset, AssetType::Mesh3d &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20textureasset_2c_20assettype_3a_3atexture_20_3e_45',['SpecificAssetImporter&lt; TextureAsset, AssetType::Texture &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specification_46',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['spherecollidercomponent_47',['SphereColliderComponent',['../structGrindstone_1_1Physics_1_1SphereColliderComponent.html',1,'Grindstone::Physics']]],
  ['spotlightcomponent_48',['SpotLightComponent',['../structGrindstone_1_1SpotLightComponent.html',1,'Grindstone']]],
  ['ssaoubostruct_49',['SsaoUboStruct',['../structSsaoUboStruct.html',1,'']]],
  ['stackallocator_50',['StackAllocator',['../classGrindstone_1_1Memory_1_1Allocators_1_1StackAllocator.html',1,'Grindstone::Memory::Allocators']]],
  ['stagecompilationartifacts_51',['StageCompilationArtifacts',['../structStageCompilationArtifacts.html',1,'']]],
  ['stages_52',['Summary of Render Stages',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md69',1,'']]],
  ['standardmaterialcreateinfo_53',['StandardMaterialCreateInfo',['../structGrindstone_1_1Editor_1_1Importers_1_1StandardMaterialCreateInfo.html',1,'Grindstone::Editor::Importers']]],
  ['statspanel_54',['StatsPanel',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatsPanel.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['statusbar_55',['StatusBar',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatusBar.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['step_201_3a_20create_20a_20custom_20asset_20type_56',['Step 1: Create a Custom Asset Type',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md6',1,'']]],
  ['step_201_3a_20create_20an_20asset_20importer_20function_57',['Step 1: Create an asset importer function',['../md_pages_2Assets_2CustomAssetEditorGuide.html#autotoc_md2',1,'']]],
  ['step_202_3a_20create_20an_20importer_20for_20it_58',['Step 2: Create an Importer for It',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md8',1,'']]],
  ['step_202_3a_20register_20the_20asset_20importer_59',['Step 2: Register the Asset Importer',['../md_pages_2Assets_2CustomAssetEditorGuide.html#autotoc_md4',1,'']]],
  ['step_203_3a_20register_20the_20asset_20type_60',['Step 3: Register the Asset Type',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md10',1,'']]],
  ['step_204_3a_20load_20and_20use_20the_20asset_61',['Step 4: Load and Use the Asset',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md12',1,'']]],
  ['storage_20for_20developers_62',['JSON-Based Storage (For Developers)',['../md_pages_2Rendering_2Materials.html#autotoc_md98',1,'']]],
  ['string_20_3a_63',['String :',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md15',1,'Access by Address (Hashed String):'],['../md_pages_2Assets_2Overview.html#autotoc_md39',1,'Access by Address (Hashed String):']]],
  ['structure_64',['Plugin Folder Structure',['../md_pages_2Plugins_2NewDesign.html#autotoc_md53',1,'']]],
  ['subasset_65',['Subasset',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetBrowserPanel_1_1AssetBrowserItem_1_1Subasset.html',1,'Grindstone::Editor::ImguiEditor::AssetBrowserPanel::AssetBrowserItem::Subasset'],['../structGrindstone_1_1Editor_1_1MetaFile_1_1Subasset.html',1,'Grindstone::Editor::MetaFile::Subasset']]],
  ['submesh_66',['Submesh',['../structGrindstone_1_1Mesh3dAsset_1_1Submesh.html',1,'Grindstone::Mesh3dAsset']]],
  ['suggestedinput_67',['SuggestedInput',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1SuggestedInput.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['summary_20of_20render_20stages_68',['Summary of Render Stages',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md69',1,'']]],
  ['supported_20assets_69',['Supported Assets',['../md_pages_2Assets_2Overview.html#autotoc_md33',1,'']]],
  ['supported_20image_20formats_70',['Supported Image Formats',['../md_pages_2Rendering_2Textures.html#autotoc_md156',1,'']]],
  ['swapchainsupportdetails_71',['SwapChainSupportDetails',['../structGrindstone_1_1GraphicsAPI_1_1Vulkan_1_1SwapChainSupportDetails.html',1,'Grindstone::GraphicsAPI::Vulkan']]],
  ['system_202_200_20specification_72',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['system_20documentation_73',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['system_20overview_74',['Grindstone Asset System Overview',['../md_pages_2Assets_2Overview.html',1,'']]],
  ['system_20roadmap_75',['Grindstone Plugin System Roadmap',['../md_pages_2Plugins_2Overview.html',1,'']]],
  ['systempanel_76',['SystemPanel',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1SystemPanel.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['systemregistrar_77',['SystemRegistrar',['../classGrindstone_1_1ECS_1_1SystemRegistrar.html',1,'Grindstone::ECS::SystemRegistrar'],['../classGrindstone_1_1SystemRegistrar.html',1,'Grindstone.SystemRegistrar']]]
];
