var searchData=
[
  ['pagedata_0',['PageData',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PageData.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['parameter_1',['Parameter',['../structGrindstone_1_1PipelineAssetMetaData_1_1Parameter.html',1,'Grindstone::PipelineAssetMetaData']]],
  ['parametervalue_2',['ParameterValue',['../unionGrindstone_1_1PipelineAssetMetaData_1_1ParameterValue.html',1,'Grindstone::PipelineAssetMetaData']]],
  ['parentcomponent_3',['ParentComponent',['../structGrindstone_1_1ParentComponent.html',1,'Grindstone']]],
  ['pass_4',['Pass',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md71',1,'Lighting Pass'],['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md70',1,'Opaque Geometry Pass'],['../structGrindstone_1_1GraphicsPipelineAsset_1_1Pass.html',1,'Grindstone::GraphicsPipelineAsset::Pass']]],
  ['pass_20tt_5',['&lt;tt&gt;pass&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md124',1,'']]],
  ['passdescriptorbinding_6',['PassDescriptorBinding',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorBinding.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passdescriptorset_7',['PassDescriptorSet',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorSet.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passes_8',['Unlit, Sky, and Transparent Passes',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md72',1,'']]],
  ['passpipelineattachmentheader_9',['PassPipelineAttachmentHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineAttachmentHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passpipelineheader_10',['PassPipelineHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passpipelineshaderstageheader_11',['PassPipelineShaderStageHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineShaderStageHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['patterns_12',['Usage Patterns',['../md_pages_2Assets_2Overview.html#autotoc_md35',1,'']]],
  ['pipeline_13',['Pipeline',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md149',1,'Example 1: Graphics Pipeline'],['../md_pages_2Rendering_2PipelineSets.html#autotoc_md151',1,'Example 2: Compute Pipeline']]],
  ['pipeline_20configuration_20keywords_14',['Pipeline Configuration Keywords',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md128',1,'']]],
  ['pipeline_20system_20documentation_15',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['pipelinedata_16',['PipelineData',['../structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1PipelineData.html',1,'Grindstone::GraphicsAPI::GraphicsPipeline']]],
  ['pipelineset_20tt_20and_20tt_20computeset_20tt_17',['&lt;tt&gt;pipelineSet&lt;/tt&gt; and &lt;tt&gt;computeSet&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md120',1,'']]],
  ['pipelinesetfileheader_18',['PipelineSetFileHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PipelineSetFileHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['platforms_19',['Platforms',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Platforms.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['platformwindows_20',['PlatformWindows',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PlatformWindows.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['plugin_21',['Plugin',['../md_pages_2Plugins_2Overview.html#autotoc_md61',1,'Example 1: Runtime Plugin'],['../md_pages_2Plugins_2Overview.html#autotoc_md62',1,'Example 2: Editor Plugin']]],
  ['plugin_20folder_20structure_22',['Plugin Folder Structure',['../md_pages_2Plugins_2NewDesign.html#autotoc_md53',1,'']]],
  ['plugin_20implementation_23',['Plugin Implementation',['../md_pages_2Plugins_2Overview.html#autotoc_md60',1,'']]],
  ['plugin_20list_24',['Plugin List',['../md_pages_2Plugins_2Overview.html#autotoc_md58',1,'']]],
  ['plugin_20manifests_25',['Plugin Manifests',['../md_pages_2Plugins_2NewDesign.html#autotoc_md49',1,'']]],
  ['plugin_20metadata_26',['Plugin Metadata',['../md_pages_2Plugins_2NewDesign.html#autotoc_md55',1,'']]],
  ['plugin_20registry_27',['Plugin Registry',['../md_pages_2Plugins_2NewDesign.html#autotoc_md51',1,'']]],
  ['plugin_20system_202_200_20specification_28',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['plugin_20system_20roadmap_29',['Grindstone Plugin System Roadmap',['../md_pages_2Plugins_2Overview.html',1,'']]],
  ['pluginbuildsettings_30',['PluginBuildSettings',['../classGrindstone_1_1BuildSettings_1_1PluginBuildSettings.html',1,'Grindstone::BuildSettings']]],
  ['pluginlistelement_31',['PluginListElement',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1PluginListElement.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['pluginswindow_32',['PluginsWindow',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1PluginsWindow.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['pointlightcomponent_33',['PointLightComponent',['../structGrindstone_1_1PointLightComponent.html',1,'Grindstone']]],
  ['points_34',['Shader Entry Points',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md129',1,'']]],
  ['poolallocator_35',['PoolAllocator',['../classGrindstone_1_1Memory_1_1Allocators_1_1PoolAllocator.html',1,'Grindstone::Memory::Allocators']]],
  ['positionkeyframe_36',['PositionKeyframe',['../structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1PositionKeyframe.html',1,'Grindstone::Formats::Animation::V1']]],
  ['post_20processing_37',['Post Processing',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md74',1,'Post-Processing'],['../md_pages_2Rendering_2Overview.html#autotoc_md109',1,'Post-Processing']]],
  ['practices_38',['Best Practices',['../md_pages_2Rendering_2Materials.html#autotoc_md96',1,'']]],
  ['printmessageevent_39',['PrintMessageEvent',['../structGrindstone_1_1Events_1_1PrintMessageEvent.html',1,'Grindstone::Events']]],
  ['processing_40',['Processing',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md74',1,'Post-Processing'],['../md_pages_2Rendering_2Overview.html#autotoc_md109',1,'Post-Processing']]],
  ['project_41',['Building the Project',['../md_pages_2BuildingTheProject.html',1,'']]],
  ['projectsettingswindow_42',['ProjectSettingsWindow',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1ProjectSettingsWindow.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['properties_43',['2. Material Properties',['../md_pages_2Rendering_2Materials.html#autotoc_md83',1,'']]],
  ['properties_20tt_44',['&lt;tt&gt;properties&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md133',1,'']]],
  ['purpose_45',['Purpose',['../md_pages_2Assets_2Overview.html#autotoc_md19',1,'']]]
];
