var searchData=
[
  ['pagedata_0',['PageData',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PageData.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['parameter_1',['Parameter',['../structGrindstone_1_1PipelineAssetMetaData_1_1Parameter.html',1,'Grindstone::PipelineAssetMetaData']]],
  ['parametervalue_2',['ParameterValue',['../unionGrindstone_1_1PipelineAssetMetaData_1_1ParameterValue.html',1,'Grindstone::PipelineAssetMetaData']]],
  ['parentcomponent_3',['ParentComponent',['../structGrindstone_1_1ParentComponent.html',1,'Grindstone']]],
  ['pass_4',['Pass',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md71',1,'Lighting Pass'],['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md70',1,'Opaque Geometry Pass'],['../structGrindstone_1_1GraphicsPipelineAsset_1_1Pass.html',1,'Grindstone::GraphicsPipelineAsset::Pass']]],
  ['pass_5',['&lt;span class=&quot;tt&quot;&gt;pass&lt;/span&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md124',1,'']]],
  ['passbufferdesc_6',['PassBufferDesc',['../structGrindstone_1_1Renderer_1_1PassBufferDesc.html',1,'Grindstone::Renderer']]],
  ['passdescriptorbinding_7',['PassDescriptorBinding',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorBinding.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passdescriptorset_8',['PassDescriptorSet',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassDescriptorSet.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passes_9',['Unlit, Sky, and Transparent Passes',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md72',1,'']]],
  ['passimagedesc_10',['PassImageDesc',['../structGrindstone_1_1Renderer_1_1PassImageDesc.html',1,'Grindstone::Renderer']]],
  ['passpipelineattachmentheader_11',['PassPipelineAttachmentHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineAttachmentHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passpipelineheader_12',['PassPipelineHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['passpipelineshaderstageheader_13',['PassPipelineShaderStageHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PassPipelineShaderStageHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['patterns_14',['Usage Patterns',['../md_pages_2Assets_2Overview.html#autotoc_md35',1,'']]],
  ['pipeline_15',['Pipeline',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md149',1,'Example 1: Graphics Pipeline'],['../md_pages_2Rendering_2PipelineSets.html#autotoc_md151',1,'Example 2: Compute Pipeline']]],
  ['pipeline_20configuration_20keywords_16',['Pipeline Configuration Keywords',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md128',1,'']]],
  ['pipeline_20system_20documentation_17',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['pipelinedata_18',['PipelineData',['../structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1PipelineData.html',1,'Grindstone::GraphicsAPI::GraphicsPipeline']]],
  ['pipelinelayout_19',['PipelineLayout',['../classGrindstone_1_1GraphicsAPI_1_1PipelineLayout.html',1,'Grindstone::GraphicsAPI']]],
  ['pipelinerendergraphbuilderpass_20',['PipelineRenderGraphBuilderPass',['../classGrindstone_1_1Renderer_1_1PipelineRenderGraphBuilderPass.html',1,'Grindstone::Renderer']]],
  ['pipelinerendergraphpass_21',['PipelineRenderGraphPass',['../classGrindstone_1_1Renderer_1_1PipelineRenderGraphPass.html',1,'Grindstone::Renderer']]],
  ['pipelineset_20and_20computeset_22',['&lt;span class=&quot;tt&quot;&gt;pipelineSet&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;computeSet&lt;/span&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md120',1,'']]],
  ['pipelinesetfileheader_23',['PipelineSetFileHeader',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1PipelineSetFileHeader.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['platforms_24',['Platforms',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Platforms.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['platformwindows_25',['PlatformWindows',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1PlatformWindows.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['plugin_26',['Plugin',['../md_pages_2Plugins_2Overview.html#autotoc_md61',1,'Example 1: Runtime Plugin'],['../md_pages_2Plugins_2Overview.html#autotoc_md62',1,'Example 2: Editor Plugin']]],
  ['plugin_20folder_20structure_27',['Plugin Folder Structure',['../md_pages_2Plugins_2NewDesign.html#autotoc_md53',1,'']]],
  ['plugin_20implementation_28',['Plugin Implementation',['../md_pages_2Plugins_2Overview.html#autotoc_md60',1,'']]],
  ['plugin_20list_29',['Plugin List',['../md_pages_2Plugins_2Overview.html#autotoc_md58',1,'']]],
  ['plugin_20manifests_30',['Plugin Manifests',['../md_pages_2Plugins_2NewDesign.html#autotoc_md49',1,'']]],
  ['plugin_20metadata_31',['Plugin Metadata',['../md_pages_2Plugins_2NewDesign.html#autotoc_md55',1,'']]],
  ['plugin_20registry_32',['Plugin Registry',['../md_pages_2Plugins_2NewDesign.html#autotoc_md51',1,'']]],
  ['plugin_20system_202_200_20specification_33',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['plugin_20system_20roadmap_34',['Grindstone Plugin System Roadmap',['../md_pages_2Plugins_2Overview.html',1,'']]],
  ['pluginbuildsettings_35',['PluginBuildSettings',['../classGrindstone_1_1BuildSettings_1_1PluginBuildSettings.html',1,'Grindstone::BuildSettings']]],
  ['pluginlistelement_36',['PluginListElement',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1PluginListElement.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['pluginswindow_37',['PluginsWindow',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1PluginsWindow.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['pointlightcomponent_38',['PointLightComponent',['../structGrindstone_1_1PointLightComponent.html',1,'Grindstone']]],
  ['points_39',['Shader Entry Points',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md129',1,'']]],
  ['poolallocator_40',['PoolAllocator',['../classGrindstone_1_1Memory_1_1Allocators_1_1PoolAllocator.html',1,'Grindstone::Memory::Allocators']]],
  ['pooledbuffer_41',['PooledBuffer',['../structGrindstone_1_1Renderer_1_1TransientResourceManager_1_1PooledBuffer.html',1,'Grindstone::Renderer::TransientResourceManager']]],
  ['pooledimage_42',['PooledImage',['../structGrindstone_1_1Renderer_1_1TransientResourceManager_1_1PooledImage.html',1,'Grindstone::Renderer::TransientResourceManager']]],
  ['positionkeyframe_43',['PositionKeyframe',['../structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1PositionKeyframe.html',1,'Grindstone::Formats::Animation::V1']]],
  ['post_20processing_44',['Post Processing',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md74',1,'Post-Processing'],['../md_pages_2Rendering_2Overview.html#autotoc_md109',1,'Post-Processing']]],
  ['practices_45',['Best Practices',['../md_pages_2Rendering_2Materials.html#autotoc_md96',1,'']]],
  ['presentrendergraphbuilderpass_46',['PresentRenderGraphBuilderPass',['../classGrindstone_1_1Renderer_1_1PresentRenderGraphBuilderPass.html',1,'Grindstone::Renderer']]],
  ['presentrendergraphpass_47',['PresentRenderGraphPass',['../classGrindstone_1_1Renderer_1_1PresentRenderGraphPass.html',1,'Grindstone::Renderer']]],
  ['printmessageevent_48',['PrintMessageEvent',['../structGrindstone_1_1Events_1_1PrintMessageEvent.html',1,'Grindstone::Events']]],
  ['processing_49',['Processing',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md74',1,'Post-Processing'],['../md_pages_2Rendering_2Overview.html#autotoc_md109',1,'Post-Processing']]],
  ['project_50',['Building the Project',['../md_pages_2BuildingTheProject.html',1,'']]],
  ['projectsettingswindow_51',['ProjectSettingsWindow',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1ProjectSettingsWindow.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['properties_52',['2. Material Properties',['../md_pages_2Rendering_2Materials.html#autotoc_md83',1,'']]],
  ['properties_53',['&lt;span class=&quot;tt&quot;&gt;properties&lt;/span&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md133',1,'']]],
  ['purpose_54',['Purpose',['../md_pages_2Assets_2Overview.html#autotoc_md19',1,'']]]
];
