var searchData=
[
  ['sampler_0',['Sampler',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1Sampler.html',1,'Grindstone::Editor::ImguiEditor::Sampler'],['../classGrindstone_1_1GraphicsAPI_1_1Sampler.html',1,'Grindstone::GraphicsAPI::Sampler']]],
  ['sampleroptions_1',['SamplerOptions',['../structGrindstone_1_1GraphicsAPI_1_1SamplerOptions.html',1,'Grindstone::GraphicsAPI']]],
  ['samplers_2',['3. Material Resources (Textures and Samplers)',['../md_pages_2Rendering_2Materials.html#autotoc_md84',1,'']]],
  ['scalekeyframe_3',['ScaleKeyframe',['../structGrindstone_1_1Formats_1_1Animation_1_1V1_1_1ScaleKeyframe.html',1,'Grindstone::Formats::Animation::V1']]],
  ['scene_4',['Scene',['../md_pages_2Rendering_2Materials.html#autotoc_md88',1,'Applying Materials in a Scene'],['../classGrindstone_1_1SceneManagement_1_1Scene.html',1,'Grindstone::SceneManagement::Scene']]],
  ['scenebuildsettings_5',['SceneBuildSettings',['../classGrindstone_1_1BuildSettings_1_1SceneBuildSettings.html',1,'Grindstone::BuildSettings']]],
  ['scenedata_6',['SceneData',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1Build_1_1SceneData.html',1,'Grindstone::Editor::ImguiEditor::Settings::Build']]],
  ['sceneheirarchypanel_7',['SceneHeirarchyPanel',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1SceneHeirarchyPanel.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['sceneloaderjson_8',['SceneLoaderJson',['../classGrindstone_1_1SceneManagement_1_1SceneLoaderJson.html',1,'Grindstone::SceneManagement']]],
  ['scenemanager_9',['SceneManager',['../classGrindstone_1_1SceneManagement_1_1SceneManager.html',1,'Grindstone::SceneManagement']]],
  ['scenewriterjson_10',['SceneWriterJson',['../classGrindstone_1_1SceneManagement_1_1SceneWriterJson.html',1,'Grindstone::SceneManagement']]],
  ['selection_11',['Selection',['../classGrindstone_1_1Editor_1_1Selection.html',1,'Grindstone::Editor']]],
  ['setdatacommand_12',['SetDataCommand',['../classGrindstone_1_1Editor_1_1SetDataCommand.html',1,'Grindstone::Editor']]],
  ['settingswindow_13',['SettingsWindow',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1Settings_1_1SettingsWindow.html',1,'Grindstone::Editor::ImguiEditor::Settings']]],
  ['shader_20entry_20points_14',['Shader Entry Points',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md129',1,'']]],
  ['shader_20pipeline_20system_20documentation_15',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['shader_20reference_20graphicspipelineset_16',['1. Shader Reference (GraphicsPipelineSet)',['../md_pages_2Rendering_2Materials.html#autotoc_md82',1,'']]],
  ['shaderblock_20tt_17',['&lt;tt&gt;shaderBlock&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md144',1,'']]],
  ['shaderhlsl_20tt_18',['&lt;tt&gt;shaderHlsl&lt;/tt&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md147',1,'']]],
  ['shaderreflectdescriptorbinding_19',['ShaderReflectDescriptorBinding',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorBinding.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['shaderreflectdescriptorset_20',['ShaderReflectDescriptorSet',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectDescriptorSet.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['shaderreflectinputvariables_21',['ShaderReflectInputVariables',['../structGrindstone_1_1Formats_1_1Pipelines_1_1V1_1_1ShaderReflectInputVariables.html',1,'Grindstone::Formats::Pipelines::V1']]],
  ['shaders_22',['Shaders',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md143',1,'']]],
  ['shaderstagedata_23',['ShaderStageData',['../structGrindstone_1_1GraphicsAPI_1_1GraphicsPipeline_1_1ShaderStageData.html',1,'Grindstone::GraphicsAPI::GraphicsPipeline']]],
  ['shapemetadata_24',['ShapeMetaData',['../structGrindstone_1_1Editor_1_1GizmoRenderer_1_1ShapeMetaData.html',1,'Grindstone::Editor::GizmoRenderer']]],
  ['sharedptr_25',['SharedPtr',['../classGrindstone_1_1SharedPtr.html',1,'Grindstone']]],
  ['sharedptrrefcounter_26',['SharedPtrRefCounter',['../structGrindstone_1_1SharedPtr_1_1SharedPtrRefCounter.html',1,'Grindstone::SharedPtr']]],
  ['singlecastobservable_27',['SinglecastObservable',['../classGrindstone_1_1SinglecastObservable.html',1,'Grindstone']]],
  ['sky_20and_20transparent_20passes_28',['Unlit, Sky, and Transparent Passes',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md72',1,'']]],
  ['solutionbuilder_29',['SolutionBuilder',['../classGrindstone_1_1Editor_1_1ScriptBuilder_1_1SolutionBuilder.html',1,'Grindstone::Editor::ScriptBuilder']]],
  ['span_30',['Span',['../classGrindstone_1_1Containers_1_1Span.html',1,'Grindstone::Containers']]],
  ['span_3c_20grindstone_3a_3abyte_20_3e_31',['Span&lt; Grindstone::Byte &gt;',['../classGrindstone_1_1Containers_1_1Span.html',1,'Grindstone::Containers']]],
  ['specificassetimporter_32',['SpecificAssetImporter',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20computepipelineasset_2c_20assettype_3a_3acomputepipelineset_20_3e_33',['SpecificAssetImporter&lt; ComputePipelineAsset, AssetType::ComputePipelineSet &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20graphicspipelineasset_2c_20assettype_3a_3agraphicspipelineset_20_3e_34',['SpecificAssetImporter&lt; GraphicsPipelineAsset, AssetType::GraphicsPipelineSet &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20materialasset_2c_20assettype_3a_3amaterial_20_3e_35',['SpecificAssetImporter&lt; MaterialAsset, AssetType::Material &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specificassetimporter_3c_20textureasset_2c_20assettype_3a_3atexture_20_3e_36',['SpecificAssetImporter&lt; TextureAsset, AssetType::Texture &gt;',['../classGrindstone_1_1SpecificAssetImporter.html',1,'Grindstone']]],
  ['specification_37',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['spotlightcomponent_38',['SpotLightComponent',['../structGrindstone_1_1SpotLightComponent.html',1,'Grindstone']]],
  ['stackallocator_39',['StackAllocator',['../classGrindstone_1_1Memory_1_1Allocators_1_1StackAllocator.html',1,'Grindstone::Memory::Allocators']]],
  ['stages_40',['Summary of Render Stages',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md69',1,'']]],
  ['statspanel_41',['StatsPanel',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatsPanel.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['statusbar_42',['StatusBar',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1StatusBar.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['step_201_3a_20create_20a_20custom_20asset_20type_43',['Step 1: Create a Custom Asset Type',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md6',1,'']]],
  ['step_201_3a_20create_20an_20asset_20importer_20function_44',['Step 1: Create an asset importer function',['../md_pages_2Assets_2CustomAssetEditorGuide.html#autotoc_md2',1,'']]],
  ['step_202_3a_20create_20an_20importer_20for_20it_45',['Step 2: Create an Importer for It',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md8',1,'']]],
  ['step_202_3a_20register_20the_20asset_20importer_46',['Step 2: Register the Asset Importer',['../md_pages_2Assets_2CustomAssetEditorGuide.html#autotoc_md4',1,'']]],
  ['step_203_3a_20register_20the_20asset_20type_47',['Step 3: Register the Asset Type',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md10',1,'']]],
  ['step_204_3a_20load_20and_20use_20the_20asset_48',['Step 4: Load and Use the Asset',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md12',1,'']]],
  ['storage_20for_20developers_49',['JSON-Based Storage (For Developers)',['../md_pages_2Rendering_2Materials.html#autotoc_md98',1,'']]],
  ['string_20_3a_50',['String :',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md15',1,'Access by Address (Hashed String):'],['../md_pages_2Assets_2Overview.html#autotoc_md39',1,'Access by Address (Hashed String):']]],
  ['structure_51',['Plugin Folder Structure',['../md_pages_2Plugins_2NewDesign.html#autotoc_md53',1,'']]],
  ['subasset_52',['Subasset',['../structGrindstone_1_1Editor_1_1ImguiEditor_1_1AssetBrowserPanel_1_1AssetBrowserItem_1_1Subasset.html',1,'Grindstone::Editor::ImguiEditor::AssetBrowserPanel::AssetBrowserItem::Subasset'],['../structGrindstone_1_1Editor_1_1MetaFile_1_1Subasset.html',1,'Grindstone::Editor::MetaFile::Subasset']]],
  ['suggestedinput_53',['SuggestedInput',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1SuggestedInput.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['summary_20of_20render_20stages_54',['Summary of Render Stages',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md69',1,'']]],
  ['supported_20assets_55',['Supported Assets',['../md_pages_2Assets_2Overview.html#autotoc_md33',1,'']]],
  ['supported_20image_20formats_56',['Supported Image Formats',['../md_pages_2Rendering_2Textures.html#autotoc_md156',1,'']]],
  ['system_202_200_20specification_57',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['system_20documentation_58',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['system_20overview_59',['Grindstone Asset System Overview',['../md_pages_2Assets_2Overview.html',1,'']]],
  ['system_20roadmap_60',['Grindstone Plugin System Roadmap',['../md_pages_2Plugins_2Overview.html',1,'']]],
  ['systempanel_61',['SystemPanel',['../classGrindstone_1_1Editor_1_1ImguiEditor_1_1SystemPanel.html',1,'Grindstone::Editor::ImguiEditor']]],
  ['systemregistrar_62',['SystemRegistrar',['../classGrindstone_1_1ECS_1_1SystemRegistrar.html',1,'Grindstone::ECS']]]
];
