var searchData=
[
  ['samplers_0',['3. Material Resources (Textures and Samplers)',['../md_pages_2Rendering_2Materials.html#autotoc_md84',1,'']]],
  ['scene_1',['Applying Materials in a Scene',['../md_pages_2Rendering_2Materials.html#autotoc_md88',1,'']]],
  ['shader_20entry_20points_2',['Shader Entry Points',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md129',1,'']]],
  ['shader_20pipeline_20system_20documentation_3',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['shader_20reference_20graphicspipelineset_4',['1. Shader Reference (GraphicsPipelineSet)',['../md_pages_2Rendering_2Materials.html#autotoc_md82',1,'']]],
  ['shaderblock_5',['&lt;span class=&quot;tt&quot;&gt;shaderBlock&lt;/span&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md144',1,'']]],
  ['shaderhlsl_6',['&lt;span class=&quot;tt&quot;&gt;shaderHlsl&lt;/span&gt;',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md147',1,'']]],
  ['shaders_7',['Shaders',['../md_pages_2Rendering_2PipelineSets.html#autotoc_md143',1,'']]],
  ['sky_20and_20transparent_20passes_8',['Unlit, Sky, and Transparent Passes',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md72',1,'']]],
  ['specification_9',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['stages_10',['Summary of Render Stages',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md69',1,'']]],
  ['step_201_3a_20create_20a_20custom_20asset_20type_11',['Step 1: Create a Custom Asset Type',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md6',1,'']]],
  ['step_201_3a_20create_20an_20asset_20importer_20function_12',['Step 1: Create an asset importer function',['../md_pages_2Assets_2CustomAssetEditorGuide.html#autotoc_md2',1,'']]],
  ['step_202_3a_20create_20an_20importer_20for_20it_13',['Step 2: Create an Importer for It',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md8',1,'']]],
  ['step_202_3a_20register_20the_20asset_20importer_14',['Step 2: Register the Asset Importer',['../md_pages_2Assets_2CustomAssetEditorGuide.html#autotoc_md4',1,'']]],
  ['step_203_3a_20register_20the_20asset_20type_15',['Step 3: Register the Asset Type',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md10',1,'']]],
  ['step_204_3a_20load_20and_20use_20the_20asset_16',['Step 4: Load and Use the Asset',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md12',1,'']]],
  ['storage_20for_20developers_17',['JSON-Based Storage (For Developers)',['../md_pages_2Rendering_2Materials.html#autotoc_md98',1,'']]],
  ['string_20_3a_18',['String :',['../md_pages_2Assets_2CustomAssetRuntimeGuide.html#autotoc_md15',1,'Access by Address (Hashed String):'],['../md_pages_2Assets_2Overview.html#autotoc_md39',1,'Access by Address (Hashed String):']]],
  ['structure_19',['Plugin Folder Structure',['../md_pages_2Plugins_2NewDesign.html#autotoc_md53',1,'']]],
  ['summary_20of_20render_20stages_20',['Summary of Render Stages',['../md_pages_2Rendering_2DeferredRenderer.html#autotoc_md69',1,'']]],
  ['supported_20assets_21',['Supported Assets',['../md_pages_2Assets_2Overview.html#autotoc_md33',1,'']]],
  ['supported_20image_20formats_22',['Supported Image Formats',['../md_pages_2Rendering_2Textures.html#autotoc_md156',1,'']]],
  ['system_202_200_20specification_23',['Plugin System 2.0 Specification',['../md_pages_2Plugins_2NewDesign.html',1,'']]],
  ['system_20documentation_24',['Shader Pipeline System Documentation',['../md_pages_2Rendering_2PipelineSets.html',1,'']]],
  ['system_20overview_25',['Grindstone Asset System Overview',['../md_pages_2Assets_2Overview.html',1,'']]],
  ['system_20roadmap_26',['Grindstone Plugin System Roadmap',['../md_pages_2Plugins_2Overview.html',1,'']]]
];
