SET(_rapidjson_HEADER_SEARCH_DIRS
"/usr/include"
"/usr/local/include"
"C:/Program Files (x86)/rapidjson" )
# check environment variable
SET(_rapidjson_ENV_ROOT_DIR "$ENV{RAPIDJSON_ROOT_DIR}")
IF(NOT RAPIDJSON_ROOT_DIR AND _rapidjson_ENV_ROOT_DIR)
	SET(RAPIDJSON_ROOT_DIR "${_rapidjson_ENV_ROOT_DIR}")
ENDIF(NOT RAPIDJSON_ROOT_DIR AND _rapidjson_ENV_ROOT_DIR)
# put user specified location at beginning of search
IF(RAPIDJSON_ROOT_DIR)
	SET(_rapidjson_HEADER_SEARCH_DIRS "${RAPIDJSON_ROOT_DIR}"
	"${RAPIDJSON_ROOT_DIR}/include"
	${_rapidjson_HEADER_SEARCH_DIRS})
ENDIF(RAPIDJSON_ROOT_DIR)
# locate header
FIND_PATH(RAPIDJSON_INCLUDE_DIR "include/rapidjson/rapidjson.h"
PATHS ${_rapidjson_HEADER_SEARCH_DIRS})
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RAPIDJSON DEFAULT_MSG
RAPIDJSON_INCLUDE_DIR)
IF(RAPIDJSON_FOUND)
	SET(RAPIDJSON_INCLUDE_DIRS "${RAPIDJSON_INCLUDE_DIR}/include")
	MESSAGE(STATUS "RAPIDJSON_INCLUDE_DIR = ${RAPIDJSON_INCLUDE_DIR}")
ELSE(RAPIDJSON_FOUND)
	MESSAGE(FATAL_ERROR "RAPIDJSON not found!")
ENDIF(RAPIDJSON_FOUND)
