name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows
            cmake-preset: windows-release
            config: Debug

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Get CMake
        uses: lukka/get-cmake@v4.4.2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '319504a5326aa870edde46438c5455fa76305a56'
          runVcpkgInstall: false

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.cmake-preset }}
          buildPreset: ${{ matrix.cmake-preset }}

      - name: Run Unit Tests
        shell: pwsh
        run: |
          ctest `
            --test-dir build/package/windows-latest `
            --output-on-failure

      - name: Package
        shell: pwsh
        run: |
          cmake --install build/windows-release `
            --config ${{ matrix.config }} `
            --prefix build/package/${{ matrix.os }}

      - name: Upload build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: grindstone-${{ matrix.os }}-build
          path: build/package/${{ matrix.os }}/
          if-no-files-found: error
