#ifndef _C_BASE_H
#define _C_BASE_H

enum ComponentType {
	COMPONENT_POSITION = 0,
	COMPONENT_MODEL,
	COMPONENT_TERRAIN,
	COMPONENT_RENDER,
	COMPONENT_LIGHT_POINT,
	COMPONENT_LIGHT_SPOT,
	COMPONENT_LIGHT_DIRECTIONAL,
	COMPONENT_PHYSICS,
	COMPONENT_INPUT,
	COMPONENT_AUDIO,
	COMPONENT_SCRIPT,
	COMPONENT_GAME_LOGIC,
	NUM_COMPONENTS,
	// Keeping this after, as it has to have an ID but shouldn't affect NUM_COMPONENTS
	COMPONENT_BASE
};

class CBase {
public:
	unsigned char componentType;
	unsigned int entityID;
};

#endif